<?php
$string['install']="Php-Stats %php-stats-ver% - Update";
$string['lang_select']="Sélectionnez votre langue : :";
$string['license']="<b>Conditions de licence</b>";
$string['license_ok']="I J'ACCEPTE";
$string['license_no']="I JE REFUSE";
$string['license_agree']="<b>En procédant à l'update, vous acceptez toutes ces conditions de licence</b>";
$string['next']="Suivant ->";
$string['end']=">> Fin <<";
$string['box_title']="Attention:";
$string['box_title_ok']="Information:";
$string['done']="Update reussit.";

// ERROR HANDLING
$error['no_min_ver']="<b>ERREUR</b>: Php-Stats PRO 0.1.3 or later est demander pour reussir l'update.";
$error['no_ver_detect']="<b>ERREUR</b>: Impossible de detecter la version de Php-Stats PRO ";
$error['noupdateneed']="Pas besion d'update pour votre Php-Stats PRO.";
$error['error_updating']="<b>ATTENTION: ERREUR CRITIQUE</b><br><br>Il est conseillé de prendre note des éventuelles erreurs et de les rapporter sur le forum du support : <a href=\"http://www.php-stats.com/forum/\" target=\"_BLANK\">http://www.php-stats.com/forum/</a><br>
                          <br><b>La procédure d'installation a été interrompue .</b>";
$error['nowrite_server']="<b>ATTENTION:</b> il est impossible d'ecrire des fichier sur le serbeur.<br>Mettre en 777 l'option des doissiers<br>Avant de continuer <b>vous devez remplacer</b> les fichiers:<br><b>php-stats.php, php-stats.recphp.php, php-stats.recjs.php and admin.php</b><br>remplacer par ceux du dossier <b>files_noWrite</b> <br>";?>
