<?php
$string['install']="Installation";
$string['lang_select']="Sélectionnez votre langue : ";
$string['license']="<b>Conditions de licence</b>";
$string['license_agree']="<b>En procédant à l'installation, vous acceptez toutes ces conditions de licence</b>";
$string['license_ok']="J'ACCEPTE";
$string['license_no']="JE REFUSE";
$string['next']="Suivant ->";
$string['end']=">> Fin. <<";
$string['step_1_1']="Les tables nécessaires à l'utilisation de ce script vont être créées.";
$string['step_1_2']="<b>ATTENTION</b>: si les tables existent déjà, elles seront effacées et remplacées.";
$string['step_3_1']="Entrez votre mot de passe : ";
$string['step_3_2']="Entrez à nouveau votre mot de passe : ";
$string['step_4_1']="<b>ATTENTION</b>: Rappellez-vous d'effacer le fichier <b>setup.php</b> et le répertoire <b>setup_files</b>.";
$string['step_4_2']="<b>NOTE</b>: Dans les pages à suivre, insérez le code suivant : ";
$string['step_4_3']="En cas de problèmes, utilisez l'adresse <a href=\"http://www.php-stats.com/forum/\" target=\"_blank\">forum de discussions</a>.";
$string['box_title']="Attention : ";
$string['done']="Les tables ont été créés correctement.";
// ERROR HANDLING
$error['error_updating']="<b>ATTENTION: ERREUR CRITIQUE</b><br><br>Il est conseillé de prendre note des éventuelles erreurs et de les rapporter sur le forum du support : <a href=\"http://www.php-stats.com/forum/\" target=\"_BLANK\">http://www.php-stats.com/forum/</a><br>
                          <br><b>La procédure d'installation a été interrompue .</b>";
$error['error_config']="Php-Stats ne peut pas créer le fichier config.php , setup is interrompue.<br><br>pour rinstaller php stats , svp effacer le fichier <b>php-stats.lock</b>"; 
$error['locked']="Php-Stats PRO semble déjà être installé et la procédure d'installation sera terminée.<br><br>Si vous voulez réinstaller Php-Stats PRO, effacer en premier le fichier <b>php-stats.lock</b>";
$error['nowrite_server']="<b>ATTENTION:</b> il est impossible d'ecrire des fichier sur le serbeur.<br>Mettre en 777 l'option des doissiers<br>Avant de continuer <b>vous devez remplacer</b> les fichiers:<br><b>php-stats.php, php-stats.recphp.php, php-stats.recjs.php and admin.php</b><br>remplacer par ceux du dossier <b>files_noWrite</b> <br>"; 

?>
