<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 4                     */
/* CACHE FILE: Generated: Wed, 31 Aug 2005 00:22:48 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_ucp {

//===========================================================================
// attachments_row
//===========================================================================
function attachments_row($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr id="{$data['attach_id']}">
		<td align="center" class="row1"><img src="{$ibforums->vars['mime_img']}/{$data['image']}" alt="{$ibforums->lang['attached_file']}" /></td>
		<td class="row2">
			<a href="{$ibforums->base_url}act=Attach&amp;type={$data['_type']}&amp;id={$data['attach_id']}" title="{$data['attach_file']}" target="_blank">{$data['short_name']}</a>
			<div class="desc">( {$ibforums->lang['attach_hits']}: {$data['attach_hits']} )</div>
		</td>
		<td align="center" class="row1">{$data['real_size']}</td>
		<td class="row2">
EOF;
//startif
if ( $data['attach_pid'] > 0 )
{
$IPBHTML .= <<<EOF
<a href="{$ibforums->base_url}showtopic={$data['tid']}&amp;view=findpost&amp;p={$data['attach_pid']}">{$data['title']}</a>
EOF;
}//endif
else
{
$IPBHTML .= <<<EOF
{$data['title']}
EOF;
}//endelse
$IPBHTML .= <<<EOF
				<br />
			<span class="desc">{$data['attach_date']}</span>
		</td>
		<td class="row2" align="center"><input type="checkbox" name="attach_{$data['attach_id']}" value="1" class="checkbox" /></td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// attachments_top
//===========================================================================
function attachments_top($info="",$pages="",$attach_html="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<!-- inbox folder -->
<div class="formsubtitle">{$ibforums->lang['m_attach']}</div>
EOF;
//startif
if ( $info['has_limit'] == 1 )
{
$IPBHTML .= <<<EOF
<table cellspacing="0">
		<tr>
			<td valign="middle">
				<!-- LEFT -->
				<table cellspacing="1" class="inbox">
					<tr>
						<td class="row1" colspan="3">{$ibforums->lang['attach_space_used']}</td>
					</tr>
					<tr>
						<td valign="middle" class="row1" colspan="3"><{BAR_LEFT}><img src="{$ibforums->vars['img_url']}/bar.gif" width="{$info['img_width']}" height="11" align="middle" alt="" /><{BAR_RIGHT}></td>
					</tr>
					<tr>
						<td class="row1" width="33%" valign="middle">0%</td>
						<td class="row1" width="33%" align="center" valign="middle">50%</td>
						<td class="row1" width="33%" align="right" valign="middle">100%</td>
					</tr>
				</table>
			</td>
			
			<!-- RIGHT -->
			<td align="right" valign="bottom">$pages<br /><br />{$ibforums->lang['attach_space_count']}</td>
		</tr>
	</table>
EOF;
}//endif
else
{
$IPBHTML .= <<<EOF
<table cellspacing="0">
	<tr>
		<td>
			<!-- LEFT -->
			{$ibforums->lang['attach_space_used']}
		</td>
		<td align="right">
			<!-- RIGHT -->
			$pages
		</td>
	</tr>
</table>
EOF;
}//endelse

$IPBHTML .= <<<EOF
<!-- ATTACHMENTS TABLE -->
  
<form action="{$ibforums->base_url}act=usercp&amp;CODE=attach&amp;sort={$ibforums->input['sort']}" name="mutliact" method="post">
<div class="borderwrapm">
	<table cellspacing="1">
		<tr>
			<th width="2%">&nbsp;</th>
			<th width="35%"><b>{$ibforums->lang['attach_title']}</b></th>
			<th width="5%"><b>{$ibforums->lang['attach_hsize']}</b></th>
			<th width="27%"><b>{$ibforums->lang['attach_topic']}</b></a></th>
			<th width="5%" align="center"><input name="allbox" type="checkbox" value="Check All" onclick="InboxCheckAll();" /></th>
		</tr>
EOF;
//startif
if ( $attach_html != "" )
{
$IPBHTML .= <<<EOF
{$attach_html}
		<tr>
			<td colspan="6" align="right" class="formbuttonrow"><input type="submit" value="{$ibforums->lang['attach_delete']}" class="button" /></td>
		</tr>
EOF;
}//endif
else
{
$IPBHTML .= <<<EOF
<tr>
			<td colspan="6" align="center">{$ibforums->lang['splash_noattach']}</td>
		</tr>
EOF;
}//endelse
$IPBHTML .= <<<EOF
	</table>
</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_autosize
//===========================================================================
function avatar_autosize() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<table cellspacing="0">
	<tr>
		<td class="pformleft">&nbsp;</td>
		<td class="pformright"><b>{$ibforums->lang['av_autosize']}</b><br />({$ibforums->lang['av_as_desc']})</td>
	</tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_external_title
//===========================================================================
function avatar_external_title() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['avatar_url_title']}</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_gallery_blank_row
//===========================================================================
function avatar_gallery_blank_row() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<td>&nbsp;</td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_gallery_cell_row
//===========================================================================
function avatar_gallery_cell_row($img="",$txt="",$form="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<td align="center"><img src="style_avatars{$img}" alt="txt" /><br /><input type="radio" class="radiobutton" name="avatar" value="$form" id="$form" />&nbsp;<b><label for="$form">$txt</label></b></td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_gallery_end_row
//===========================================================================
function avatar_gallery_end_row() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_gallery_end_table
//===========================================================================
function avatar_gallery_end_table() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</table>
<div align="center" class="formsubtitle">
	<input type="submit" name="submit" value="{$ibforums->lang['av_gall_submit']}" />
	&nbsp;&nbsp;&nbsp;<input type="button" name="remove" onclick="self.location='{$ibforums->base_url}act=UserCP&amp;CODE=24';" value="{$ibforums->lang['av_gall_cancel']}" />
</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_gallery_start_row
//===========================================================================
function avatar_gallery_start_row() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_gallery_start_table
//===========================================================================
function avatar_gallery_start_table($title="",$av_gals="",$current_folder="",$key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['av_gallery_title']} $title</div>
<form action="{$ibforums->base_url}act=UserCP&amp;CODE=getgallery" method="post">
	<div id="padandcenter"><b>{$ibforums->lang['av_gall_jump']}</b>&nbsp;$av_gals&nbsp;&nbsp;<input type="submit" value="{$ibforums->lang['av_go_go']}" name="submit" /></div>
</form>
<form action="{$ibforums->base_url}auth_key=$key" method="post">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="setinternalavatar" />
<input type="hidden" name="current_folder" value="$current_folder" />
	<table cellspacing="0">
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_limits
//===========================================================================
function avatar_limits() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['av_settings']}</div>
	<p>{$ibforums->lang['av_text_url']} {$ibforums->lang['av_text_upload']}<br />{$ibforums->lang['av_allowed_files']}</p>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_main
//===========================================================================
function avatar_main($data="",$formextra="",$hidden_field="",$key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
var url_input      = "{$data['current_url_avatar']}";
var remove_pressed = 0;
	function select_url(){
		restore_it();
	}
	
	function select_upload(){
		try{
			if ( document.creator.url_avatar.value != "" ) {
				url_input = document.creator.url_avatar.value;
			}
			document.creator.url_avatar.value = "";
		}
		catch(nourl){
			return true;
		}
	}
	
	function restore_it(){
		if (url_input != ""){
			document.creator.url_avatar.value = url_input;
			}
		}
	function checkform(){
		if ( remove_pressed != 1 ){
			return true;
		}
	
		else{
			fcheck = confirm("{$ibforums->lang['av_confirm']}");
			if ( fcheck == true ){
				return true;
			}
			else{
				return false;
				}
			}
	}
-->
</script>
<!--IBF.LIMITS_AVATAR-->
<div class="formsubtitle">{$ibforums->lang['av_current']}</div>
<div class="tablepad" align="center">{$data['current_avatar_image']}<br />{$data['current_avatar_type']} {$data['current_avatar_dims']}</div>
<div class="formsubtitle">{$ibforums->lang['avatar_pre_title']}</div>
<form action="{$ibforums->base_url}act=UserCP&amp;CODE=getgallery" method="post">
	<table cellspacing="0">
		<tr>
			<td class="pformleft">{$ibforums->lang['av_go_gal']}</td>
			<td class="pformright">{$data['avatar_galleries']}&nbsp;&nbsp;<input type="submit" value="{$ibforums->lang['av_go_go']}" name="submit" /></td>
		</tr>
	</table>
</form>
<form action="{$ibforums->base_url}auth_key=$key" method="post" $formextra name="creator" onsubmit="return checkform();">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="25" />
$hidden_field
<!--IBF.EXTERNAL_TITLE-->
<!--IBF.URL_AVATAR-->
<!--IBF.UPLOAD_AVATAR-->
<!--IPB.SIZE-->
	<div align="center" class="formsubtitle">
		<input type="submit" name="submit" value="{$ibforums->lang['av_update']}" />
		&nbsp;&nbsp;&nbsp;<input type="submit" name="remove" onclick="remove_pressed=1;" value="{$ibforums->lang['av_remove']}" />
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_mansize
//===========================================================================
function avatar_mansize() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<table cellspacing="0">
	<tr>
		<td class="pformleft">&nbsp;</td>
		<td class="pformright"><b>{$ibforums->lang['width']}</b>&nbsp;<input type="text" size="3" name="man_width" />&nbsp;&nbsp;<b>{$ibforums->lang['height']}</b>&nbsp;<input type="text" size="3" name="man_height" /></td>
	</tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_upload_field
//===========================================================================
function avatar_upload_field($text="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
				<tr>
                <td class='row1' width='40%' valign='top'><b>{$ibforums->lang['upload_avatar']}</b></td>
                <td class='row1'><input type='file' size='30' name='FILE_UPLOAD' class='forminput' onfocus='select_upload()' onclick='select_upload()'><br>$text</td>
                </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_url_field
//===========================================================================
function avatar_url_field($avatar="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<table cellspacing="0">
	<tr>
		<td class="pformleft">{$ibforums->lang['av_url']}</td>
		<td class="pformright"><input type="text" size="40" maxlength="80" name="url_avatar" value="$avatar" onfocus="select_url()" />&nbsp;&nbsp;(<a href="javascript:restore_it()">{$ibforums->lang['pp_restore']}</a>)</td>
	</tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// birthday
//===========================================================================
function birthday($day="",$month="",$year="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
            <tr>
            <td class='row2' width='40%'><b>{$ibforums->lang['birthday']}</b></td>
            <td class='row2'>
            <select name='day' class='forminput'>{$day}</select> 
            <select name='month' class='forminput'>{$month}</select> 
            <select name='year' class='forminput'>{$year}</select>
            </td>
            </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// CP_end
//===========================================================================
function CP_end() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
          <!-- end main CP area -->
        
       </table>
       </td>
      </tr>
      </table>
    </td>
  </tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// dead_section
//===========================================================================
function dead_section() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['dead_section_title']}</div>
<p>
	{$ibforums->lang['dead_section_text']}
</p>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// email
//===========================================================================
function email($Profile="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form action="{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}" method="post">
     <input type='hidden' name='act' value='UserCP'>
     <input type='hidden' name='CODE' value='03'>
     <input type='hidden' name='s' value='{$ibforums->session_id}'>
                   <td valign='left' colspan='2' class='category'><b>{$ibforums->lang['privacy_settings']}</b></td>
                 </tr>
                <tr>
                <td class='row1' align='right' valign='top'><input type='checkbox' name='hide_email' value='1' {$Profile['hide_email']}></td>
                <td class='row1' align='left' width='100%'>{$ibforums->lang['hide_email']}</td>
                </tr>  
                <tr>
                <td class='row1' align='right' valign='top'><input type='checkbox' name='admin_send' value='1' {$Profile['allow_admin_mails']}></td>
                <td class='row1' align='left'  width='100%'>{$ibforums->lang['admin_send']}</td>
                </tr>
                 <tr>
                   <td valign='left' colspan='2' class='category'><b>{$ibforums->lang['board_prefs']}</b></td>
                 </tr>
                <tr>
                <td class='row1' align='right' valign='top'><input type='checkbox' name='send_full_msg' value='1' {$Profile['email_full']}></td>
                <td class='row1' align='left'  width='100%'>{$ibforums->lang['send_full_msg']}</td>
                </tr>
                <tr>
                <td class='row1' align='right' valign='top'><input type='checkbox' name='pm_reminder' value='1' {$Profile['email_pm']}></td>
                <td class='row1' align='left'  width='100%'>{$ibforums->lang['pm_reminder']}</td>
                </tr>
                <tr>
                <td class='row1' align='right' valign='top'><input type='checkbox' name='auto_track' value='1' {$Profile['auto_track']}></td>
                <td class='row1' align='left'  width='100%'>{$ibforums->lang['auto_track']}</td>
                </tr>
                <tr>
                <td class='row2' align='center' colspan='2'>
                <input type="submit" value="{$ibforums->lang['submit_email']}" class='forminput'>
                </td></tr>
                </form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// email_change
//===========================================================================
function email_change($txt="",$regid="",$msg="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                   <td  colspan='2' class='category'><b>{$ibforums->lang['change_email_title']}</b></td>
                 </tr>
				
				 <script language='Javascript'>
				    var msg = "$msg";
				    if ( msg != "")
				    {
				    	alert(msg);
				    }
				 </script>
				 
                 <form action="{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}" method="post" name='form1'>
                 <input type='hidden' name='act' value='UserCP'>
                 <input type='hidden' name='CODE' value='09'>
                 <input type='hidden' name='s' value='{$ibforums->session_id}'>
                 <tr>
                 	<td class='row1' colspan='2'>$txt</td>
                 </tr>
                 <tr>
                   <td class='row1' nowrap><b>{$ibforums->lang['ce_new_email']}</b></td>
                   <td class='row1' width='70%' align='left'><input type='text' name='in_email_1' value='' class='forminput'></td>
                 </tr>
                  <tr>
                   <td class='row1' nowrap><b>{$ibforums->lang['ce_new_email2']}</b></td>
                   <td class='row1' width='70%' align='left'><input type='text' name='in_email_2' value='' class='forminput'></td>
                 </tr>
                 
				 <tr>
					 <td colspan='2'>
						 <table cellpadding='3' cellspacing='1' border='0' width='100%'>
						 <tr>
						 <td valign='left' colspan='2' class='titlemedium'>{$ibforums->lang['ras_title']}</td>
						 </tr>
						 <tr>
						 <td class='row1' width='40%'>{$ibforums->lang['ras_numbers']}</td>
						 <td class='row1'>
						  <input type='hidden' name='regid' value='$regid'>
						  <img src='{$ibforums->base_url}&act=UserCP&CODE=show_image&rc={$regid}&p=1' border='0' alt='Code Bit'>
						  &nbsp;<img src='{$ibforums->base_url}&act=UserCP&CODE=show_image&rc={$regid}&p=2' border='0' alt='Code Bit'>
						  &nbsp;<img src='{$ibforums->base_url}&act=UserCP&CODE=show_image&rc={$regid}&p=3' border='0' alt='Code Bit'>
						  &nbsp;<img src='{$ibforums->base_url}&act=UserCP&CODE=show_image&rc={$regid}&p=4' border='0' alt='Code Bit'>
						  &nbsp;<img src='{$ibforums->base_url}&act=UserCP&CODE=show_image&rc={$regid}&p=5' border='0' alt='Code Bit'>
						  &nbsp;<img src='{$ibforums->base_url}&act=UserCP&CODE=show_image&rc={$regid}&p=6' border='0' alt='Code Bit'>
						 </td>
						 </tr>
						 <tr>
						 <td class='row2' width='40%'>{$ibforums->lang['ras_text']}</td>
						 <td class='row2'><input type='text' size='32' maxlength='32' name='reg_code' class='forminput'></td>
						 </tr>
						 </table>
					 </td>
				 </tr>
                 
                 <tr>
                     <td class='row2' align='center' colspan='2'><input type="submit" name='change_email' value="{$ibforums->lang['account_email_submit']}" class='forminput'></td>
                 </tr>
                 </form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// email_change_gd
//===========================================================================
function email_change_gd($regid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['ras_title']}</div>
<table cellspacing="0">
	<tr>
		<td width="40%">{$ibforums->lang['ras_numbers']}</td>
		<td>
			<input type="hidden" name="regid" value="$regid" />
			<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}" alt="Code Bit" />
		</td>
	</tr>
	<tr>
		<td width="40%">{$ibforums->lang['ras_text']}</td>
		<td><input type="text" size="32" maxlength="32" name="reg_code" /></td>
	</tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// email_change_img
//===========================================================================
function email_change_img($regid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['ras_title']}</div>
<table cellspacing="0">
	<tr>
		<td width="40%">{$ibforums->lang['ras_numbers']}</td>
		<td>
			<input type="hidden" name="regid" value="$regid" />
				<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}&amp;p=1" alt="Code Bit" />
				&nbsp;<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}&amp;p=2" alt="Code Bit" />
				&nbsp;<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}&amp;p=3" alt="Code Bit" />
				&nbsp;<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}&amp;p=4" alt="Code Bit" />
				&nbsp;<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}&amp;p=5" alt="Code Bit" />
				&nbsp;<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}&amp;p=6" alt="Code Bit" />
		</td>
	</tr>
	<tr>
		<td width="40%">{$ibforums->lang['ras_text']}</td>
		<td><input type="text" size="32" maxlength="32" name="reg_code" /></td>
	</tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// field_dropdown
//===========================================================================
function field_dropdown($name="",$options="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
            <select name='$name' class='forminput'>$options</select>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// field_entry
//===========================================================================
function field_entry($title="",$desc="",$content="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
            <tr>
			<td class='row1' width='40%' valign='top'><b>$title</b><br>$desc</td>
			<td class='row1'>$content</td>
			</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// field_textarea
//===========================================================================
function field_textarea($name="",$value="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
            <textarea cols='60' rows='5' wrap='soft' name='$name' class='forminput'>$value</textarea>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// field_textinput
//===========================================================================
function field_textinput($name="",$value="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
            <input type='text' size='50' name='$name' value='$value' class='forminput'>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// forum_jump
//===========================================================================
function forum_jump($data="",$menu_extra="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
    <script language='Javascript'>
      <!--
		function jump_page(internal) {
			
			var f = document.jumpForm.themenu;
			
			var base_url = "{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&";
			
			if (f.options[f.selectedIndex].value == -1) {
				return false;
			}
			
			var l_data = f.options[f.selectedIndex].value;
			
			s_data = l_data.split("|");
			
			if (s_data[0] == 0) {
				window.location = base_url + s_data[1];
			}
			else {
				window.open( s_data[1], 'width=800,height=600,top=0,left=0,resizable=1,scrollbars=1,location=yes,directories=yes,status=yes,menubar=yes,toolbar=yes');
			}
			
		}
	  -->
    </script>
<br>
<table cellpadding='0' cellspacing='0' border='0' width='<{tbl_width}>' align='center'>
	<tr>
		<td align='left'>
		<form name='jumpForm'>
			<select name='themenu' onchange='jump_page("1")' class='forminput'>
    	            <option value='-1'>{$ibforums->lang['qc_header']}</option>
    	            <option value='0|act=Msg&CODE=00'>{$ibforums->lang['qc_messenger']}</option>
    				<option value='0|act=Msg&CODE=01&VID=in'>{$ibforums->lang['qc_inbox']}</option>
    				<option value='0|act=Msg&CODE=01&VID=sent'>{$ibforums->lang['qc_sent']}</option>
    				<option value='0|act=Msg&CODE=04'>{$ibforums->lang['qc_compose']}</option>
    				<option value='0|act=Msg&CODE=07'>{$ibforums->lang['qc_prefs']}</option>
    				<option value='-1'>--------------</option>
    				<option value='0|act=Search&CODE=00'>{$ibforums->lang['qc_search']}</option>
    				<option value=''>{$ibforums->lang['qc_home']}</option>
    				<option value='0|act=Help&CODE=00'>{$ibforums->lang['qc_help']}</option>
					$menu_extra    				
    		</select>
    	</form>
    	</td>
		<td align='right'>{$data}</td>
	</tr>
</table>
<br>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// forum_subs_end
//===========================================================================
function forum_subs_end() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
 <td align='right' class='titlemedium' valign='middle' colspan='5'><a href='{$ibforums->base_url}&act=UserCP&CODE=51&f=all'>{$ibforums->lang['ft_unsub_all']}</a></td>
</tr>
</table>
</td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// forum_subs_header
//===========================================================================
function forum_subs_header() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                   <td align='left' colspan='2' class='pagetitle'>{$ibforums->lang['forum_subs_header']}</td>
                 </tr>
                 <tr>
                 <td valign='top' colspan='2' >
                 <table cellpadding='4' cellspacing='1' align='center' width='100%' bgcolor='<{tbl_border}>'>
                 <tr>
                   <td class='titlemedium' align='left' width='5%'>&nbsp;</td>
                   <td class='titlemedium' align='left' width='50%'>{$ibforums->lang['ft_forum']}</td>
                   <td class='titlemedium' align='center' width='5%'>{$ibforums->lang['ft_topics']}</td>
                   <td class='titlemedium' align='center' width='5%'>{$ibforums->lang['ft_posts']}</td>
                   <td class='titlemedium' align='center' width='35%'>{$ibforums->lang['ft_last_post']}</td>
                 </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// forum_subs_none
//===========================================================================
function forum_subs_none() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                 <tr>
                   <td class='row1' align='center' colspan='5'>{$ibforums->lang['forum_subs_none']}</td>
                 </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// forum_subs_row
//===========================================================================
function forum_subs_row($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                 <tr>
                   <td class='row1' align='center' width='5%'>{$data['folder_icon']}</td>
                   <td class='row1' align='left'>
                       <span class='linkthru'><b><a href='{$ibforums->base_url}&act=SF&f={$data['id']}'>{$data['name']}</a></b>
                       <br><span class='desc'>{$data['description']}</span>
                       <br><br><b>[ <a href='{$ibforums->base_url}&act=UserCP&CODE=51&f={$data['id']}'>{$ibforums->lang['ft_unsub']}</a> ]</b>
                   </td>
                   <td class='row1' align='center'>{$data['topics']}</td>
                   <td class='row1' align='center'>{$data['posts']}</td>
                   <td class='row1' align='left'>{$data['last_post']}<br>{$ibforums->lang['in']} {$data['last_topic']}<br>{$ibforums->lang['by']} {$data['last_poster']}</td>
                 </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// iu_add_new
//===========================================================================
function iu_add_new() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td colspan="4" class="formsubtitle">{$ibforums->lang['mi5_addem']}</td>
	</tr>
	<tr>
		<td colspan="2" class="row1"><input type="text" name="newbox_1" value="{$ibforums->input['newbox_1']}" /></td>
		<td colspan="2" class="row2"><input type="button" value="{$ibforums->lang['mi5_finduser']}" name="findusers" onclick="find_users('newbox_1')"  /></td>
	</tr>
	<tr>
		<td colspan="2" class="row1"><input type="text" name="newbox_2" value="{$ibforums->input['newbox_2']}" /></td>
		<td colspan="2" class="row2"><input type="button" value="{$ibforums->lang['mi5_finduser']}" onclick="find_users('newbox_2')" /></td>
	</tr>
	<tr>
		<td colspan="2" class="row1"><input type="text" name="newbox_3" value="{$ibforums->input['newbox_3']}" /></td>
		<td colspan="2" class="row2"><input type="button" value="{$ibforums->lang['mi5_finduser']}" onclick="find_users('newbox_3')" /></td>
	</tr>
	<tr>
		<td class="formbuttonrow" colspan="4"><input type="submit" value="{$ibforums->lang['mi5_edit']}" /></td>
	</tr>
</table>
</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// iu_populated_row
//===========================================================================
function iu_populated_row($member="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td><b><a href="{$ibforums->base_url}showuser={$member['id']}">{$member['name']}</a></b></td>
		<td>{$member['prefix']}{$member['g_title']}{$member['suffix']}</td>
		<td>{$member['posts']}</td>
		<td><a href="{$ibforums->base_url}act=UserCP&amp;CODE=ignoreremove&amp;id={$member['id']}">{$ibforums->lang['mi5_remove']}</a></td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// iu_start
//===========================================================================
function iu_start() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
	function find_users(field){
		url = "index.{$ibforums->vars['php_ext']}?act=legends&CODE=finduser_one&s={$ibforums->session_id}&entry=textarea&name="+field+"&sep=none";
		window.open(url,"FindUsers","width=400,height=250,resizable=yes,scrollbars=yes"); 
	}
-->
</script>
<form action="{$ibforums->base_url}" method="post" name="REPLIER">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="ignoreadd" />
<div class="formsubtitle">{$ibforums->lang['mi5_title']}</div>
<p>{$ibforums->lang['mi5_text']}</p>
<div class="borderwrapm">
	<table cellspacing="1">
		<tr>
			<th width="30%">{$ibforums->lang['mi5_name']}</th>
			<th width="30%">{$ibforums->lang['mi5_group']}</th>
			<th width="20%">{$ibforums->lang['mi5_posts']}</th>
			<th width="20%">&nbsp;</th>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// member_title
//===========================================================================
function member_title($title="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                <tr>
                <td class='row1' width='40%'>{$ibforums->lang['member_title']}</td>
                <td class='row1'><input type='text' size='40' maxlength='120' name='member_title' value='$title' class='forminput'></td>
                </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// Menu_bar
//===========================================================================
function Menu_bar($base_url="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br>
<table width='<{tbl_width}>' bgcolor='<{tbl_border}>' align='center' border="0" cellspacing="1" cellpadding="0">
  <tr> 
    <td class='maintitle' > 
      &nbsp;
    </td>
  </tr>
  <tr> 
    <td> 
      <table class='mainbg' width="100%" border="0" cellspacing="1" cellpadding="4">
        <tr> 
          <td nowrap class='titlemedium'>&nbsp;</td>
          <td width="100%" nowrap class='titlemedium'>&nbsp;</td>
        </tr>
        <tr> 
          <td class='row1' valign="top">
           <table cellpadding='0' cellspacing='0' width='100%' align='left' border='0'>
            <tr>
              <td style='line-height:150%' nowrap>
			  <!-- Messenger -->
			  <b>{$ibforums->lang['m_messenger']}</b><br>
              <img src="{$ibforums->vars['img_url']}/dark_line.gif" alt="" width="155" height="7"><br>
              &#149; <a href='{$base_url}&act=Msg&CODE=01'><b>{$ibforums->lang['mess_inbox']}</b></a><br>
              &#149; <a href='{$base_url}&act=Msg&CODE=04'><b>{$ibforums->lang['mess_new']}</b></a><br>
              &#149; <a href='{$base_url}&act=Msg&CODE=02'>{$ibforums->lang['mess_contact']}</a><br>
              &#149; <a href='{$base_url}&act=Msg&CODE=07'>{$ibforums->lang['mess_folders']}</a><br>
              &#149; <a href='{$base_url}&act=Msg&CODE=14'>{$ibforums->lang['mess_archive']}</a><br>
              &#149; <a href='{$base_url}&act=Msg&CODE=20'>{$ibforums->lang['mess_saved']}</a><br>
              &#149; <a href='{$base_url}&act=Msg&CODE=30'>{$ibforums->lang['mess_tracker']}</a><br>
              <br>
              <!-- End Messenger -->
              
              <!-- Topic Tracker -->
			  
              <b>{$ibforums->lang['m_tracker']}</b><br>
              <img src="{$ibforums->vars['img_url']}/dark_line.gif" alt="" width="155" height="7"><br>
              &#149; <a href='{$base_url}&act=UserCP&CODE=26'>{$ibforums->lang['m_view_subs']}</a><br>
              &#149; <a href='{$base_url}&act=UserCP&CODE=50'>{$ibforums->lang['m_view_forum']}</a><br>
			  <br>
			  
			  <!-- Profile -->
              <b>{$ibforums->lang['m_personal']}</b><br>
              <img src="{$ibforums->vars['img_url']}/dark_line.gif" alt="" width="155" height="7"><br>
              &#149; <a href='{$base_url}&act=UserCP&CODE=01'>{$ibforums->lang['m_contact_info']}</a><br>
              <!-- &#149; <a href='#'>{$ibforums->lang['m_bio_info']}</a><br> -->
              &#149; <a href='{$base_url}&act=UserCP&CODE=22'>{$ibforums->lang['m_sig_info']}</a><br>
              &#149; <a href='{$base_url}&act=UserCP&CODE=24'>{$ibforums->lang['m_avatar_info']}</a><br>
              <!-- &#149; <a href='#'>{$ibforums->lang['m_edit_links']}</a><br> -->
			  <!-- Options -->
              <br>
              <b>{$ibforums->lang['m_options']}</b><br>
              <img src="{$ibforums->vars['img_url']}/dark_line.gif" alt="" width="155" height="7"><br>
              &#149; <a href='{$base_url}&act=UserCP&CODE=02'>{$ibforums->lang['m_email_opt']}</a><br>
              &#149; <a href='{$base_url}&act=UserCP&CODE=04'>{$ibforums->lang['m_board_opt']}</a><br>
              &#149; <a href='{$base_url}&act=UserCP&CODE=06'>{$ibforums->lang['m_skin_lang']}</a><br>
              &#149; <a href='{$base_url}&act=UserCP&CODE=08'>{$ibforums->lang['m_email_change']}</a><br>
              &#149; <a href='{$base_url}&act=UserCP&CODE=28'>{$ibforums->lang['m_passy_opt']}</a><br>
              
			  
             </td>
            </tr>
           </table>
          </td>
          <td valign='top' class='row1'>
          <table cellpadding='4' cellspacing='3' width='100%' align='left' border='0'>
            <tr>
             
			     <!-- Start main CP area -->
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// menu_bar_msg_folder_link
//===========================================================================
function menu_bar_msg_folder_link($id="",$real="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
&nbsp;&nbsp; <{MSG_FOLDER}>&nbsp;<a href="{$ibforums->base_url}act=Msg&amp;CODE=01&amp;VID=$id">$real</a><br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// menu_bar_new_link
//===========================================================================
function menu_bar_new_link($url="",$name="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<{ITEM_START}> <a href="$url">$name</a><br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mod_find_user
//===========================================================================
function mod_find_user($msg="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form name="ibform" action="{$ibforums->base_url}act=usercp&amp;CODE=domemtool" method="post">
EOF;
//startif
if ( $msg )
{
$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['ipm_title']}</div>
<p>
	$msg
</p>
<br />
EOF;
}//endif
$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['cp_edit_user']}</div>
	<table cellspacing="1">
		<tr>
			<td width="40%" class="row1">{$ibforums->lang['cp_find_user']}</td>
			<td class="row1"><input type="text" size="40" name="name" value="{$ibforums->input['name']}" /></td>
		</tr>
	<tr>
		<td class="formbuttonrow" colspan="2"><input type="submit" value="{$ibforums->lang['cp_find_submit']}" /></td>
	</tr>
	</table>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mod_ip_member_results
//===========================================================================
function mod_ip_member_results($pages="",$content="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div>
	<div class="borderwrapm">
		<table cellspacing="0">
			<tr>
				<th width="20%">{$ibforums->lang['ipm_name']}</th>
				<th width="20%">{$ibforums->lang['ipm_ip']}</th>
				<th width="10%">{$ibforums->lang['ipm_posts']}</th>
				<th width="15%">{$ibforums->lang['ipm_reg']}</th>
				<th width="15%">{$ibforums->lang['ipm_group']}</th>
				<th width="20%">{$ibforums->lang['ipm_options']}</th>
			</tr>
			{$content}
		</table>
	</div>
	<div>$pages</div>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mod_ip_member_row
//===========================================================================
function mod_ip_member_row($row="",$auth_key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
	<td class="row1"><a href="{$ibforums->base_url}showuser={$row['id']}">{$row['name']}</a></td>
	<td class="row1">{$row['ip_address']}</td>
	<td class="row1">{$row['posts']}</td>
	<td class="row1">{$row['joined']}</td>
	<td class="row1">{$row['groupname']}</td>
	<td class="row1" align="center"><a href="{$ibforums->base_url}act=mod&amp;CODE=editmember&amp;mid={$row['id']}&amp;auth_key=$auth_key">{$ibforums->lang['ipm_edit']}</a></td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mod_ip_post_results
//===========================================================================
function mod_ip_post_results($uid="",$count="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
{$ibforums->lang['ipp_found']} $count
<br />
<br />
<a target="_blank" href="{$ibforums->base_url}act=Search&amp;CODE=show&amp;searchid=$uid&amp;search_in=posts&amp;result_type=posts">{$ibforums->lang['ipp_click']}</a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mod_ip_start_form
//===========================================================================
function mod_ip_start_form($ip="",$msg="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form name="ibform" action="{$ibforums->base_url}" method="post">
<input type="hidden" name="s" value="{$ibforums->session_id}" />
<input type="hidden" name="act" value="usercp" />
<input type="hidden" name="CODE" value="doiptool" />
EOF;
//startif
if ( $msg )
{
$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['ipm_title']}</div>
<p>
	$msg
</p>
<br />
EOF;
}//endif
$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['menu_ipsearch']}</div>
	<table cellspacing="0">
		<tr>
			<td width="40%" class="row1">{$ibforums->lang['ip_enter']}</td>
			<td class="row1">
				<input type="text" size="20" maxlength="24" name="ip" value="{$ip}" />
				<select name="iptool">
					<option value="resolve">{$ibforums->lang['ip_resolve']}</option>
					<option value="posts">{$ibforums->lang['ip_posts']}</option>
					<option value="members">{$ibforums->lang['ip_members']}</option>
				</select>
			</td>
		</tr>
	<tr>
		<td class="formsubtitle" style="text-align: center;" colspan="2"><input type="submit" value="{$ibforums->lang['ip_submit']}" /></td>
	</tr>
	</table>
</form>
	<br />
<div class="tablepad">
	{$ibforums->lang['ip_desc_text']}
	<br /><br />{$ibforums->lang['ip_warn_text']}
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// pass_change
//===========================================================================
function pass_change() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
				<form action="{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}" method="post" name='form1'>
                 <input type='hidden' name='act' value='UserCP'>
                 <input type='hidden' name='CODE' value='29'>
                 <input type='hidden' name='s' value='{$ibforums->session_id}'>
                   <td colspan='2' class='category'><b>{$ibforums->lang['account_pass_title']}</b></td>
                 </tr>
                 <tr>
                   <td class='row1' colspan='2'>{$ibforums->lang['pass_change_text']}</td>
                 </tr>
                 <tr>
                   <td class='row2' nowrap><b>{$ibforums->lang['account_pass_old']}</b></td>
                   <td class='row2' align='left'><input type='password' name='current_pass' value='' class='forminput'></td>
                 </tr>
                 <tr>
                   <td class='row1' nowrap><b>{$ibforums->lang['account_pass_new']}</b></td>
                   <td class='row1' align='left'><input type='password' name='new_pass_1' value='' class='forminput'></td>
                 </tr>
                 <tr>
                   <td class='row1' nowrap><b>{$ibforums->lang['account_pass_new2']}</b></td>
                   <td class='row1' align='left'><input type='password' name='new_pass_2' value='' class='forminput'></td>
                 </tr>
                 <tr>
                    <td class='row2' align='center' colspan='2'><input type="submit" name='s_pass' value="{$ibforums->lang['account_pass_submit']}" class='forminput'></td>
                 </tr>
                 </form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// personal_avatar
//===========================================================================
function personal_avatar($data="",$formextra="",$hidden_field="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                <script langauge='javascript'>
                <!--
                
                  function checkTheBox() {
                  	
                  	var isUrl = "{$ibforums->vars['avatar_url']}";
                  	
                  	if (isUrl == 1)
                  	{
                  		document.creator.choice[1].checked = true;
                  	}
                  	else
                  	{
                  		document.creator.choice[0].checked = true;
                  	}
                  }
                  
                  function showavatar(theURL) {
                    
                    document.creator.choice[0].checked = true;
                    
                    document.images.show_avatar.src=theURL+document.creator.gallery_list.options[document.creator.gallery_list.selectedIndex].value;
                  }
                  
                  function select_url() {
                  	document.creator.choice[1].checked = true;
                  }
                  
                  function select_upload() {
                  	document.creator.choice[1].checked = true;
                  	document.creator.url_avatar.value = "";
                  }
                  
                  function select_none() {
                  	document.creator.choice[2].checked = true;
                  }
                  
                //-->
                </script>
                
                <form action='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}' method='post' onload='checkTheBox' $formextra name='creator'>
                <input type='hidden' name='act' value='UserCP'>
                <input type='hidden' name='CODE' value='25'>
                <input type='hidden' name='s' value='{$ibforums->session_id}'>
                $hidden_field
                
                <td align='left' colspan='2' class='category'><b>{$ibforums->lang['av_current']}</b></td>
                </tr>
                <tr>
                <td class='row2' width='40%' valign='middle'>{$ibforums->lang['this_avatar']}</td>
                <td class='row2' width='60%' valign='middle'>{$data[CUR_AV]}</td>
                <tr>
                <td valign='left' colspan='2' class='category'><input type='radio' name='choice' value='gallery' onclick='return true;'><b>{$ibforums->lang['avatar_pre_title']}</b></td>
                </tr>
                <tr>
                <td class='row1' width='40%' valign='top'>{$ibforums->lang['avatar_pre_txt']}</td>
                <td class='row1' valign='top'>{$data[AVATARS]} &nbsp; &nbsp; {$data[SHOW_AVS]}</td>
                </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// personal_avatar_end
//===========================================================================
function personal_avatar_end() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                <tr>
                <td valign='left' colspan='2' class='category'><input type='radio' name='choice' value='none' onclick='return true;'><b>{$ibforums->lang['av_tt_one']}</b></td>
                </tr>
                <tr>
                <td class='row1' align='center' colspan='2'>{$ibforums->lang['av_tt_two']}</td>
                </tr> 
                <tr>
                <td class='row2' align='center' colspan='2'><input type="submit" value="{$ibforums->lang['avatar_pre_submit']}" class='forminput'></td>
                </tr>         
                </form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// personal_avatar_URL
//===========================================================================
function personal_avatar_URL($Profile="",$avatar="",$allowed_ext="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                <tr>
                <td valign='left' colspan='2' class='category'><input type='radio' name='choice' value='url' checked onclick='return true;'><b>{$ibforums->lang['avatar_url_title']}</b></td>
                </tr>
                <tr>
                <td class='row1' width='40%' valign='top'>{$ibforums->lang['avatar']}<br>{$ibforums->lang['avatar_url_ext']}<br><b>$allowed_ext</b></td>
                <td class='row1'><input type='text' size='55' maxlength='80' name='url_avatar' value='$avatar' class='forminput' onfocus='select_url()'></td>
                </tr>
                <!-- IBF.UPLOAD_AVATAR -->
                <tr>
                <td class='row1' width='40%' valign='top'>{$ibforums->lang['avatar_dims']}<br>{$ibforums->lang['maximum']} {$ibforums->lang['width']} = {$ibforums->vars['av_width']} {$ibforums->lang['pixels']}<br>{$ibforums->lang['maximum']} {$ibforums->lang['height']} = {$ibforums->vars['av_height']} {$ibforums->lang['pixels']}</td>
                <td class='row1'>{$ibforums->lang['width']} &nbsp; <input type='text' size='3' maxlength='3' name='Avatar_width' value='{$Profile[AVATAR_WIDTH]}' class='forminput' onfocus='select_url()'>&nbsp; x &nbsp; {$ibforums->lang['height']} &nbsp; <input type='text' size='3' maxlength='3' name='Avatar_height' value='{$Profile[AVATAR_HEIGHT]}' onfocus='select_url()' class='forminput'></td>
                </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// personal_panel
//===========================================================================
function personal_panel($Profile="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script language="javascript">
<!--
var LocationMax  = "{$ibforums->vars['max_location_length']}";
var InterestMax  = "{$ibforums->vars['max_interest_length']}";
function CheckLength(Type) {
    LocationLength  = document.theForm.Location.value.length;
    InterestLength  = document.theForm.Interests.value.length;
    message  = "";
    if (Type == "location") {
        if (LocationMax !=0) {
            message = "{$ibforums->lang['js_location']}: {$ibforums->lang['js_max']} " + LocationMax + " {$ibforums->lang['js_characters']}.";
        } else {
            message = "";
        }
        alert(message + "  {$ibforums->lang['js_used']} " + LocationLength + " {$ibforums->lang['js_so_far']}.");
    }
    if (Type == "interest") {
        if (InterestMax !=0) {
            message = "{$ibforums->lang['js_interests']}: {$ibforums->lang['js_max']} " + InterestMax + " {$ibforums->lang['js_characters']}.";
        } else {
            message = "";
        }
        alert(message + "  {$ibforums->lang['js_used']} " + InterestLength + " {$ibforums->lang['js_so_far']}.");
    }
    
}
function ValidateProfile() {
    LocationLength  = document.theForm.Location.value.length;
    InterestLength  = document.theForm.Interests.value.length;
    errors = "";
    if (LocationMax !=0) {
        if (LocationLength > LocationMax) {
            errors = "{$ibforums->lang['js_location']}:  {$ibforums->lang['js_max']} " + LocationMax + " {$ibforums->lang['js_characters']}.  {$ibforums->lang['js_used']}: " + LocationLength;
        }
    }
    if (InterestMax !=0) {
        if (InterestLength > InterestMax) {
            errors = errors + "  {$ibforums->lang['js_interests']}:  {$ibforums->lang['js_max']} " + InterestMax + " {$ibforums->lang['js_characters']}.  {$ibforums->lang['js_used']}: " + InterestLength;
        }
    } 
    
    if (errors != "") {
        alert(errors);
        return false;
    } else {
        return true;
    }
}
//-->
</script>
<form action="{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}" method="post" name='theForm' onSubmit='return ValidateProfile()'>
     <input type='hidden' name='act' value='UserCP'>
     <input type='hidden' name='CODE' value='21'>
     <input type='hidden' name='s' value='{$ibforums->session_id}'>
				<!--{REQUIRED.FIELDS}-->
                <td valign='left' colspan='2' class='category'>{$ibforums->lang['profile_title']}</td>
                </tr>
                <!--{MEMBERTITLE}-->
                <!--{BIRTHDAY}-->
                <!-- for v1.1<tr>
                <td class='row1' width='40%'>{$ibforums->lang['photo']}</td>
                <td class='row1'><input type='text' size='40' maxlength='120' name='Photo' value='{$Profile['photo']}' class='forminput'></td>
                </tr>  -->
                <tr>
                <td class='row2' width='40%'>{$ibforums->lang['website']}</td>
                <td class='row2'><input type='text' size='40' maxlength='1200' name='WebSite' value='{$Profile['website']}' class='forminput'></td>
                </tr>  
                <tr>
                <td class='row1' width='40%'>{$ibforums->lang['icq']}</td>
                <td class='row1'><input type='text' size='40' maxlength='20' name='ICQNumber' value='{$Profile['icq_number']}' class='forminput'></td>
                </tr>
                <tr>
                <td class='row2' width='40%'>{$ibforums->lang['aol']}</td>
                <td class='row2'><input type='text' size='40' maxlength='30' name='AOLName' value='{$Profile['aim_name']}' class='forminput'></td>
                </tr>
                <tr>
                <td class='row1' width='40%'>{$ibforums->lang['yahoo']}</td>
                <td class='row1'><input type='text' size='40' maxlength='30' name='YahooName' value='{$Profile['yahoo']}' class='forminput'></td>
                </tr>
                <tr>
                <td class='row2' width='40%'>{$ibforums->lang['msn']}</td>
                <td class='row2'><input type='text' size='40' maxlength='30' name='MSNName' value='{$Profile['msnname']}' class='forminput'></td>
                </tr>
                <tr>
                <td class='row1' width='40%'>{$ibforums->lang['location']}<br>(<a href='javascript:CheckLength("location");'>{$ibforums->lang['check_length']}</a>)</td>
                <td class='row1'><input type='text' size='40' name='Location' value='{$Profile['location']}' class='forminput'></td>
                </tr>
                <tr>
                <td class='row2' width='40%' valign='top'>{$ibforums->lang['interests']}<br>(<a href='javascript:CheckLength("interest");'>{$ibforums->lang['check_length']}</a>)</td>
                <td class='row2'><textarea cols='60' rows='10' wrap='soft' name='Interests' class='forminput'>{$Profile['interests']}</textarea></td>
                </tr>
                <!--{OPTIONAL.FIELDS}-->
                <tr>
                <td class='row2' align='center' colspan='2'>
                <input type="submit" value="{$ibforums->lang['submit_profile']}" class='forminput'>
                </td></tr>
                </form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// photo_page
//===========================================================================
function photo_page($cur_photo="",$cur_type="",$url_photo="",$show_size="",$key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
var url_input = "$url_photo";
var remove_pressed = 0;
	
	function clear_it(){
		if ( document.bob.url_photo.value != "" ){
			url_input = document.bob.url_photo.value;
		}
      	document.bob.url_photo.value = "";
	}
   
	function restore_it(){
		if (url_input != ""){
		document.bob.url_photo.value = url_input;
		}
	}
   
	function checkform(){
		if ( remove_pressed != 1 ){
			return true;
		}
   		else{
   			fcheck = confirm("{$ibforums->lang['pp_confirm']}");
   			if ( fcheck == true ){
   				return true;
   			}
   			else{
   				return false;
   			}
   		}
	}
-->
</script>
<form action="{$ibforums->base_url}auth_key=$key" enctype="multipart/form-data" method="post" name="bob" onsubmit="return checkform();">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="dophoto" />
<div class="formsubtitle">{$ibforums->lang['pph_title']}</div>
<p>{$ibforums->lang['pph_desc']}<br />{$ibforums->lang['pph_max']}</p>
<div class="formsubtitle">{$ibforums->lang['pph_current']}</div>
<div align="center">
 <p>$cur_photo<br />$cur_type ($show_size)</p>
</div>
<div class="formsubtitle">{$ibforums->lang['pph_change']}</div>
<table cellspacing="0">
	<tr>
		<td class="pformleft">{$ibforums->lang['pph_url']}</td>
		<td class="pformright"><input type="text" onfocus="restore_it()" name="url_photo" value="$url_photo" size="40" />&nbsp;&nbsp;(<a href="javascript:restore_it()">{$ibforums->lang['pp_restore']}</a>)</td>
	</tr>
	<!--IPB.UPLOAD-->
	<!--IPB.SIZE-->
</table>
<div align="center" class="formsubtitle">
	<input type="submit" name="submit" value="{$ibforums->lang['pph_submit']}" />
	&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" onclick="remove_pressed=1;" name="remove" value="{$ibforums->lang['pph_remove']}" />
</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// photo_page_autosize
//===========================================================================
function photo_page_autosize() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td class="pformleft">&nbsp;</td>
		<td class="pformright"><b>{$ibforums->lang['pph_autosize']}</b><br />({$ibforums->lang['pph_as_desc']})</td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// photo_page_mansize
//===========================================================================
function photo_page_mansize() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td class="pformleft">&nbsp;</td>
		<td class="pformright"><b>{$ibforums->lang['width']}</b>&nbsp;<input type="text" size="3" name="man_width" />&nbsp;&nbsp;<b>{$ibforums->lang['height']}</b>&nbsp;<input type="text" size="3" name="man_height" /></td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// photo_page_upload
//===========================================================================
function photo_page_upload($max_filesize="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td class="pformleft">{$ibforums->lang['pph_upload']}</td>
		<td class="pformright"><input type="hidden" name="MAX_FILE_SIZE" value="$max_filesize" /><input type="file" name="upload_photo" value="" size="40" onclick="clear_it()" /></td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// required_end
//===========================================================================
function required_end() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// required_title
//===========================================================================
function required_title() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
            <td valign='left' colspan='2' class='category'>{$ibforums->lang['cf_required']}</td>
            </tr>
            <tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// settings_end
//===========================================================================
function settings_end($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                 <tr>
                   <td colspan='2' class='category'><b>{$ibforums->lang['settings_display']}</b></td>
                 </tr>
                 <tr>
                   <td class='row1' nowrap><b>{$ibforums->lang['settings_viewsig']}</b></td>
                   <td class='row1' width='70%' align='left'>{$data[SIG]}</td>
                 </tr>
                 <tr>
                   <td class='row1' nowrap><b>{$ibforums->lang['settings_viewimg']}</b></td>
                   <td class='row1' width='70%' align='left'>{$data[IMG]}</td>
                 </tr>
                 <tr>
                   <td class='row1' nowrap><b>{$ibforums->lang['settings_viewava']}</b></td>
                   <td class='row1' width='70%' align='left'>{$data[AVA]}</td>
                 </tr>
                 <tr>
                   <td class='row1' nowrap><b>{$ibforums->lang['settings_dopopup']}</b></td>
                   <td class='row1' width='70%' align='left'>{$data[POP]}</td>
                 </tr>
                 <tr>
                   <td class='row1' nowrap>{$ibforums->lang['hide_session_txt']}</td>
                   <td class='row1' width='70%' align='left'>{$data[SESS]}</td>
                 </tr>
                 <tr>
                   <td class='row1' nowrap><b>{$ibforums->lang['pp_number_posts']}</b></td>
                   <td class='row1' width='70%' align='left'><select name='postpage' class='forminput'>{$data['PPS']}</select></td>
                 </tr>
                 <tr>
                   <td class='row1' nowrap><b>{$ibforums->lang['pp_number_topics']}</b></td>
                   <td class='row1' width='70%' align='left'><select name='topicpage' class='forminput'>{$data['TPS']}</select></td>
                 </tr>
                 <tr>
                   <td class='row2' colspan='2' align='center'><input type='submit' name='submit' value='{$ibforums->lang['settings_submit']}' class='forminput'></form></td>
                 </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// settings_header
//===========================================================================
function settings_header($Profile="",$time_select="",$time="",$dst_check="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
     <form action="{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}" method="post">
     <input type='hidden' name='act' value='UserCP'>
     <input type='hidden' name='CODE' value='05'>
     <input type='hidden' name='s' value='{$ibforums->session_id}'>
                  
                   <td colspan='2' class='category'><b>{$ibforums->lang['settings_time']}</b></td>
                 </tr>
                 <tr>
                   <td class='row1' colspan='2'><b>{$ibforums->lang['settings_time_txt']}</b><br><span class='highlight'>$time</span></td>
                 </tr>
                 <tr>
                   <td class='row1' colspan='2' align='left'>$time_select</td>
                 </tr>
                 <tr>
                   <td class='row1' nowrap>{$ibforums->lang['dst_box']}</td>
                   <td class='row1' width='70%' align='left'><input type='checkbox' class='forminput' name='DST' value='1' $dst_check></td>
                 </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// settings_skin
//===========================================================================
function settings_skin($skin="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                 </tr>
                   <td colspan='2' class='category'><b>{$ibforums->lang['settings_skin']}</b></td>
                 </tr>
                 <tr>
                   <td class='row1' nowrap><b>{$ibforums->lang['settings_skin_txt']}</b></td>
                   <td class='row1' align='left'>$skin &nbsp;&nbsp; <input type='button' value='{$ibforums->lang['cp_skin_preview']}' class='forminput' onClick='do_preview()'></td>
                 </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// signature
//===========================================================================
function signature($sig="",$t_sig="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script language="javascript1.2">
<!--
var MessageMax  = "{$ibforums->lang['the_max_length']}";
var Override    = "{$ibforums->lang['override']}";
function CheckLength() {
    MessageLength  = document.REPLIER.Post.value.length;
    message  = "";
        if (MessageMax > 0) {
            message = "{$ibforums->lang['js_max_length']} " + MessageMax + " {$ibforums->lang['js_characters']}.";
        } else {
            message = "";
        }
        alert(message + "\\n{$ibforums->lang['js_used']} " + MessageLength + " {$ibforums->lang['js_characters']}.");
}
function ValidateForm() {
    MessageLength  = document.REPLIER.Post.value.length;
    errors = "";
    if (MessageMax !=0) {
        if (MessageLength > MessageMax) {
            errors = "{$ibforums->lang['js_max_length']} " + MessageMax + " {$ibforums->lang['js_characters']}.\\n{$ibforums->lang['js_current']}: " + MessageLength;
        }
    }
    if (errors != "" && Override == "") {
        alert(errors);
        return false;
    } else {
        document.REPLIER.submit.disabled = true;
        return true;
    }
}

// IBC Code stuff
	var text_enter_url      = "{$ibforums->lang['jscode_text_enter_url']}";
	var text_enter_url_name = "{$ibforums->lang['jscode_text_enter_url_name']}";
	var text_enter_image    = "{$ibforums->lang['jscode_text_enter_image']}";
	var text_enter_email    = "{$ibforums->lang['jscode_text_enter_email']}";
	var text_enter_flash    = "{$ibforums->lang['jscode_text_enter_flash']}";
	var text_code           = "{$ibforums->lang['jscode_text_code']}";
	var text_quote          = "{$ibforums->lang['jscode_text_quote']}";
	var error_no_url        = "{$ibforums->lang['jscode_error_no_url']}";
	var error_no_title      = "{$ibforums->lang['jscode_error_no_title']}";
	var error_no_email      = "{$ibforums->lang['jscode_error_no_email']}";
	var error_no_width      = "{$ibforums->lang['jscode_error_no_width']}";
	var error_no_height     = "{$ibforums->lang['jscode_error_no_height']}";
	var prompt_start        = "{$ibforums->lang['js_text_to_format']}";
	
	var help_bold           = "{$ibforums->lang['hb_bold']}";
	var help_italic         = "{$ibforums->lang['hb_italic']}";
	var help_under          = "{$ibforums->lang['hb_under']}";
	var help_font           = "{$ibforums->lang['hb_font']}";
	var help_size           = "{$ibforums->lang['hb_size']}";
	var help_color          = "{$ibforums->lang['hb_color']}";
	var help_close          = "{$ibforums->lang['hb_close']}";
	var help_url            = "{$ibforums->lang['hb_url']}";
	var help_img            = "{$ibforums->lang['hb_img']}";
	var help_email          = "{$ibforums->lang['hb_email']}";
	var help_quote          = "{$ibforums->lang['hb_quote']}";
	var help_list           = "{$ibforums->lang['hb_list']}";
	var help_code           = "{$ibforums->lang['hb_code']}";
	var help_click_close    = "{$ibforums->lang['hb_click_close']}";
	var list_prompt         = "{$ibforums->lang['js_tag_list']}";
//-->
</script>

		<form action="{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}" method="POST" name='REPLIER'>
		<input type='hidden' name='act' value='UserCP'>
		<input type='hidden' name='CODE' value='23'>
		<input type='hidden' name='s' value='{$ibforums->session_id}'>
		<td class='title' colspan='2'><b>{$ibforums->lang['cp_current_sig']}</b></td>
		</tr>
		<tr>
		<td class='row1' align='center' colspan='2'>
			<table cellpadding='2' cellspacing='0' width='75%' align='center'>
				<tr>
					<td class='signature'>$sig</td>
				</tr>
			</table>
		</td>
		</tr>
		<tr>
		<td class='title' colspan='2'><b>{$ibforums->lang['cp_edit_sig']}</b></td>
		</tr>
        <tr> 
          <td class='row1' width='20%' nowrap>
          	<input type='radio' name='bbmode' value='ezmode' onClick='setmode(this.value)'>&nbsp;<b>{$ibforums->lang['bbcode_guided']}</b><br>
          	<input type='radio' name='bbmode' value='normal' onClick='setmode(this.value)' checked>&nbsp;<b>{$ibforums->lang['bbcode_normal']}</b>
          </td>
          <script language='Javascript' src='html/ibfcode.js'></script>
          <td class='row1' width="80%" valign="top">
			<table cellpadding='2' cellspacing='2' width='100%' align='center'>
                		<tr>
                			<td nowrap width='10%'>
							  <input type='button' accesskey='b' value=' B '       onClick='simpletag("B")' class='codebuttons' name='B' style="font-weight:bold" onMouseOver="hstat('bold')">
							  <input type='button' accesskey='i' value=' I '       onClick='simpletag("I")' class='codebuttons' name='I' style="font-style:italic" onMouseOver="hstat('italic')">
							  <input type='button' accesskey='u' value=' U '       onClick='simpletag("U")' class='codebuttons' name='U' style="text-decoration:underline" onMouseOver="hstat('under')">
							  
							  <select name='ffont' class='codebuttons' onchange="alterfont(this.options[this.selectedIndex].value, 'FONT')"  onMouseOver="hstat('font')">
							  <option value='0'>{$ibforums->lang['ct_font']}</option>
							  <option value='Arial' style='font-family:Arial'>{$ibforums->lang['ct_arial']}</option>
							  <option value='Times' style='font-family:Times'>{$ibforums->lang['ct_times']}</option>
							  <option value='Courier' style='font-family:Courier'>{$ibforums->lang['ct_courier']}</option>
							  <option value='Impact' style='font-family:Impact'>{$ibforums->lang['ct_impact']}</option>
							  <option value='Geneva' style='font-family:Geneva'>{$ibforums->lang['ct_geneva']}</option>
							  <option value='Optima' style='font-family:Optima'>Optima</option>
							  </select><select name='fsize' class='codebuttons' onchange="alterfont(this.options[this.selectedIndex].value, 'SIZE')" onMouseOver="hstat('size')">
							  <option value='0'>{$ibforums->lang['ct_size']}</option>
							  <option value='1'>{$ibforums->lang['ct_sml']}</option>
							  <option value='7'>{$ibforums->lang['ct_lrg']}</option>
							  <option value='14'>{$ibforums->lang['ct_lest']}</option>
							  </select><select name='fcolor' class='codebuttons' onchange="alterfont(this.options[this.selectedIndex].value, 'COLOR')" onMouseOver="hstat('color')">
							  <option value='0'>{$ibforums->lang['ct_color']}</option>
							  <option value='blue' style='color:blue'>{$ibforums->lang['ct_blue']}</option>
							  <option value='red' style='color:red'>{$ibforums->lang['ct_red']}</option>
							  <option value='purple' style='color:purple'>{$ibforums->lang['ct_purple']}</option>
							  <option value='orange' style='color:orange'>{$ibforums->lang['ct_orange']}</option>
							  <option value='yellow' style='color:yellow'>{$ibforums->lang['ct_yellow']}</option>
							  <option value='gray' style='color:gray'>{$ibforums->lang['ct_grey']}</option>
							  <option value='green' style='color:green'>{$ibforums->lang['ct_green']}</option>
							  </select>
							  &nbsp; <a href='javascript:closeall();' onMouseOver="hstat('close')">{$ibforums->lang['js_close_all_tags']}</a>
							</td>
						 </tr>
						 <tr>
						    <td align='left'>
							  <input type='button' accesskey='h' value=' http:// ' onClick='tag_url()'            class='codebuttons' name='url' onMouseOver="hstat('url')">
							  <input type='button' accesskey='g' value=' IMG '     onClick='tag_image()'          class='codebuttons' name='img' onMouseOver="hstat('img')">
							  <input type='button' accesskey='e' value='  @  '     onClick='tag_email()'          class='codebuttons' name='email' onMouseOver="hstat('email')">
							  <input type='button' accesskey='q' value=' QUOTE '   onClick='simpletag("QUOTE")'   class='codebuttons' name='QUOTE' onMouseOver="hstat('quote')">
							  <input type='button' accesskey='p' value=' CODE '    onClick='simpletag("CODE")'    class='codebuttons' name='CODE' onMouseOver="hstat('code')">
							  <input type='button' accesskey='l' value=' LIST '     onClick='tag_list()'          class='codebuttons' name="LIST" onMouseOver="hstat('list')">
							  <!--<input type='button' accesskey='l' value=' SQL '     onClick='simpletag("SQL")'     class='codebuttons' name='SQL'>
							  <input type='button' accesskey='t' value=' HTML '    onClick='simpletag("HTML")'    class='codebuttons' name='HTML'>-->
							</td>
						</tr>
						<tr>
						<!-- Help Box -->
						 <td align='left'>
						  <input type='text' name='helpbox' size='50' maxlength='120' style='width:450px;font-size:10px;font-family:verdana,arial;border:0px;font-weight:bold;' readonly class='row1' value="{$ibforums->lang['hb_start']}">
						  <br>
          				  <b>{$ibforums->lang['hb_open_tags']}:</b>&nbsp;<input type='text' name='tagcount' size='3' maxlength='3' style='font-size:10px;font-family:verdana,arial;border:0px;font-weight:bold;' readonly class='row1' value="0">
						 </td>
						</tr>
					</table>
                </td>
                </tr>
                <tr>
                <td class='row1' align='center' colspan='2'><textarea cols='60' rows='12' wrap='soft' name='Post' tabindex='3' class='textinput'>$t_sig</textarea><br>(<a href='javascript:CheckLength()'>{$ibforums->lang['check_length']}</a>)</td>
                </tr>
                <tr>
                <td class='row1' align='center' colspan='2'><input type='submit' value='{$ibforums->lang['cp_submit_sig']}'></td>
                </tr>
                </form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// skin_lang_end
//===========================================================================
function skin_lang_end() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                 <tr>
                   <td class='row2' colspan='2' align='center'><input type='submit' name='submit' value='{$ibforums->lang['settings_submit']}' class='forminput'></form></td>
                 </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// skin_lang_header
//===========================================================================
function skin_lang_header($lang_select="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
	<script language='Javascript'>
      <!--
		function do_preview() {
			
			var f = document.prefs.u_skin;
			
			var base_url = "{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&";
			
			if (f.options[f.selectedIndex].value == -1) {
				return false;
			}
			
			window.open( base_url + 'skinid='+f.options[f.selectedIndex].value, 'Preview', 'width=800,height=600,top=0,left=0,resizable=1,scrollbars=1,location=no,directories=no,status=no,menubar=no,toolbar=no');
			
		}
	  -->
    </script>
     <form action="{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}" method="post" name='prefs'>
     <input type='hidden' name='act' value='UserCP'>
     <input type='hidden' name='CODE' value='07'>
     <input type='hidden' name='s' value='{$ibforums->session_id}'>
                   <td colspan='2' class='category'><b>{$ibforums->lang['settings_title']}</b></td>                
                 </tr>
                 <tr>
                   <td class='row1' nowrap><b>{$ibforums->lang['settings_lang_txt']}</b></td>
                   <td class='row1' align='left'>$lang_select</td>
                 </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// splash
//===========================================================================
function splash($member="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
      <td class='titlemedium' width="100%">{$ibforums->lang['stats_header']}</td>
        </tr>
        <tr> 
          <td class='row1' valign="top" width="100%">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td width="40%">{$ibforums->lang['email_address']}</td>
                <td width="60%">{$member[MEMBER_EMAIL]}</td>
              </tr>
              <tr> 
                <td width="40%">{$ibforums->lang['number_posts']}</td>
                <td width="60%">{$member[MEMBER_POSTS]}</td>
              </tr>
              <tr> 
                <td width="40%">{$ibforums->lang['registered']}</td>
                <td width="60%">{$member[DATE_REGISTERED]}</td>
              </tr>
              <tr> 
                <td width="40%">{$ibforums->lang['daily_average']}</td>
                <td width="60%">{$member[DAILY_AVERAGE]}</td>
              </tr>
            </table>
          </td>
        </tr>
        <!-- MSG -->
        <tr> 
          <td class='titlemedium' width="100%">{$ibforums->lang['messenger_summary']}</td>
        </tr>
        <tr> 
          <td class='row1' valign="top" width="100%">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td width="40%">{$ibforums->lang['total_messages']}</td>
                <td width="60%">{$member['total_messages']} {$member['full_percent']}</td>
              </tr>
              <tr> 
                <td width="40%">{$ibforums->lang['messages_left']}</td>
                <td width="60%">{$member['space_free']} {$member['full_messenger']}</td>
              </tr>
            </table>
          </td>
        </tr>
       <!-- END MSG -->
        <tr>
          <td class='titlemedium' width="100%">{$ibforums->lang['note_pad']}</td>
        </tr>
        <tr>
          <td class='row1' valign="top" width="100%">
                <form name='notepad' action="{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}" method="post">
				<input type='hidden' name='act' value='UserCP'>
				<input type='hidden' name='s' value='{$ibforums->session_id}'>
				<input type='hidden' name='CODE' value='20'>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
				<td align="center">
				<textarea cols='65' rows='{$member['SIZE']}' wrap='soft' name='notes' class='forminput' style='width:100%'>{$member['NOTES']}</textarea>
				</td>
              </tr>
            </table>
            <br>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td align="right" width="50%">{$ibforums->lang['ta_size']}&nbsp;</td>
                <td nowrap width="50%"> 
				   <select name='ta_size' class='forminput'>
				   {$member['SIZE_CHOICE']}
				   </select>
                  <input type='submit' value='{$ibforums->lang['submit_notepad']}' class='forminput'>
                </td>
              </tr>
            </table>
            </form>
          </td>
        </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// subs_end
//===========================================================================
function subs_end($text="",$days="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
 <td align='center' class='titlemedium' valign='middle' colspan='6'><input type='submit' class='forminput' value='{$ibforums->lang['subs_delete']}'>&nbsp;&nbsp;{$ibforums->lang['with_selected']}</td>
</tr>
</form>
</table>
<br>
<table width='<{tbl_width}>' cellpadding='2' cellspacing='0' align='center'>
<tr>
 <td align='right' nowrap><i>$text</i></td>
</tr>
<tr>
 <td align='right' valign='middle' width='100%'>
 	<form action='{$ibforums->base_url}&act=UserCP&CODE=26' method='post'>
 	{$ibforums->lang['show_topics_from']} <select class='forminput' name='datecut'>$days</select>
 	<input type='submit' class='forminput' value='{$ibforums->lang['jmp_go']}'>
 	</form>
 </td>
</tr>
</table>
</td></tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// subs_forum_row
//===========================================================================
function subs_forum_row($fid="",$fname="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                 <tr>
                   <td colspan='6' class='titlemedium' align='left'><a href='{$ibforums->base_url}&act=SF&f=$fid'>$fname</a></td>
                 </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// subs_header
//===========================================================================
function subs_header() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<!-- inbox folder -->
                     <script language='JavaScript'>
                     <!--
                     function CheckAll(cb) {
                         var fmobj = document.mutliact;
                         for (var i=0;i<fmobj.elements.length;i++) {
                             var e = fmobj.elements[i];
                             if ((e.name != 'allbox') && (e.type=='checkbox') && (!e.disabled)) {
                                 e.checked = fmobj.allbox.checked;
                             }
                         }
                     }
                     function CheckCheckAll(cb) {	
                         var fmobj = document.mutliact;
                         var TotalBoxes = 0;
                         var TotalOn = 0;
                         for (var i=0;i<fmobj.elements.length;i++) {
                             var e = fmobj.elements[i];
                             if ((e.name != 'allbox') && (e.type=='checkbox')) {
                                 TotalBoxes++;
                                 if (e.checked) {
                                     TotalOn++;
                                 }
                             }
                         }
                         if (TotalBoxes==TotalOn) {fmobj.allbox.checked=true;}
                         else {fmobj.allbox.checked=false;}
                     }
                     //-->
                     </script>
                 
                   <td align='left' nowrap class='pagetitle'>{$ibforums->lang['subs_header']}</td>
                   <td>
					  <form action="{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}" name='mutliact' method="post">
					  <input type='hidden' name='act' value='UserCP'>
					  <input type='hidden' name='CODE' value='27'>
					  <input type='hidden' name='s'    value='{$ibforums->session_id}'>
                   </td>
                 </tr>
                 <tr>
                 <td valign='top' colspan='2' >
                 <table cellpadding='4' cellspacing='1' align='center' width='100%' bgcolor='<{tbl_border}>'>
                 <tr>
                   <td class='titlemedium' align='left' width='5%'>&nbsp;</td>
                   <td class='titlemedium' align='left' width='*'>{$ibforums->lang['subs_topic']}</td>
                   <td class='titlemedium' align='center' width='5%'>{$ibforums->lang['subs_replies']}</td>
                   <td class='titlemedium' align='center' width='5%'>{$ibforums->lang['subs_view']}</td>
                   <td class='titlemedium' align='left' width='20%'>{$ibforums->lang['subs_last_post']}</td>
                   <td align='center' width='5%' class='titlemedium'><input name="allbox" type="checkbox" value="Check All" onClick="CheckAll();"></td>
                 </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// subs_none
//===========================================================================
function subs_none() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                 <tr>
                   <td class='row1' align='center' colspan='6'>{$ibforums->lang['subs_none']}</td>
                 </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// subs_row
//===========================================================================
function subs_row($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
                 <tr>
                   <td class='row1' align='center' width='5%'>{$data['folder_icon']}</td>
                   <td class='row1' align='left'><span class='linkthru'><a href='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&act=ST&f={$data['forum_id']}&t={$data['tid']}'>{$data['title']}</a> ( <a href='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&act=ST&f={$data['forum_id']}&t={$data['tid']}' target='_blank'>{$ibforums->lang['new_window']}</a> )</span><br><span class='desc'>{$data['description']}{$ibforums->lang['subs_start']} {$data['start_date']}</span></td>
                   <td class='row1' align='center'>{$data['posts']}</td>
                   <td class='row1' align='center'>{$data['views']}</td>
                   <td class='row1' align='left'>{$data['last_post_date']}<br>{$ibforums->lang['subs_by']} {$data['last_poster']}</td>
                   <td class='row2' align='center'><input type='checkbox' name='id-{$data['trid']}' value='yes' class='forminput'></td>
                 </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// subs_show_choice_page
//===========================================================================
function subs_show_choice_page($forum="",$topic="",$method="",$key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form action="{$ibforums->base_url}" method="post" name="REPLIER">
<input type="hidden" name="act" value="usercp" />
<input type="hidden" name="CODE" value="end_subs" />
<input type="hidden" name="method" value="$method" />
<input type="hidden" name="auth_key" value="$key" />
<input type="hidden" name="tid" value="{$topic['tid']}" />
<input type="hidden" name="fid" value="{$forum['id']}" />
<input type="hidden" name="st" value="{$ibforums->input['st']}" />
<div class="formsubtitle">{$ibforums->lang['subs_c_title']}</div>
<div style='padding:4px'>
EOF;
//startif
if ( $topic['tid'] != "" )
{
$IPBHTML .= <<<EOF
<b>{$ibforums->lang['subs_c_topic']} {$topic['title']}</b>
EOF;
}//endif
else
{
$IPBHTML .= <<<EOF
<b>{$ibforums->lang['subs_c_forum']} {$forum['name']}</b>
EOF;
}//endelse
$IPBHTML .= <<<EOF
	<div class="desc">{$ibforums->lang['subs_exp_text']}</div>
</div>
<table cellspacing="0">
	<tr>
		<td width="5%" align="center"><input type="radio" name="emailtype" value="none" /></td>
		<td><b>{$ibforums->lang['subs_none_title']}</b><div class="desc">{$ibforums->lang['subs_none_desc']}</div></td>
	</tr>
	<tr>
		<td width="5%" align="center"><input type="radio" name="emailtype" value="delayed" checked="checked" /></td>
		<td><b>{$ibforums->lang['subs_delayed']}</b><div class="desc">{$ibforums->lang['subs_delayed_desc']}</div></td>
	</tr>
	<tr>
		<td width="5%" align="center"><input type="radio" name="emailtype" value="immediate" /></td>
		<td><b>{$ibforums->lang['subs_immediate']}</b><div class="desc">{$ibforums->lang['subs_immediate_desc']}</div></td>
	</tr>
	<tr>
		<td width="5%" align="center"><input type="radio" name="emailtype" value="daily" /></td>
		<td><b>{$ibforums->lang['subs_daily']}</b><div class="desc">{$ibforums->lang['subs_daily_desc']}</div></td>
	</tr>
	<tr>
		<td width="5%" align="center"><input type="radio" name="emailtype" value="weekly" /></td>
		<td><b>{$ibforums->lang['subs_weekly']}</b><div class="desc">{$ibforums->lang['subs_weekly_desc']}</div></td>
	</tr>
	<tr>
		<td class="formbuttonrow" colspan="2"><input type="submit" value="{$ibforums->lang['subs_submit']}" class="button" /></td>
	</tr>
</table>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// ucp_announce_form
//===========================================================================
function ucp_announce_form($announce="",$button="",$forum_html="",$type="",$msg="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form action="{$ibforums->base_url}" method="post" name="REPLIER">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="announce_save" />
<input type="hidden" name="type" value="$type" />
<input type="hidden" name="id"   value="{$announce['announce_id']}" />
<div class="formsubtitle">{$button}</div>
EOF;
//startif
if ( $msg != "" )
{
$IPBHTML .= <<<EOF
<div class="borderwrapm"><div class="tablepad">{$msg}</div></div>
EOF;
}//endif
$IPBHTML .= <<<EOF
<table cellspacing="0">
	<tr>
		<td class="pformleft"><b>{$ibforums->lang['announce_form_title']}</b></td>
		<td class="pformright" valign="top"><input type="text" size="30" name="announce_title" value="{$announce['announce_title']}" /></td>
	</tr>
	<tr>
		<td class="pformleft"><b>{$ibforums->lang['announce_form_start']}</b><div class="desc">{$ibforums->lang['announce_form_startdesc']}</div></td>
		<td class="pformright" valign="top"><input type="text" size="10" name="announce_start" value="{$announce['announce_start']}" /></td>
	</tr>
	<tr>
		<td class="pformleft"><b>{$ibforums->lang['announce_form_end']}</b><div class="desc">{$ibforums->lang['announce_form_enddesc']}</div></td>
		<td class="pformright" valign="top"><input type="text" size="10" name="announce_end" value="{$announce['announce_end']}" /></td>
	</tr>
	<tr>
		<td class="pformleft" valign="top"><b>{$ibforums->lang['announce_form_forums']}</b><div class="desc">{$ibforums->lang['announce_form_forums2']}</div></td>
		<td class="pformright" valign="top"><select class="dropdown" multiple="multiple" size="10" name="announce_forum[]">$forum_html</td>
	</tr>
	<tr>
		<td class="pformleft" valign="top"><b>{$ibforums->lang['announce_form_content']}</b></td>
		<td class="pformright" valign="top"><textarea cols="50" class="textarea" rows="15" name="announce_post" tabindex="3">{$announce['announce_post']}</textarea></td>
	</tr>
	<tr>
		<td class="pformleft" valign="top"><b>{$ibforums->lang['announce_form_options']}</b></td>
		<td class="pformright" valign="middle">
			<input type="checkbox" class="checkbox" name="announce_active" value="1" {$announce['announce_active_checked']} />&nbsp;{$ibforums->lang['announce_form_enable']}
			<br /><input type="checkbox" class="checkbox" name="announce_html_enabled" value="1" {$announce['announce_html_enabled']} />&nbsp;{$ibforums->lang['announce_use_html']}
		</td>
	</tr>
	<tr>
		<td class="formbuttonrow" colspan="2"><input type="submit" value="{$button}" class="button" /></td>
	</tr>
</table>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// ucp_announce_manage
//===========================================================================
function ucp_announce_manage($content="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
 var ipb_lang_js_del_1 = "{$ibforums->lang['announce_del1']}";
 var ipb_lang_js_del_2 = "{$ibforums->lang['announce_del2']}";
-->
</script>
<script type="text/javascript" src="jscripts/ipb_topic.js"></script>
<div class="formsubtitle">{$ibforums->lang['announce_current']}</div>
<form action="{$ibforums->base_url}" name="mutliact" method="post">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="announce_alter" />
<div class="borderwrapm">
	<table cellspacing="1">
		<tr>
			<th width="35%">{$ibforums->lang['announce_title']}</th>
			<th align="center" width="10%">{$ibforums->lang['announce_starts']}</th>
			<th align="center" width="10%">{$ibforums->lang['announce_end']}</th>
			<th width="25%">{$ibforums->lang['announce_forums']}</th>
			<th width="15%">&nbsp;</th>
		</tr>
EOF;
//startif
if ( $content )
{
$IPBHTML .= <<<EOF
$content
EOF;
}//endif
else
{
$IPBHTML .= <<<EOF
<tr>
			<td align="center" colspan="5">{$ibforums->lang['announce_none']}</td>
		</tr>
EOF;
}//endelse
$IPBHTML .= <<<EOF
	<tr>
		<td class="formbuttonrow" colspan="5"><a href="{$ibforums->base_url}act=usercp&amp;CODE=announce_add">{$ibforums->lang['announce_add']}</a></td>
	</tr>
	</table>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// ucp_announce_manage_row
//===========================================================================
function ucp_announce_manage_row($announce="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
			<td class="row1"><b><a href="{$ibforums->base_url}act=announce&amp;id={$announce['announce_id']}">{$announce['announce_title']}</a></b> {$announce['announce_inactive']}<div class="desc">{$ibforums->lang['announce_by']} {$announce['name']}</div></td>
			<td class="row1" align="center">{$announce['announce_starts_converted']}</td>
			<td class="row1" align="center">{$announce['announce_end_converted']}</td>
			<td class="row1"><div class="forumdesc">{$announce['announce_forum_show']}</div></td>
			<td class="row1" align="center">
				<a href="{$ibforums->base_url}act=usercp&amp;CODE=announce_edit&amp;id={$announce['announce_id']}">{$ibforums->lang['announce_edit']}</a>
				&middot; <a href="#" onclick="delete_post('{$ibforums->base_url}act=usercp&amp;CODE=announce_delete&amp;id={$announce['announce_id']}'); return false;">{$ibforums->lang['announce_delete']}</a>
			</td>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// ucp_message
//===========================================================================
function ucp_message($title="",$msg="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$title}</div>
	<p>$msg</p>
EOF;

//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
avatar_upload_field,birthday,CP_end,email,email_change,field_dropdown,field_entry,field_textarea,field_textinput,forum_jump,forum_subs_end,forum_subs_header,forum_subs_none,forum_subs_row,member_title,Menu_bar,pass_change,personal_avatar,personal_avatar_end,personal_avatar_URL,personal_panel,required_title,settings_end,settings_header,settings_skin,signature,skin_lang_end,skin_lang_header,splash,subs_end,subs_forum_row,subs_header,subs_none,subs_row
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>