<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 4                     */
/* CACHE FILE: Generated: Wed, 31 Aug 2005 00:22:48 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_topic {

//===========================================================================
// announcement_show
//===========================================================================
function announcement_show($announce="",$author="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="borderwrap">
	<div class="maintitle"><{CAT_IMG}>&nbsp;Announcement: {$announce['announce_title']}</div>
	<table cellspacing="1">
		<tr>
			<td valign="middle" class="row2"><span class="normalname"><a href="{$ibforums->base_url}showuser={$author['id']}">{$author['name']}</a></span></td>
			<td class="row2" valign="top">
				<!-- POSTED DATE DIV -->
				<div class="row2">
					<span class="postdetails"><b>{$announce['announce_title']}</b>&nbsp; {$announce['running_date']}</span>
				</div>
			</td>
		</tr>
		<tr>
			<td valign="top" class="post1">
				<span class="postdetails">
					{$author['avatar']}<br /><br />
					{$author['title']}<br />
					{$author['member_rank_img']}<br /><br />
					{$author['member_group']}<br />
					{$author['member_posts']}<br />
					{$author['member_number']}<br />
					{$author['member_joined']}<br /><br />
					{$author['warn_text']} {$author['warn_minus']}{$author['warn_img']}{$author['warn_add']}
				</span><br />
				<!--$ author[field_1]-->
				<img src="{$ibforums->vars['img_url']}/spacer.gif" alt="" width="160" height="1" /><br /> 
			</td>
			<td width="100%" valign="top" class="post1"><div class="postcolor">{$announce['announce_post']}</td>
		</tr>
		<tr>
			<td class="darkrow3">&nbsp;</td>
			<td class="darkrow3" nowrap="nowrap">
				<!-- EMAIL / WWW / MSGR -->
				<div class="darkrow3">
					{$author['addresscard']}{$author['message_icon']}{$author['email_icon']}
				</div>
			</td>
		</tr>
	</table>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// button_delete
//===========================================================================
function button_delete($fid="",$tid="",$pid="",$key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="javascript:delete_post('{$ibforums->base_url}act=Mod&amp;CODE=04&amp;f={$fid}&amp;t={$tid}&amp;p={$pid}&amp;st={$ibforums->input['st']}&amp;auth_key=$key')"><{P_DELETE}></a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// button_edit
//===========================================================================
function button_edit($fid="",$tid="",$pid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="{$ibforums->base_url}act=Post&amp;CODE=08&amp;f={$fid}&amp;t={$tid}&amp;p={$pid}&amp;st={$ibforums->input['st']}"><{P_EDIT}></a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// button_posting
//===========================================================================
function button_posting($url="",$macro="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="$url">$macro</a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// email_options
//===========================================================================
function email_options($tid="",$fid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
	<table cellpadding='0' cellspacing='0' width='80%' align='left' border='0'>
  	    <tr>
  	     <td>
  	     	<b><a href='{$ibforums->base_url}&act=Track&f=$fid&t=$tid'>{$ibforums->lang['tt_title']}</a></b>
  	     	<br>{$ibforums->lang['tt_desc']}
  	     	<br><br>
  	     	<b><a href='{$ibforums->base_url}&act=Track&f=$fid&type=forum'>{$ibforums->lang['ft_title']}</a></b>
  	     	<br>{$ibforums->lang['ft_desc']}
  	     	<br><br>
  	     	<b><a href='{$ibforums->base_url}&act=Print&client=choose&f=$fid&t=$tid'>{$ibforums->lang['av_title']}</a></b>
  	     	<br>{$ibforums->lang['av_desc']}
  	     </td>
  	    </tr>
  	   </table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// golastpost_link
//===========================================================================
function golastpost_link($fid="",$tid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
( <a href='{$ibforums->base_url}&act=ST&f=$fid&t=$tid&view=getnewpost'>{$ibforums->lang['go_new_post']}</a> )
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// ip_admin_hide
//===========================================================================
function ip_admin_hide() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<i>{$ibforums->lang['ip_private']}</i>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// ip_admin_show
//===========================================================================
function ip_admin_show($ip="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="{$ibforums->base_url}act=usercp&amp;CODE=iptool&amp;ip={$ip}" target="_blank">{$ip}</a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// ip_show
//===========================================================================
function ip_show($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<span class='desc'>{$ibforums->lang['ip']}: $data</span>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// member_group
//===========================================================================
function member_group($title="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
{$ibforums->lang['m_group']} $title
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// member_icon_email
//===========================================================================
function member_icon_email($id="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="{$ibforums->base_url}act=Mail&amp;CODE=00&amp;MID={$id}"><{P_EMAIL}></a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// member_icon_msg
//===========================================================================
function member_icon_msg($id="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="{$ibforums->base_url}act=Msg&amp;CODE=04&amp;MID={$id}"><{P_MSG}></a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// member_icon_profile
//===========================================================================
function member_icon_profile($id="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="{$ibforums->base_url}showuser={$id}"><{P_PROFILE}></a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// member_icon_vcard
//===========================================================================
function member_icon_vcard($id="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="javascript:PopUp('{$ibforums->base_url}act=Profile&amp;CODE=showcard&amp;MID={$id}','AddressCard','600','300','0','1','1','1')" title="{$ibforums->lang['ac_title']}"><{P_CARD}></a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// member_joined
//===========================================================================
function member_joined($date="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
{$ibforums->lang['m_joined']} $date
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// member_location
//===========================================================================
function member_location($location="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
{$ibforums->lang['m_location']} $location<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// member_number
//===========================================================================
function member_number($number="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
{$ibforums->lang['member_no']} $number
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// member_posts
//===========================================================================
function member_posts($posts="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
{$ibforums->lang['m_posts']} $posts
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// member_rank_img
//===========================================================================
function member_rank_img($filename="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<img src="$filename" alt="Group Icon" />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mm_end
//===========================================================================
function mm_end() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</select>&nbsp;
		<input type="submit" value="{$ibforums->lang['mm_submit']}" class="button" />
	</form>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mm_entry
//===========================================================================
function mm_entry($id="",$name="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<option value="$id">$name</option>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mm_start
//===========================================================================
function mm_start($tid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div style="float: left;">
	<form action="{$ibforums->base_url}act=mmod&amp;t=$tid" method="post">
	<input type="hidden" name="check" value="1" />
		<select name="mm_id" class="dropdown">
			<option value="-1">{$ibforums->lang['mm_title']}</option>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// Mod_Panel
//===========================================================================
function Mod_Panel($data="",$fid="",$tid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
    <!--<table cellpadding='0' cellspacing='0' width='100%' border='0' align='right'>
      <tr>
          <td align='right'>-->
          <form method='POST' style='display:inline' name='modform' action='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}'>
          <input type='hidden' name='s' value='{$ibforums->session_id}'>
          <input type='hidden' name='t' value='$tid'>
          <input type='hidden' name='f' value='$fid'>
          <input type='hidden' name='st' value='{$ibforums->input['st']}'>
          <input type='hidden' name='act' value='Mod'>
          <select name='CODE' class='forminput' style="font-weight:bold;color:red">
          <option value='-1' style='color:black'>{$ibforums->lang['moderation_ops']}</option>
          $data
          </select>&nbsp;<input type='submit' value='{$ibforums->lang['jmp_go']}' class='forminput' /></form>
          <!--</td>
        </tr>
    </table>-->
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mod_wrapper
//===========================================================================
function mod_wrapper($id="",$text="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<option value='$id'>$text</option>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mq_image_add
//===========================================================================
function mq_image_add($pid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<img src="{$ibforums->vars['img_url']}/p_mq_add.gif" name="mad_$pid" alt="+" />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mq_image_remove
//===========================================================================
function mq_image_remove($pid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<img src="{$ibforums->vars['img_url']}/p_mq_remove.gif" name="mad_$pid" alt="-" />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// pid_image_selected
//===========================================================================
function pid_image_selected($pid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<img name="img{$pid}" src="{$ibforums->vars['img_url']}/topic_selected.gif" />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// pid_image_unselected
//===========================================================================
function pid_image_unselected($pid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<img name="img{$pid}" src="{$ibforums->vars['img_url']}/topic_unselected.gif" />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// post_icon
//===========================================================================
function post_icon($icon="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<img src="{$ibforums->vars['img_url']}/folder_post_icons/icon{$icon}.gif" alt="" />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// quick_reply_box_closed
//===========================================================================
function quick_reply_box_closed() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="javascript:ShowHide('qr_open','qr_closed');" title="{$ibforums->lang['qr_open']}" accesskey="f"><{T_QREPLY}></a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// quick_reply_box_open
//===========================================================================
function quick_reply_box_open($fid="",$tid="",$show="hide",$key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
	function emo_pop(){
		window.open("index.{$ibforums->vars['php_ext']}?act=legends&amp;CODE=emoticons&amp;s={$ibforums->session_id}","Legends","width=250,height=500,resizable=yes,scrollbars=yes"); 
	}
-->
</script>
<div id="qr_open" style="display: $show; position: relative;">
<br />
<form name="REPLIER" action="{$ibforums->base_url}" method="post">
<input type="hidden" name="act" value="Post" />
<input type="hidden" name="CODE" value="03" />
<input type="hidden" name="f" value="$fid" />
<input type="hidden" name="t" value="$tid" />
<input type="hidden" name="st" value="{$ibforums->input['st']}" />
<input type="hidden" name="auth_key" value="$key" />
<!-- TITLE DIV -->
<div class="borderwrap">
	<div class="maintitle"><{CAT_IMG}>&nbsp;{$ibforums->lang['qr_title']}</div>
	<div style='padding:6px' align="center">
		<textarea cols="70" rows="8" name="Post" class="textarea" tabindex="1"></textarea>
		<br />
		<br />
		<a href="javascript:emo_pop();">{$ibforums->lang['show_emo']}</a>
		<br />
EOF;
//startif
if ( $ibforums->member['auto_track'] == "" or $ibforums->member['auto_track'] == '0' )
{
$IPBHTML .= <<<EOF
<input type="checkbox" name="enabletrack" value="1" class="checkbox" />&nbsp;{$ibforums->lang['qr_add_email']} &#124;
EOF;
}//endif
else
{
$IPBHTML .= <<<EOF
<input type="checkbox" name="enabletrack" value="1" class="checkbox" checked="checked" />&nbsp;{$ibforums->lang['qr_add_email']} &#124;
EOF;
}//endelse
$IPBHTML .= <<<EOF
		<input type="checkbox" name="enableemo" value="yes" class="checkbox" checked="checked" />&nbsp;{$ibforums->lang['qr_add_smilie']} &#124;
		<input type="checkbox" name="enablesig" value="yes" class="checkbox" checked="checked" />&nbsp;{$ibforums->lang['qr_add_sig']}
		<br />
		<br />
		<input type="submit" name="submit" value="{$ibforums->lang['qr_submit']}" class="button" tabindex="2" accesskey="s" />&nbsp;
		<input type="submit" name="preview" value="{$ibforums->lang['qr_more_opts']}" class="button" />
		&nbsp;&nbsp; <input type="button" name="qrc" onclick="ShowHide('qr_open','qr_closed');" value="{$ibforums->lang['qr_closeit']}" class="button" />
	</div>
</div>
</form>
</div>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// quickreply
//===========================================================================
function quickreply($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</table></td></tr> 
  <tr> 
    <td>
<form action='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}' method='POST' name='REPLIER'>
<input type='hidden' name='st' value='0'>
<input type='hidden' name='act' value='Post'>
<input type='hidden' name='f' value='$data[f]'>
<input type='hidden' name='CODE' value='03'>
<input type='hidden' name='t' value='$data[t]'>
<input type='hidden' name='enableemo' value='yes'>
<input type='hidden' name='enablesig' value='yes'>
<table cellpadding='0' cellspacing='0' border='0' width='100%' bgcolor='{$ibforums->skin['tbl_border']}' align='center'>
       <tr>
           <td>
               <table cellpadding='4' cellspacing='1' border='0' width='100%' class='row1'>
               <tr>
               <td align='center' colspan='2' class='titlemedium'>Réponse rapide</td>
               </tr>
               <tr>
               <td class='category' align='left' colspan='2'>Entrez votre réponse ci-dessous :</td>
               </tr>
   <tr>
  <td class='row1' align='center' colspan='2'>$data[guest_box]</td>
  </tr>
   <tr><td class='row1' align='center'><textarea cols='60' rows='6' wrap='soft' name='Post' tabindex='3' class='textinput'></textarea></td></tr>
                   <tr>
               <td class='row2' align='center' colspan='2'>
               <input type="submit" name="submit" value="Ajouter réponse" tabindex='4' class='forminput'>&nbsp;
               <input type="submit" name="preview" value="Editer réponse" tabindex='5' class='forminput'>
               </td>
               </tr>
           </table>
           </td>
         </tr>
      </table>
  </form>
    </td>
  </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// render_row_hidden
//===========================================================================
function render_row_hidden($post="",$author="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<!--Begin Msg Number {$post['pid']}-->
<table cellspacing="1">
	<tr>
		<td valign="middle" class="row2" width="1%"><a name="entry{$post['pid']}"></a><span class="{$post['name_css']}">{$author['name']}</span></td>
		<td class="row2" valign="top" width="99%">
			<!-- POSTED DATE DIV -->
			<div class="row2">
				{$post['post_icon']}<span class="postdetails"><b><a title="{$ibforums->lang['tt_link']}" href="#" onclick="link_to_post({$post['pid']}); return false;">{$ibforums->lang['posted_on']}</a></b> {$post['post_date']}</span>
			</div>
		</td>
	</tr>
	<tr>
		<td valign="top" class="row2">
			{$author['title']}<br />
			{$author['member_rank_img']}<br /><br />
			{$author['member_group']}<br />
			{$author['member_posts']}<br />
			<img src="{$ibforums->vars['img_url']}/spacer.gif" alt="" width="160" height="1" /><br /> 
		</td>
		<td width="100%" valign="top" class="row2">
        	<!-- THE POST {$post['pid']} --> 
        	You have chosen to ignore {$post['author_name']}.
        	<a href="{$ibforums->base_url}showtopic={$post['topic_id']}&amp;view=findpost&amp;p={$post['pid']}">View this post</a> &middot; <a href="{$ibforums->base_url}act=UserCP&amp;CODE=ignoreremove&amp;id={$author['id']}">Un-ignore {$post['author_name']}</a>
        	<!-- THE POST -->
        </td>
	</tr>
</table>
<div class="catend"><!-- --></div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// renderrow
//===========================================================================
function renderrow($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
		<!--Begin Msg Number {$data[POST]['pid']}-->
		 <tr>
		 <td valign='middle' class='posthead'><a name='entry{$data[POST]['pid']}'></a><span class='{$data[POST]['name_css']}'>{$data[POSTER]['name']}</span></td>
          <td class='posthead' valign='top'>
			<table width='100%' border='0' cellspacing='0' cellpadding='0'>
              <tr> 
                <td class='posthead'>{$data[POST]['post_icon']}<span class='postdetails'><b>{$ibforums->lang['posted_on']}</b> {$data[POST]['post_date']}</span></td>
                <td class='posthead' align='right'>{$data[POST]['delete_button']}{$data[POST]['edit_button']}<a href='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&act=Post&CODE=06&f={$ibforums->input[f]}&t={$ibforums->input[t]}&p={$data[POST]['pid']}'><{P_QUOTE}></a></td>
              </tr>
            </table>
		 </td>
        </tr>
		<tr>
          <td valign='top' class='{$data['POST']['post_css']}'>
            	<span class='postdetails'>{$data[POSTER]['avatar']}<br><br>
				{$data[POSTER]['title']}<br>
				{$data[POSTER]['member_rank_img']}<br><br>
            	{$data[POSTER]['member_group']}<br>
            	{$data[POSTER]['member_posts']}<br>
            	{$data[POSTER]['member_number']}<br>
            	{$data[POSTER]['member_joined']}<br>
            	{$data[POSTER][WARN_GFX]}<br><br></span>
		        <img src='{$ibforums->vars['img_url']}/spacer.gif' alt='' width='160' height='1'><br> 
          </td>
          <td width='100%' valign='top' class='{$data['POST']['post_css']}'><span class='postcolor'>{$data[POST]['post']} {$data[POST]['attachment']} {$data[POST]['signature']}</td>
        </tr>
        <tr>
		   <td class='postfoot' align='left'>{$data[POST]['ip_address']}&nbsp;</td>
		   <td class='postfoot' nowrap align='left'>
		    <table width='100%' border='0' cellspacing='0' cellpadding='0'>
              <tr>
                <td class='postfoot' align='left' valign='middle' nowrap>{$data[POSTER]['message_icon']}{$data[POSTER]['email_icon']}{$data[POSTER]['website_icon']}{$data[POSTER]['icq_icon']}{$data[POSTER]['aol_icon']}{$data[POSTER]['yahoo_icon']}{$data[POSTER]['msn_icon']}</td>
                <td class='postfoot' valign='middle' align='right'>{$data[POST]['report_link']}&nbsp;</td>
		   		<td class='postfoot' valign='middle' align='right' width='2%'><a href='javascript:scroll(0,0);'><img src='{$ibforums->vars['img_url']}/p_up.gif' alt='Top' border='0'></a></td>
		      </tr>
		    </table>
		   </td>
        </tr>
        <tr> 
          <td class='postsep' colspan='2'><img src='{$ibforums->vars['img_url']}/spacer.gif' alt='' width='1' height='1'></td>
		</tr>
  <!-- end Message -->
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// report_link
//===========================================================================
function report_link($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<span class='desc'><a href='{$ibforums->base_url}&act=report&f={$data['forum_id']}&t={$data['topic_id']}&p={$data['pid']}&st={$ibforums->input['st']}'>{$ibforums->lang['snitch_geezer_to_a_copper']}</a></span>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// show_attachment_title
//===========================================================================
function show_attachment_title($title="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br /><br /><b><span class="edit">$title</span></b><br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// Show_attachments
//===========================================================================
function Show_attachments($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
    <br><br>
     <table cellpadding='4' cellspacing='0' border='0' width='50%' align='center' class='fancyborder'>
      <tr>
       <td align='right' valign='middle' rowspan='2'><img src='{$ibforums->vars['mime_img']}/{$data['image']}' border='0' alt='User Attached Image'></td>
        <td align='left'><a href='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&act=Attach&type=post&id={$data['pid']}' target='_blank'>{$ibforums->lang['attach_dl']}</a></td>
      </tr>
      <tr>
      <td align='left' valign='middle' width='98%'>{$data['name']}  ( {$ibforums->lang['attach_hits']}: {$data['hits']} )</td>
      </tr>
     </table>
     <br><br>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// Show_attachments_img
//===========================================================================
function Show_attachments_img($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br><br><center><b>{$ibforums->lang['pic_attach']}</b></center><br>
<table cellpadding='4' cellspacing='0' border='0' width='50%' align='center' class='fancyborder'>
 <tr>
  <td valign='middle' align='center'><img src='{$ibforums->vars['upload_url']}/{$data['file_name']}' border='0' alt='{$ibforums->lang['pic_attach']}'></td>
 </tr>
</table>
<p>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// Show_attachments_img_thumb
//===========================================================================
function Show_attachments_img_thumb($file_name="",$width="",$height="",$aid="",$size="",$hits="",$file="",$method="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="{$ibforums->base_url}act=Attach&amp;type=$method&amp;id=$aid" title="$file - {$ibforums->lang['attach_size']} $size, {$ibforums->lang['attach_ahits']} $hits" target="_blank"><img src="{$ibforums->vars['upload_url']}/$file_name" width="$width" height="$height" class="attach" alt="{$ibforums->lang['pic_attach']}" /></a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// start_poll_link
//===========================================================================
function start_poll_link($fid="",$tid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="{$ibforums->base_url}act=Post&amp;CODE=14&amp;f=$fid&amp;t=$tid"><{A_APOLL}></a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tablefooter
//===========================================================================
function tablefooter($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
  <tr> 
    <td class='mainbg'>
      <!--IBF.TOPIC_ACTIVE-->
	   <table width='100%' border='0' cellspacing='1' cellpadding='4'>
        <tr>
          <td class='titlemedium' width='100%'>
			<table width='100%' border='0' cellspacing='0' cellpadding='0'>
              <tr>
                <td align='left'><b>{$ibforums->lang['topic_stats']}</b></td>
              	<td align='right'><b><a href='{$ibforums->base_url}&act=Track&f={$data['FORUM']['id']}&t={$data['TOPIC']['tid']}'>{$ibforums->lang['track_topic']}</a> |
									<a href='{$ibforums->base_url}&act=Forward&f={$data['FORUM']['id']}&t={$data['TOPIC']['tid']}'>{$ibforums->lang['forward']}</a> |
									<a href='{$ibforums->base_url}&act=Print&client=printer&f={$data['FORUM']['id']}&t={$data['TOPIC']['tid']}'>{$ibforums->lang['print']}</a></b></td>
               </tr>
            </table>
		  </td>
        </tr>
      </table>
		</td>
  </tr>
</table>
<table width='<{tbl_width}>' align='center' border='0' cellspacing='0' cellpadding='4'>
  <tr> 
    <td width='100%'>{$data[TOPIC][SHOW_PAGES]}
    <br>&lt;&lt; <a href='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&act=SF&f={$data['FORUM']['id']}'>{$ibforums->lang['b_back_to']} {$data['FORUM']['name']}</a></td>
    <td align='right' nowrap>{$data[TOPIC][REPLY_BUTTON]}<a href='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&act=Post&CODE=00&f={$data[FORUM]['id']}' title='{$ibforums->lang['start_new_topic']}'><{A_POST}></a>{$data[TOPIC][POLL_BUTTON]}</td>
  </tr>
</table>
<br>
<table width='<{tbl_width}>' align='center' border='0' cellspacing='0' cellpadding='3'>
  <tr>
  	<td width='60%' align='left'>
  	   <!--IBF.EMAIL_OPTIONS-->
  	</td>
    <td width='40%' align='right' nowrap valign='top'>{$data[FORUM]['JUMP']}<br><br><!--IBF.MOD_PANEL--></td>
  </tr>
</table>
<br>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// topic_active_users
//===========================================================================
function topic_active_users($active=array()) {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
	
	  <table width='100%' border='0' cellspacing='1' cellpadding='4'>
		  <tr> 
			<td class='titlemedium' align='left'>{$ibforums->lang['active_users_title']} ({$ibforums->lang['active_users_detail']})</td>
		  </tr>
		  <tr>
			<td class='forum1'><b>{$ibforums->lang['active_users_members']}</b> {$active['names']}</td>
		  </tr>
	  </table>
	 
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// topic_end_first_post
//===========================================================================
function topic_end_first_post($data="",$noreplieshow=0) {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</div>
<table cellspacing="0">
	<tr>
		<td style='padding-left:0px' width="40%" valign="middle" nowrap="nowrap"><div>{$data['TOPIC']['SHOW_PAGES']}&nbsp;{$data['TOPIC']['go_new']}</div></td>
		<td class='nopad' style='padding:5px 0px 5px 0px' align="right" width="60%" valign="middle">{$data[TOPIC][REPLY_BUTTON]}<a href="{$ibforums->base_url}act=Post&amp;CODE=00&amp;f={$data[FORUM]['id']}" title="{$ibforums->lang['start_new_topic']}"><{A_POST}></a>{$data[TOPIC][POLL_BUTTON]}<!--{IBF.START_NEW_POLL}--></td>
	</tr>
</table>
<a name="firstpost"></a>
<div class="borderwrap">
	<div class="maintitle">{$ibforums->lang['tom_replies']}
EOF;
//startif
if ( $noreplieshow != 1 )
{
$IPBHTML .= <<<EOF
({$data['TOPIC']['new_mode_start']} - {$data['TOPIC']['new_mode_end']})
EOF;
}//endif
$IPBHTML .= <<<EOF
	</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// topic_end_outline
//===========================================================================
function topic_end_outline($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</div>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// topic_opts_closed
//===========================================================================
function topic_opts_closed() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="javascript:ShowHide('topic_open','topic_closed')" title="{$ibforums->lang['to_open']}"><{T_OPTS}></a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// topic_opts_open
//===========================================================================
function topic_opts_open($fid="",$tid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div id="topic_open" style="display: none; z-index: 2;">
	<br />
	<div class="borderwrap">
		<div class="maintitle"><{CAT_IMG}>&nbsp;<a href="javascript:ShowHide('topic_open','topic_closed')">{$ibforums->lang['to_close']}</a></div>
		<div class="tablepad">
			<b><a href="{$ibforums->base_url}act=Track&amp;f={$fid}&amp;t={$tid}">{$ibforums->lang['tt_title']}</a></b><br />
			<span class="desc">{$ibforums->lang['tt_desc']}</span><br /><br />
			<b><a href="{$ibforums->base_url}act=Track&amp;f={$fid}&amp;type=forum">{$ibforums->lang['ft_title']}</a></b><br />
			<span class="desc">{$ibforums->lang['ft_desc']}</span><br /><br />
			<b><a href="{$ibforums->base_url}act=Print&amp;client=choose&amp;f={$fid}&amp;t={$tid}">{$ibforums->lang['av_title']}</a></b><br />
			<span class="desc">{$ibforums->lang['av_desc']}</span>
		</div>
	</div>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// topic_page_top_classic
//===========================================================================
function topic_page_top_classic($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
var ipb_lang_tt_prompt = "{$ibforums->lang['tt_prompt']}";
var ipb_lang_js_del_1  = "{$ibforums->lang['js_del_1']}";
var ipb_lang_js_del_2  = "{$ibforums->lang['js_del_2']}";
var addquotebutton     = "{$ibforums->vars['img_url']}/p_mq_add.gif";
var removequotebutton  = "{$ibforums->vars['img_url']}/p_mq_remove.gif";
var unselectedbutton = "{$ibforums->vars['img_url']}/topic_unselected.gif";
var selectedbutton   = "{$ibforums->vars['img_url']}/topic_selected.gif";
var lang_gobutton    = "{$ibforums->lang['f_go']}";
var lang_suredelete  = "{$ibforums->lang['cp_js_delete']}";
-->
</script>
<script type="text/javascript" src="jscripts/ipb_topic.js"></script>
<a name="top"></a>
<!--IBF.FORUM_RULES-->
<table cellspacing="0">
	<tr>
		<td style='padding-left:0px' width="40%" valign="middle" nowrap="nowrap"><div>{$data['TOPIC']['SHOW_PAGES']}&nbsp;{$data['TOPIC']['go_new']}</div></td>
		<td class='nopad' style='padding:0px 0px 5px 0px' align="right" width="60%" valign="middle">{$data[TOPIC][REPLY_BUTTON]}<a href="{$ibforums->base_url}act=Post&amp;CODE=00&amp;f={$data[FORUM]['id']}" title="{$ibforums->lang['start_new_topic']}"><{A_POST}></a>{$data[TOPIC][POLL_BUTTON]}<!--{IBF.START_NEW_POLL}--></td>
	</tr>
</table>
<div class="borderwrap">
	<div class="maintitle">
		<p class="expand">
			{$data['TOPIC']['to_button_threaded']} &middot;
			{$data['TOPIC']['to_button_standard']} &middot;
			{$data['TOPIC']['to_button_linearpl']}
		</p>
		<p><{CAT_IMG}>&nbsp;<b>{$data['TOPIC']['title']}</b>{$data['TOPIC']['description']}</p>
	</div>
	<!--{IBF.POLL}-->
	<div align="right" class="subtitle">
		<div><a href="{$ibforums->base_url}act=usercp&amp;CODE=start_subs&amp;method=topic&amp;tid={$data['TOPIC']['tid']}">{$ibforums->lang['track_topic']}</a> | <a href="{$ibforums->base_url}act=Forward&amp;f={$data['FORUM']['id']}&amp;t={$data['TOPIC']['tid']}">{$ibforums->lang['forward']}</a> | <a href="{$ibforums->base_url}act=Print&amp;client=printer&amp;f={$data['FORUM']['id']}&amp;t={$data['TOPIC']['tid']}">{$ibforums->lang['print']}</a>
		</div>
	</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// topic_page_top_new_mode
//===========================================================================
function topic_page_top_new_mode($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
    <script language='javascript'>
    <!--
    function delete_post(theURL) {
       if (confirm('{$ibforums->lang['js_del_1']}')) {
          window.location.href=theURL;
       }
       else {
          alert ('{$ibforums->lang['js_del_2']}');
       } 
    }
    
    function PopUp(url, name, width,height,center,resize,scroll,posleft,postop) {
    if (posleft != 0) { x = posleft }
    if (postop  != 0) { y = postop  }
    if (!scroll) { scroll = 1 }
    if (!resize) { resize = 1 }
    if ((parseInt (navigator.appVersion) >= 4 ) && (center)) {
      X = (screen.width  - width ) / 2;
      Y = (screen.height - height) / 2;
    }
    if (scroll != 0) { scroll = 1 }
    var Win = window.open( url, name, 'width='+width+',height='+height+',top='+Y+',left='+X+',resizable='+resize+',scrollbars='+scroll+',location=no,directories=no,status=no,menubar=no,toolbar=no');
	}
    //-->
    </script>
<a name='top'></a>
<!-- Cgi-bot Start Forum page unique top -->
<table width='<{tbl_width}>' border='0' cellspacing='0' cellpadding='4' align='center'>
  <tr> 
    <td width='100%'>{$data['TOPIC']['SHOW_PAGES']}&nbsp;{$data['TOPIC']['go_new']}</td>
    <td align='right' nowrap>{$data[TOPIC][REPLY_BUTTON]}<a href='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&act=Post&CODE=00&f={$data[FORUM]['id']}' title='{$ibforums->lang['start_new_topic']}'><{A_POST}></a>{$data[TOPIC][POLL_BUTTON]}</td>
  </tr>
</table>
<table width='<{tbl_width}>' border='0' cellspacing='1' cellpadding='0' bgcolor='<{tbl_border}>' align='center'>
  <tr> 
    <td class='maintitle'>
			<table width='100%' border='0' cellspacing='0' cellpadding='3'>
        <tr> 
          <td><img src='{$ibforums->vars['img_url']}/nav_m.gif' alt='' width='8' height='8'></td>
          <td width='100%' class='maintitle'><b>{$data['TOPIC']['title']}</b>{$data['TOPIC']['description']}</td>
        </tr>
      </table>
		</td>
  </tr>
  <tr> 
	<td class='mainbg'>
	<!--{IBF.POLL}-->
	<table width='100%' border='0' cellspacing='1' cellpadding='4'>
	<tr> 
	  <td width='100%' class='titlemedium' nowrap colspan="2"> 
		<table width='100%' border='0' cellspacing='0' cellpadding='0'>
		  <tr>
		    <td align='left'><b>&laquo; <a href='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&act=ST&f={$data[FORUM]['id']}&t={$data[TOPIC]['tid']}&view=old'>{$ibforums->lang['t_old']}</a> | <a href='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&act=ST&f={$data[FORUM]['id']}&t={$data[TOPIC]['tid']}&view=new'>{$ibforums->lang['t_new']}</a> &raquo;</b></td>
			<td align='right'><b>
				<a href='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&act=Track&f={$data['FORUM']['id']}&t={$data['TOPIC']['tid']}'>{$ibforums->lang['track_topic']}</a> |
				<a href='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&act=Forward&f={$data['FORUM']['id']}&t={$data['TOPIC']['tid']}'>{$ibforums->lang['forward']}</a> |
				<a href='{$ibforums->vars['board_url']}/index.{$ibforums->vars['php_ext']}?s={$ibforums->session_id}&act=Print&client=printer&f={$data['FORUM']['id']}&t={$data['TOPIC']['tid']}'>{$ibforums->lang['print']}</a></b></td>
			</tr>
		</table>
	  </td>
	</tr>
<!-- Cgi-bot End Forum page unique top -->
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// toutline_end_list
//===========================================================================
function toutline_end_list($pages="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</div>
	<div class="row1">$pages</div>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// toutline_end_new_parent
//===========================================================================
function toutline_end_new_parent() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// toutline_mode_choice_off
//===========================================================================
function toutline_mode_choice_off($url="",$macro="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="$url">$macro</a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// toutline_mode_choice_on
//===========================================================================
function toutline_mode_choice_on($url="",$macro="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
[ <a href="$url">$macro</a> ]
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// toutline_show_row
//===========================================================================
function toutline_show_row($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
{$data['depthguide']} {$data['new_post']} <b>{$data['linked_name']}</b> &nbsp; <i><a href="{$ibforums->base_url}showtopic={$data['topic_id']}&amp;pid={$data['pid']}&amp;mode=threaded&amp;show={$ibforums->input['show']}&amp;st={$ibforums->input['st']}&#entry{$data['pid']}">{$data['post_title']}</a></i> &nbsp; <span class="desc">{$data['formatted_date']}</span><br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// toutline_show_row_highlight
//===========================================================================
function toutline_show_row_highlight($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div style='background:#FFF9BA;'>{$data['depthguide']} {$data['new_post']} <b>{$data['linked_name']}</b> &nbsp; <i><a href="{$ibforums->base_url}showtopic={$data['topic_id']}&amp;pid={$data['pid']}&amp;mode=threaded&amp;show={$ibforums->input['show']}&amp;st={$ibforums->input['st']}&#entry{$data['pid']}">{$data['post_title']}</a></i> &nbsp; <span class="desc">{$data['formatted_date']}</span></div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// toutline_start_list
//===========================================================================
function toutline_start_list() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="borderwrap">
	<div class="maintitle">Posts in this topic</div>
	<div class="tablepad">
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// toutline_start_new_parent
//===========================================================================
function toutline_start_new_parent() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// warn_level_rating
//===========================================================================
function warn_level_rating($id="",$level="",$min=0,$max=10) {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
&lt;&nbsp;$min ( <a href="javascript:PopUp('{$ibforums->base_url}act=warn&amp;mid={$id}&amp;CODE=view','Pager','500','450','0','1','1','1')">{$level}</a> ) $max&nbsp;&gt;
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// warn_level_warn
//===========================================================================
function warn_level_warn($id="",$percent="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
{$ibforums->lang['tt_warn']} (<a href="javascript:PopUp('{$ibforums->base_url}act=warn&amp;mid={$id}&amp;CODE=view','Pager','500','450','0','1','1','1')">{$percent}</a>%)
EOF;

//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
email_options,golastpost_link,ip_show,Mod_Panel,mod_wrapper,quickreply,renderrow,report_link,Show_attachments,Show_attachments_img,tablefooter,topic_active_users,topic_page_top_new_mode
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>