<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 2                     */
/* CACHE FILE: Generated: Wed, 31 Aug 2005 00:22:38 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_portal {

//===========================================================================
// csite_css_external
//===========================================================================
function csite_css_external($css="",$img="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<style type="text/css" media="all">
	@import url({$ibforums->vars['board_url']}/css.php?d={$css}_{$img}.css);
</style>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// csite_css_inline
//===========================================================================
function csite_css_inline($css="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<style type="text/css">
	{$css}
</style>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// csite_javascript
//===========================================================================
function csite_javascript() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<!-- -->
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// csite_sep_char
//===========================================================================
function csite_sep_char() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
,
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// csite_skeleton_template
//===========================================================================
function csite_skeleton_template() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
		<meta name="generator" content="IPDynamic Lite">
		<meta http-equiv="Pragma" content="no-cache">
		<meta http-equiv="no-cache">
		<meta http-equiv="Cache-Control" content="no-cache">
		<title><!--CS.TEMPLATE.TITLE--></title>
		<!--CS.TEMPLATE.JAVASCRIPT-->
		<!--CS.TEMPLATE.CSS-->
	</head>
	<body>
		<script type="text/javascript">
		<!--
		 var ipb_var_st       = "{$ibforums->input['st']}";
		 var ipb_lang_tpl_q1  = "{$ibforums->lang['tpl_q1']}";
		 var ipb_var_s        = "{$ibforums->session_id}";
		 var ipb_var_phpext   = "{$ibforums->vars['php_ext']}";
		 var ipb_var_base_url = "{$ibforums->js_base_url}";
		 var ipb_input_f      = "{$ibforums->input['f']}";
		 var ipb_input_t      = "{$ibforums->input['t']}";
		 var ipb_input_p      = "{$ibforums->input['p']}";
		 var ipb_var_cookieid = "{$ibforums->vars['cookie_id']}";
		 //-->
		</script>
		<script type="text/javascript" src="jscripts/ipb_global.js"></script>
		<div id="ipbwrapper">
			<!--Header-->
			<div class="borderwrap">
				<div id="logostrip">
					<a href="{$ibforums->base_url}" title="Return to Forums Index, Powered by IPB"><img src='style_images/<#IMG_DIR#>/logo4.gif' style='vertical-align:top' alt='IPB' border='0' /></a>
				</div>
				<div id="submenu">
					<p class="home"><a href="{$ibforums->vars['home_url']}">{$ibforums->vars['home_name']}</a><!--IBF.RULES--></p>
					<p>
EOF;
//startif
if ( $ibforums->vars['gallery_images_path'] != '' )
{
$IPBHTML .= <<<EOF
<a href="{$ibforums->base_url}act=module&module=gallery">{$ibforums->lang['gallery']}</a>
EOF;
}//endif
$IPBHTML .= <<<EOF
						<a href="{$ibforums->base_url}act=Help">{$ibforums->lang['tb_help']}</a><a href="{$ibforums->base_url}act=Search&amp;f={$ibforums->input['f']}">{$ibforums->lang['tb_search']}</a><a href="{$ibforums->base_url}act=Members">{$ibforums->lang['tb_mlist']}</a><a href="{$ibforums->base_url}act=calendar">{$ibforums->lang['tb_calendar']}</a><!--IBF.CHATLINK--><!--IBF.TSLLINK--></td>
					</p>
				</div>
			</div>
			<!--CS.TEMPLATE.WELCOMEBOX-->
			<!--CS.TEMPLATE.LINKS-->
			<!--End Header-->
			<!--Main Content-->
			<table cellspacing="0">
				<tr>
					<td width="25%" class="nopad" valign="top">
						<!-- LEFT -->
						<!--CS.TEMPLATE.SEARCH-->
						<!--CS.TEMPLATE.SITENAV-->
						<!--CS.TEMPLATE.CHANGESKIN-->
						<!--CS.TEMPLATE.ONLINEUSERS-->
						<!--CS.TEMPLATE.POLL-->
						<!--CS.TEMPLATE.LATESTPOSTS-->
						<!--CS.TEMPLATE.RECENTARTICLES-->
						<!--CS.TEMPLATE.AFFILIATES-->
						<!--END LEFT-->
					</td>
					<!--SPACER-->
					<td width="1%" class="nopad">&nbsp;</td>
					<td width="75%" class="nopad" valign="top">
						<!--MAIN-->
						<!--CS.TEMPLATE.ARTICLES-->
						<!--END MAIN-->
					</td>
				</tr>
				<!--End Main Content-->
			</table>
			<!--CS.TEMPLATE.COPYRIGHT-->
			<div style="text-align: center;"><!--CS.TEMPLATE.DEBUG--></div>
		</div>
	</body>
</html>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// rules_link
//===========================================================================
function rules_link($url="",$title="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
&nbsp;<a href="$url">$title</a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// show_chat_link_inline
//===========================================================================
function show_chat_link_inline() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
&nbsp;<a href="{$ibforums->base_url}act=chat">{$ibforums->lang['live_chat']}</a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// show_chat_link_popup
//===========================================================================
function show_chat_link_popup() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
&nbsp;<a href="javascript:chat_pop();">{$ibforums->lang['live_chat']}</a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_affiliates
//===========================================================================
function tmpl_affiliates($links="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br />
<div class="borderwrap">
	<div class="maintitle"><{CAT_IMG}>&nbsp;{$ibforums->lang['aff_title']}</div>
	<div class="tablepad">
		$links
	</div>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_articles
//===========================================================================
function tmpl_articles($articles="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
$articles
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_articles_row
//===========================================================================
function tmpl_articles_row($entry="",$bottom_string="",$top_string="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="borderwrap">
<table cellspacing="0">
	<tr>
		<td class="maintitle" colspan="2"><{CAT_IMG}>&nbsp;<a href="{$ibforums->base_url}showtopic={$entry['tid']}">{$entry['title']}</a></td>
	</tr>
	<tr>
		<td class="row1" colspan="2">$top_string</td>
	</tr>
	<tr>
		<td class="post1" width="5%" valign="top">{$entry['avatar']}</td>
		<td class="post1" width="95%" valign="top"><div style="height: 200px; overflow: auto;">{$entry['post']}
		<!--IBF.ATTACHMENT_{$entry['pid']}--></div></td>
	</tr>
	<tr>
		<td class="row1" colspan="2" align="right">
		$bottom_string
		&nbsp;&nbsp;<a href="{$ibforums->base_url}act=Print&amp;client=printer&amp;f={$entry['forum_id']}&amp;t={$entry['tid']}"><img src='style_images/<#IMG_DIR#>/cs_print.gif' border='0' /></a>
		<a href="{$ibforums->base_url}act=Forward&amp;f={$entry['forum_id']}&amp;t={$entry['tid']}"><img src='style_images/<#IMG_DIR#>/cs_email.gif' border='0' /></a>
		</td>
	</tr>
</table>
</div>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_changeskin
//===========================================================================
function tmpl_changeskin($select="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br />
<form action="{$ibforums->vars['dynamiclite']}&amp;s={$ibforums->session_id}&amp;setskin=1" method="post">
	<div class="borderwrap">
		<div class="maintitle"><{CAT_IMG}> {$ibforums->lang['cskin_title']}</div>
		<div class="formsubtitle">{$ibforums->lang['cskin_text']}</div>
		<div class="tablepad" align="center">
			$select &nbsp; <input type="submit" value="{$ibforums->lang['cskin_go']}" />
		</div>
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_comment_link
//===========================================================================
function tmpl_comment_link($tid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="{$ibforums->base_url}showtopic=$tid&amp;view=getlastpost">{$ibforums->lang['article_comment']}</a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_debug
//===========================================================================
function tmpl_debug($queries="",$time="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="desc">[ DB Queries: $queries ] [ Execution Time: $time ]</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_latestposts
//===========================================================================
function tmpl_latestposts($posts="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br />
<div class="borderwrap">
	<div class="maintitle"><{CAT_IMG}>&nbsp;{$ibforums->lang['discuss_title']}</div>
	$posts
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_links_wrap
//===========================================================================
function tmpl_links_wrap($link="",$name="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
&middot; <a href="$link">$name</a><br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_onlineusers
//===========================================================================
function tmpl_onlineusers($breakdown="",$split="",$names="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br />
<div class="borderwrap">
	<div class="maintitle"><{CAT_IMG}>&nbsp;<a href="{$ibforums->base_url}act=Online">{$ibforums->lang['online_title']}</a></div>
	<div class="tablepad">
		<span class="desc">$breakdown<br />$split<br />$names</span>
	</div>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_poll_choice_row
//===========================================================================
function tmpl_poll_choice_row($id="",$choice="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<input type="radio" name="poll_vote" value="$id" class="radiobutton" />&nbsp;<b>$choice</b>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_poll_footer
//===========================================================================
function tmpl_poll_footer($vote="",$total="",$tid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<span class="desc">
				&middot; <b>$total</b>
				<br />&middot; $vote
				<br />&middot; <a href="{$ibforums->base_url}showtopic=$tid">{$ibforums->lang['poll_discuss']}</a>
			</span>
		</div>
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_poll_header
//===========================================================================
function tmpl_poll_header($question="",$tid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br />
<form action="{$ibforums->base_url}act=Poll&amp;t=$tid" method="post">
	<div class="borderwrap">
		<div class="maintitle"><{CAT_IMG}>&nbsp;<a href="{$ibforums->base_url}showtopic=$tid">{$ibforums->lang['poll_title']}</a></div>
		<div class="formsubtitle">$question</div>
		<div class="tablepad">
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_poll_result_row
//===========================================================================
function tmpl_poll_result_row($votes="",$id="",$choice="",$percent="",$width="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
$choice
<br /><{BAR_LEFT}><img src="{$ibforums->vars['img_url']}/bar.gif" width="$width" height="11" align="middle" alt="" /><{BAR_RIGHT}>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_poll_vote
//===========================================================================
function tmpl_poll_vote() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<input type="submit" value="{$ibforums->lang['poll_vote']}" class="codebuttons" />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_readmore_link
//===========================================================================
function tmpl_readmore_link($tid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
...<a href="{$ibforums->base_url}showtopic=$tid">{$ibforums->lang['article_readmore']}</a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_recentarticles
//===========================================================================
function tmpl_recentarticles($articles="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br />
<div class="borderwrap">
	<div class="maintitle"><{CAT_IMG}>&nbsp;{$ibforums->lang['recent_title']}</div>
	$articles
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_search
//===========================================================================
function tmpl_search() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form action="{$ibforums->base_url}act=Search&amp;CODE=01&amp;forums=all" method="post" name="search">
	<div class="borderwrap">
		<div class="maintitle"><{CAT_IMG}>&nbsp;{$ibforums->lang['search_title']}</div>
		<div class="formsubtitle"><a href="{$ibforums->base_url}act=Search&amp;mode=adv">{$ibforums->lang['search_advanced']}</a></div>
		<div class="tablepad" align="center">
			<input type="text" name="keywords" value="" size="15" />&nbsp;<input type="submit" value="{$ibforums->lang['search_go']}" />
		</div>
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_sitenav
//===========================================================================
function tmpl_sitenav($links="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br />
<div class="borderwrap">
	<div class="maintitle"><{CAT_IMG}>&nbsp;{$ibforums->lang['links_title']}</div>
	<div class="tablepad">
		$links
	</div>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_skin_select_bottom
//===========================================================================
function tmpl_skin_select_bottom() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</select>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_skin_select_top
//===========================================================================
function tmpl_skin_select_top() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<select name="skinid" onchange="window.location='{$ibforums->vars['dynamiclite']}&s={$ibforums->session_id}&setskin=1&skinid=' + this.value">
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_topic_row
//===========================================================================
function tmpl_topic_row($tid="",$title="",$posts="",$views="",$mid="",$mname="",$date="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">
	<b><a href="{$ibforums->base_url}showtopic=$tid">$title</a></b>
</div>
<div class="tablepad">
	<a href="{$ibforums->base_url}showuser=$mid">$mname</a> &#064; $date
	<br />{$ibforums->lang['recent_read']}: $views &nbsp; {$ibforums->lang['recent_comments']}: $posts
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_welcomebox_guest
//===========================================================================
function tmpl_welcomebox_guest($top_string="",$return="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form action="{$ibforums->base_url}act=Login&amp;CODE=01&amp;CookieDate=1&amp;return=$return" method="post">
	<div id="userlinksguest">
		<p class="pcen"><b>{$ibforums->lang['wbox_welcome']}, {$ibforums->lang['wbox_guest_name']}</b> ( <a href="{$ibforums->base_url}act=Login&amp;CODE=00">{$ibforums->lang['log_in']}</a> | <a href="{$ibforums->base_url}act=Reg&amp;CODE=00">{$ibforums->lang['register']}</a> )</p>
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_welcomebox_member
//===========================================================================
function tmpl_welcomebox_member($pm_string="",$last_visit="",$name="",$return="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div id="userlinks">
		<p class="home"><b>{$ibforums->lang['wbox_welcome']}, $name</b> ( <a href="{$ibforums->base_url}act=Login&amp;CODE=03&amp;return=$return">{$ibforums->lang['wbox_logout']}</a> )<br /></p>
		<p><a href="{$ibforums->base_url}act=UserCP"><b>{$ibforums->lang['wbox_mycontrols']}</b></a>&nbsp;&middot;&nbsp;<a href="{$ibforums->base_url}act=Search&amp;CODE=getnew">{$ibforums->lang['wbox_getnewposts']}</a>&nbsp;&middot;&nbsp;<a href="javascript:buddy_pop();">{$ibforums->lang['wbox_myassistant']}</a>&nbsp;&middot;&nbsp;$pm_string</p>
	</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// tmpl_wrap_avatar
//===========================================================================
function tmpl_wrap_avatar($avatar="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
$avatar
EOF;

//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>