<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 5                     */
/* CACHE FILE: Generated: Wed, 31 Aug 2005 00:22:51 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_calendar {

//===========================================================================
// cal_birthday_end
//===========================================================================
function cal_birthday_end() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</ul>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_birthday_entry
//===========================================================================
function cal_birthday_entry($uid="",$uname="",$age="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<li><a href="{$ibforums->base_url}showuser=$uid">$uname</a> ($age)</li>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_birthday_start
//===========================================================================
function cal_birthday_start() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['cal_birthdays']}</div>
<div class="tablepad">
	<ul>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_blank_cell
//===========================================================================
function cal_blank_cell() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<td class="cellblank"><!-- no content --><br /></td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_date_cell
//===========================================================================
function cal_date_cell($month_day="",$events="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<td class="celldate">
	<div class="calday">$month_day</div>
	$events
</td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_date_cell_today
//===========================================================================
function cal_date_cell_today($month_day="",$events="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<td class="celltoday">
	<div class="calday">$month_day</div>
	$events
</td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_day_bit
//===========================================================================
function cal_day_bit($day="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<td width="14%" class="subtitle">$day</td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_edit_del_button
//===========================================================================
function cal_edit_del_button($id="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<a href="javascript:deleteEvent($id)"><b>Delete Event</b></a> / <a href="{$ibforums->base_url}act=calendar&amp;code=edit&amp;eventid=$id"><b>Edit Event</b></a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_events_end
//===========================================================================
function cal_events_end() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_events_start
//===========================================================================
function cal_events_start() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="calevents">
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_events_wrap
//===========================================================================
function cal_events_wrap($link="",$text="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="divpad">&middot; <a href="{$ibforums->base_url}act=calendar&amp;$link">$text</a></div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_events_wrap_range
//===========================================================================
function cal_events_wrap_range($link="",$text="",$ft="",$bg="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div style="background-color: $bg; color: $ft; padding: 3px; border-top: 1px outset $bg; border-bottom: 1px outset $bg;">
	<a href="{$ibforums->base_url}act=calendar&amp;$link" style="color: $ft;">$text</a>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_events_wrap_recurring
//===========================================================================
function cal_events_wrap_recurring($link="",$text="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="divpad">
	&middot; <a href="{$ibforums->base_url}act=calendar&amp;$link" title="{$ibforums->lang['tbt_recur']}">$text</a>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_main_content
//===========================================================================
function cal_main_content($month="",$year="",$prev="",$next="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="calmonths">
	<a href="{$ibforums->base_url}act=calendar&amp;m={$prev['month_id']}&amp;y={$prev['year_id']}" title="{$prev['month_name']} {$prev['year_id']}">&laquo;</a>
	$month $year 
	<a href="{$ibforums->base_url}act=calendar&amp;m={$next['month_id']}&amp;y={$next['year_id']}" title="{$next['month_name']} {$next['year_id']}">&raquo;</a>
</div>
<table cellspacing="0">
	<tr>
		<td width="25%" valign="top" class="nopad">
			<!--PREV.MONTH--><br />
			<!--THIS.MONTH--><br />
			<!--NEXT.MONTH--><br />
		</td>
		<td width="1%" class="nopad">&nbsp;</td>
		<td width="75%" valign="top" class="nopad">
			<div class="borderwrap">
				<div class="maintitle">{$ibforums->lang['table_title']}</div>
				<table cellspacing="1">
					<tr>
						<td width="2%" class="subtitle">&nbsp;</td>
						<!--IBF.DAYS_TITLE_ROW-->
						<!--IBF.DAYS_CONTENT-->
					</tr>
				</table>
			</div>
			<br />
		</td>
	</tr>
</table>
<form action="{$ibforums->base_url}act=calendar" method="post">
	<div class="borderwrap">
		<div class="barb">
			<p class="overs"><span class="fauxbutton"><a href="{$ibforums->base_url}act=calendar&amp;code=newevent">{$ibforums->lang['aa_add_new_event']}</a></span>&nbsp;<span class="fauxbutton"><a href="{$ibforums->base_url}act=calendar&amp;code=find&amp;what=thismonth">{$ibforums->lang['aa_cur_month']}</a></span>&nbsp;<span class="fauxbutton"><a href="{$ibforums->base_url}act=calendar&amp;code=find&amp;what=thisweek">{$ibforums->lang['aa_view_week']}</a></span></p>
			<p><select name="m"><!--IBF.MONTH_BOX--></select>&nbsp;
			   <select name="year"><!--IBF.YEAR_BOX--></select>&nbsp;
			   <input class="gobutton" type="image" src="{$ibforums->vars['img_url']}/login-button.gif" value="Go" /></p>
		</div>
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_new_row
//===========================================================================
function cal_new_row($week="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</tr>
<!-- NEW ROW-->
<tr>
	<td class="formsubtitle">
		<a href="{$ibforums->base_url}act=calendar&amp;code=showweek&amp;week=$week">&raquo;</a>
	</td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_page_events_end
//===========================================================================
function cal_page_events_end() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_page_events_start
//===========================================================================
function cal_page_events_start() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
	function deleteEvent(id) {
		if (confirm('{$ibforums->lang['js_del_1']}')) {
			 window.location.href = "{$ibforums->base_url}act=calendar&code=delete&e=" + id;
		 }
		 else {
			alert ('{$ibforums->lang['js_del_2']}');
		} 
	}
</script>
<div class="borderwrap">
	<div class="maintitle">{$ibforums->lang['cal_title_events']}</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_show_event
//===========================================================================
function cal_show_event($event="",$member="",$event_type="",$edit_button="",$type="",$date_ends="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="barc">
	<p class="over">$edit_button</p>
	<p><b>{$event['title']} ($event_type)</b></p>
</div>
<table cellspacing="1">
	<tr>
		<td class="row2" width="1%" valign="middle" nowrap="nowrap"><span class="normalname"><a href="{$ibforums->base_url}showuser={$member['id']}">{$member['name']}</a></span></td>
		<td class="row2" width="99%">
			<b>{$ibforums->lang['event_date']} {$event['mday']} {$event['month_text']} {$event['year']} $date_ends</b> ($type)
		</td>
	</tr>
	<tr>
		<td valign="top" class="row1" nowrap="nowrap">
			{$member['avatar']}<span class="postdetails"><br />{$ibforums->lang['group']} {$member['g_title']}<br />{$ibforums->lang['posts']} {$member['posts']}<br />{$ibforums->lang['joined']} {$member['joined']}</span>
		</td>
		<td valign="top" class="row1">
			<span class="postcolor">{$event['event_text']}</span>
		</td>
	</tr>
	<tr>
		<td class="formbuttonrow" colspan="2"><a href="{$ibforums->base_url}act=calendar&amp;d={$ibforums->input['d']}&amp;m={$ibforums->input['m']}&amp;y={$ibforums->input['y']}"><b>{$ibforums->lang['back']}</b></a></td>
	</tr>
	<tr>
		<td class="catend" colspan="2"><!-- no content --></td>
	</tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_week_content
//===========================================================================
function cal_week_content($date="",$month="",$year="",$prev="",$next="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="calmonths">
	<a href="{$ibforums->base_url}act=calendar&amp;code=showweek&amp;week={$prev['0']}" title="{$prev['mday']} {$prev['month']} {$prev['year']}">&laquo;</a>
	$date $month $year 
	<a href="{$ibforums->base_url}act=calendar&amp;code=showweek&amp;week={$next['0']}" title="{$next['mday']} {$next['month']} {$next['year']}">&raquo;</a>
</div>
<table cellspacing="0">
	<tr>
		<td width="25%" valign="top" class="nopad">
			<!--PREV.MONTH--><br />
			<!--THIS.MONTH--><br />
			<!--NEXT.MONTH--><br />
		</td>
		<td width="1%" class="nopad">&nbsp;</td>
		<td width="75%" valign="top" class="nopad">
			<div class="borderwrap">
				<table cellspacing="0">
					<!--IBF.DAYS_CONTENT-->
					</tr>
				</table>
			</div>
			<br />
		</td>
	</tr>
</table>
<form action="{$ibforums->base_url}act=calendar" method="post">
	<div class="borderwrap">
		<div class="barb">
			<p class="overs"><span class="fauxbutton"><a href="{$ibforums->base_url}act=calendar&amp;code=newevent">Add New Event</a></span>&nbsp;<span class="fauxbutton"><a href="{$ibforums->base_url}act=calendar&amp;code=find&amp;what=thismonth">View Current Month</a></span>&nbsp;<span class="fauxbutton"><a href="{$ibforums->base_url}act=calendar&amp;code=find&amp;what=thisweek">View Current Week</a></span></p>
			<p><select name="m"><!--IBF.MONTH_BOX--></select>&nbsp;<select name="y"><!--IBF.YEAR_BOX--></select>&nbsp;<input class="gobutton" type="image" src="{$ibforums->vars['img_url']}/login-button.gif" value="{$ibforums->lang['go']}" /></p>
		</div>
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_week_dayentry
//===========================================================================
function cal_week_dayentry($wday="",$date="",$month="",$mid="",$year="",$events="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
	<td class="nopad">
		<div class="bar">
			<p class="over"><a href="{$ibforums->base_url}act=calendar&amp;code=newevent&amp;nd={$year}-{$mid}-{$date}">{$ibforums->lang['post_new_event']}</a></p>
			<p><span class="weekday">$wday</span></p>
		</div>
	</td>
</tr>
<tr>
	<td class="nopad">
		<table cellspacing="0">
			<tr>
				<td width="5%" class="calweekday">$date</td>
				<td class="row2">$events</td>
			</tr>
		</table>
	</td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_week_events_wrap
//===========================================================================
function cal_week_events_wrap($link="",$text="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="divpad">
	<b><a href="{$ibforums->base_url}act=calendar&amp;$link">$text</a></b>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_week_events_wrap_range
//===========================================================================
function cal_week_events_wrap_range($link="",$text="",$ft="",$bg="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div style="background-color: $bg; color: $ft; padding: 3px; border: 1px outset $bg; width: 50%;'>
	<a href="{$ibforums->base_url}act=calendar&amp;$link" style="color: $ft;">$text</a>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// cal_week_monthbar
//===========================================================================
function cal_week_monthbar($month="",$year="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
	<td class="maintitle">$month $year</td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// calendar_admin_group_box
//===========================================================================
function calendar_admin_group_box($groups="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr> 
	<td class="pformleft">{$ibforums->lang['calendar_group_filter']}</td>
	<td class="pformright"><select name="e_groups[]" size="5" multiple>$groups</select></td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// calendar_choose_date
//===========================================================================
function calendar_choose_date($days="",$months="",$years="",$end_days="",$end_months="",$end_years="",$recur_days="",$recur_unit="",$div="",$checked="",$cols="",$recend="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr> 
	<td class="pformleft" valign="top"><b>{$ibforums->lang['calendar_event_date']}</b></td>
	<td class="pformright">
		<table cellspacing="0">
			<tr>
				<td>
					<input type="radio" name="eventtype" id="single" onclick="selecttype();" class="radiobutton" value="single" {$checked['normal']} />
					<b><label for="single">{$ibforums->lang['fv_single']}</label></b>
				</td>
				<td>
					<select name="e_day">
						$days
					</select>&nbsp;&nbsp;
					<select name="e_month">
						$months
					</select>&nbsp;&nbsp;
					<select name="e_year">
						$years
					</select>
				</td>
			</tr>
			<tr>
				<td>
					<input type="radio" name="eventtype" id="range" onclick="selecttype();" class="radiobutton" value="range"{$checked['range']} />
					<b><label for="range">{$ibforums->lang['fv_range']}</label></b>
				</td>
				<td>
					<div id="rangeshow" style="display: {$div['range_on']};">
						<table cellspacing="0">
							<tr>
								<td><b>{$ibforums->lang['fv_range_ends']}</b></td>
								<td>
									<select name="end_day">
										$end_days
									</select>&nbsp;&nbsp;
									<select name="end_month">
										$end_months
									</select>&nbsp;&nbsp;
									<select name="end_year">
										$end_years
									</select>
								</td>
							</tr>
							<tr>
								<td><b>{$ibforums->lang['fv_bgcolor']}</b></td>
								<td>
									{$cols['bg']} <input type="text" name="style" size="5" readonly="readonly" id="stylebg" />
								</td>
							</tr>
							<tr>
								<td><b>{$ibforums->lang['fv_font']}</b></td>
								<td>
									{$cols['ft']} <input type="text" name="style2" size="5" readonly="readonly" id="styleft" />
								</td>
							</tr>
						</table>
					</div>
					<div id="rangehide" style="display: {$div['range_off']};">{$ibforums->lang['fv_hidden']}</div>
				</td>
			</tr>
			<tr>
				<td>
					<input type="radio" name="eventtype" id="recur"  onclick="selecttype();" class="radiobutton" value="recur" {$checked['recur']} />
					<b><label for="recur">{$ibforums->lang['fv_recur']}</label></b>
				</td>
				<td>
					<div id="recurshow" style="display: {$div['recur_on']};">
						<b>{$ibforums->lang['fv_recur_every']}</b> 
						<select name="recur_unit">
							$recur_unit
						</select>
						<b>{$ibforums->lang['fv_until']}</b> 
						<select name="recend_day">
							{$recend['d']}
						</select>
						<select name="recend_month">
							{$recend['m']}
						</select>&nbsp;&nbsp;
						<select name="recend_year">
							{$recend['y']}
						</select>
					</div>
					<div id="recurhide" style="display: {$div['recur_off']};">{$ibforums->lang['fv_hidden']}</div>
				</td>
			</tr>
		</table>
	</td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// calendar_delete_box
//===========================================================================
function calendar_delete_box() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr> 
	<td class="row1" width="100%" colspan="2">
		<input type="checkbox" name="event_delete" value="1">&nbsp;{$ibforums->lang['calendar_delete_box']}
	</td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// calendar_end_form
//===========================================================================
function calendar_end_form($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
			<td class="formbuttonrow" colspan="2">
				<input type="submit" name="submit" value="$data" tabindex="4">
			</td>
		</tr>
	</table>
</div>
</form>
<br />
<br clear="all" />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// calendar_event_title
//===========================================================================
function calendar_event_title($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr> 
	<td class="pformleft"><b>{$ibforums->lang['calendar_title']}</b></td>
	<td class="pformright"><input type="text" size="40" maxlength="40" name="event_title" value="$data" /></td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// calendar_event_type
//===========================================================================
function calendar_event_type($pub_select="",$priv_select="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr> 
	<td class="pformleft"><b>{$ibforums->lang['calendar_event_type']}</b></td>
	<td class="pformright">
		<select name="e_type">
			<option value="public"$pub_select>{$ibforums->lang['calendar_type_public']}</option>
			<option value="private"$priv_select>{$ibforums->lang['calendar_type_private']}</option>
		</select>
	</td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// calendar_start_edit_form
//===========================================================================
function calendar_start_edit_form($eventid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form action="{$ibforums->base_url}act=calendar&amp;code=doedit&amp;eventid=$eventid" method="post" name="REPLIER" onsubmit="return ValidateForm()">
	<input type="hidden" name="removeattachid" value="" />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// calendar_start_form
//===========================================================================
function calendar_start_form() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form action="{$ibforums->base_url}act=calendar&amp;code=addnewevent" method="post" name="REPLIER" onSubmit="return ValidateForm()">
	<input type="hidden" name="removeattachid" value="" />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mini_cal_blank_cell
//===========================================================================
function mini_cal_blank_cell() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<td class="mcellblank"><!-- no content --></td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mini_cal_date_cell
//===========================================================================
function mini_cal_date_cell($month_day="",$events="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<td class="mcelldate">
	<div class="calday">$month_day</div>
</td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mini_cal_date_cell_today
//===========================================================================
function mini_cal_date_cell_today($month_day="",$events="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<td class="mcelltoday">
	<div class="calday">$month_day</div>
</td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mini_cal_day_bit
//===========================================================================
function mini_cal_day_bit($day="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<td width="14%" class="subtitle">$day</td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mini_cal_mini_wrap
//===========================================================================
function mini_cal_mini_wrap($month="",$mid="",$year="",$content="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="borderwrap">
	<div class="maintitle">
		<p class="goto"><a href="{$ibforums->base_url}act=calendar&amp;m={$mid}&amp;y=$year"><{CAL_GOTO}></a></p>
		<p>{$month} {$year}</p>
	</div>
	<table cellspacing="1">
		<tr>
			<td class="subtitle">&nbsp;</td>
			{$content}
		</tr>
	</table>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mini_cal_new_row
//===========================================================================
function mini_cal_new_row($week="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</tr>
	<!-- NEW ROW-->
<tr>
	<td class="formsubtitle">
		<a href="{$ibforums->base_url}act=calendar&amp;code=showweek&amp;week=$week">&raquo;</a>
	</td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// table_top
//===========================================================================
function table_top($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script language='Javascript' type='text/javascript'>
	<!--
	function PopUp(url, name, width,height,center,resize,scroll,posleft,postop) {
		if (posleft != 0) { x = posleft }
		if (postop  != 0) { y = postop  }
	
		if (!scroll) { scroll = 1 }
		if (!resize) { resize = 1 }
	
		if ((parseInt (navigator.appVersion) >= 4 ) && (center)) {
		  X = (screen.width  - width ) / 2;
		  Y = (screen.height - height) / 2;
		}
		if (scroll != 0) { scroll = 1 }
	
		var Win = window.open( url, name, 'width='+width+',height='+height+',top='+Y+',left='+X+',resizable='+resize+',scrollbars='+scroll+',location=no,directories=no,status=no,menubar=no,toolbar=no');
	 }
	function changeDiv(id, method)
	{
		var itm = null;
		if (document.getElementById) {
			itm = document.getElementById(id);
		} else if (document.all)     {
			itm = document.all[id];
		} else if (document.layers)   {
			itm = document.layers[id];
		}
		
		if (itm.style)
		{
			if ( method == 'show' )
			{
				itm.style.display = "";
			}
			else
			{
				itm.style.display = "none";
			}
		}
		else
		{
			itm.visibility = "show";
		}
	}
	
	function selecttype()
	{
		
		if ( document.REPLIER.eventtype[1].checked == true )
		{
			// Ranged date...
			
			changeDiv( 'rangeshow', 'show' );
			changeDiv( 'rangehide', 'none' );
			changeDiv( 'recurshow', 'none' );
			changeDiv( 'recurhide', 'show' );
		}
		else if ( document.REPLIER.eventtype[2].checked == true )
		{
			// Repeating event
			
			changeDiv( 'rangeshow', 'none' );
			changeDiv( 'rangehide', 'show' );
			changeDiv( 'recurshow', 'show' );
			changeDiv( 'recurhide', 'none' );
		}
		else
		{
			changeDiv( 'rangeshow', 'none' );
			changeDiv( 'rangehide', 'show' );
			changeDiv( 'recurshow', 'none' );
			changeDiv( 'recurhide', 'show' );
		}
	}
	
	function changeColour(BOXid, val)
	{
		document.all.BOXid.style.backgroundColor = val;
	}
	//-->
</script>
<div class="borderwrap">
<table cellspacing="0">
	<tr>
		<td class="maintitle" colspan="2">&nbsp;&nbsp;$data</td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>