<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 5                     */
/* CACHE FILE: Generated: Wed, 31 Aug 2005 00:22:51 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_subscriptions {

//===========================================================================
// do_authorizenet_normal_screen
//===========================================================================
function do_authorizenet_normal_screen($ccode="",$member_id="",$new_sub_id="",$to_pay="",$sub_title="",$desc_string="",$vendor_id="",$fp_hash="",$fp_seq="",$fp_time="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['sc_complete']}</div>
<p>
	{$ibforums->lang['sc_upgrade_explain']}<br /><br />
	$desc_string<br /><br /><b>{$ibforums->lang['gw_authorize']}</b>
</p>
<form method="POST" action="https://secure.authorize.net/gateway/transact.dll">
	<input type="hidden" name="x_login" value="$vendor_id" />
	<input type="hidden" name="x_relay_response" value="TRUE" />
	<input type="hidden" name="x_relay_url" value="{$ibforums->base_url}act=module&module=subscription&CODE=incoming&type=authorizenet" />
	<input type="hidden" name="x_amount" value="$to_pay" />
	<input type="hidden" name="x_currency_code" value="$ccode" />
	<input type="hidden" name="x_fp_hash" value="$fp_hash" />
	<input type="hidden" name="x_fp_timestamp" value="$fp_time" />
	<input type="hidden" name="x_fp_sequence" value="$fp_seq" />
	<input type="hidden" name="x_show_form" value="PAYMENT_FORM" />
	<input type="hidden" name="x_description" value="$sub_title" />
	<input type="hidden" name="x_cust_id" value="{$member_id}x{$new_sub_id}" />
	<input type="hidden" name="x_test_request" value="false" /><br /><br />
	<div>
		<input type="submit" name="b1" value="Continue..." />
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// do_manual_normal_screen
//===========================================================================
function do_manual_normal_screen($new_sub_id="",$desc_string="",$ccode="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
	function pop_ticket(){
		window.open('{$ibforums->js_base_url}act=module&module=subscription&type=manual&CODE=custom&mode=ticket&tickid=0&upgrade=0&sid=$new_sub_id&currency=$ccode','TICKET','width=250,height=350,resizable=yes,scrollbars=yes,toolbar=yes');
	}
-->
</script>
<div class="formsubtitle">{$ibforums->lang['sc_complete']}</div>
	<p>
		$desc_string<br /><br />
		{$ibforums->lang['post_manual']}<br /><br />
		{$ibforums->lang['post_manual_more']}
	</p>
	<br /><br />
	<div>
		<input type="button" value="{$ibforums->lang['gw_manual']}" onclick="pop_ticket()" />
	</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// do_manual_upgrade_screen
//===========================================================================
function do_manual_upgrade_screen($new_sub_id="",$cur_id="",$desc_string="",$ccode="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
function pop_ticket(){
	window.open('{$ibforums->js_base_url}act=module&module=subscription&type=manual&CODE=custom&mode=ticket&tickid={$cur_id}&upgrade=1&sid=$new_sub_id&currency=$ccode','TICKET','width=250,height=350,resizable=yes,scrollbars=yes,toolbar=yes');
}
-->
</script>
<div class="formsubtitle">{$ibforums->lang['sc_upgrade_title']}</div>
	<p>
		$desc_string<br /><br />
		{$ibforums->lang['post_manual']}<br /><br />
		{$ibforums->lang['post_manual_more']}
	</p>
	<br /><br />
	<div>
		<input type="button" value="{$ibforums->lang['gw_manual']}" onclick="pop_ticket()" />
	</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// do_nochex_normal_screen
//===========================================================================
function do_nochex_normal_screen($ccode="",$member_id="",$new_sub_id="",$to_pay="",$nochex_email="",$sub_title="",$desc_string="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['sc_complete']}</div>
<p>
	{$ibforums->lang['sc_upgrade_explain']}<br /><br />
	$desc_string<br /><br />
	<b>{$ibforums->lang['gw_nochex']}</b>
</p>
<form action="https://www.nochex.com/nochex.dll/checkout" method="post">
<input type="hidden" name="email" value="$nochex_email" />
<input type="hidden" name="amount" value="$to_pay" />
<input type="hidden" name="ordernumber" value="{$new_sub_id}x{$member_id}x0" />
<input type="hidden" name="returnurl" value="{$ibforums->base_url}act=module&module=subscription&CODE=paydone&type=nochex" />
<input type="hidden" name="responderurl" value="{$ibforums->base_url}act=module&module=subscription&CODE=incoming&type=nochex" />
	<br /><br />
	<div>
		<input type="image" src="http://www.nochex.com/web/images/payme4.gif" name="submit" alt="Pay with NOCHEX now" />
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// do_nochex_upgrade_screen
//===========================================================================
function do_nochex_upgrade_screen($ccode="",$member_id="",$new_sub_id="",$to_pay="",$nochex_email="",$sub_title="",$cur_tran_id="",$desc_string="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['sc_complete']}</div>
<p>
	{$ibforums->lang['sc_upgrade_explain']}<br /><br />
	$desc_string<br /><br /><b>{$ibforums->lang['gw_nochex']}</b>
</p>
<form action="https://www.nochex.com/nochex.dll/checkout" method="post">
<input type="hidden" name="email" value="$nochex_email" />
<input type="hidden" name="amount" value="$to_pay" />
<input type="hidden" name="ordernumber" value="{$new_sub_id}x{$member_id}x$cur_tran_id" />
<input type="hidden" name="returnurl" value="{$ibforums->base_url}act=module&module=subscription&CODE=paydone&type=nochex" />
<input type="hidden" name="responderurl" value="{$ibforums->base_url}act=module&module=subscription&CODE=incoming&type=nochex" />
	<br /><br />
	<div>
		<input type="image" src="http://www.nochex.com/web/images/payme4.gif" name="submit" alt="Pay with NOCHEX now" />
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// do_paypal_normal_recurring_screen
//===========================================================================
function do_paypal_normal_recurring_screen($ccode="",$member_id="",$new_sub_id="",$unit="",$length="",$cost="",$paypal_email="",$sub_title="",$desc_string="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['sc_complete']}</div>
<p>
	{$ibforums->lang['sc_upgrade_explain']}<br /><br />
	$desc_string<br /><br />
	<b>{$ibforums->lang['gw_paypal']}</b>
</p>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick-subscriptions" />
<input type="hidden" name="business" value="$paypal_email" />
<input type="hidden" name="item_name" value="$sub_title" />
<input type="hidden" name="item_number" value="$new_sub_id" />
<input type="hidden" name="no_shipping" value="1" />
<input type="hidden" name="src" value="1" />
<input type="hidden" name="a3" value="$cost" />
<input type="hidden" name="p3" value="$length" />
<input type="hidden" name="t3" value="$unit" />
<input type="hidden" name="custom" value="$member_id" />
<input type="hidden" name="notify_url" value="{$ibforums->base_url}act=module&module=subscription&CODE=incoming&type=paypal" />
<input type="hidden" name="currency_code" value="$ccode" />
<input type="hidden" name="return" value="{$ibforums->base_url}act=module&module=subscription&CODE=paydone&type=paypal" />
<input type="hidden" name="cancel_return" value="{$ibforums->base_url}act=module&module=subscription&CODE=paydone&type=paypal" />
	<br /><br />
	<div>
		<input type="image" src="https://www.paypal.com/images/x-click-but6.gif" name="submit" alt="Make payments with PayPal - it"s fast, free and secure!" />
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// do_paypal_normal_screen
//===========================================================================
function do_paypal_normal_screen($ccode="",$member_id="",$new_sub_id="",$to_pay="",$paypal_email="",$sub_title="",$desc_string="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['sc_complete']}</div>
<p>
	{$ibforums->lang['sc_upgrade_explain']}<br /><br />
	$desc_string<br /><br />
	<b>{$ibforums->lang['gw_paypal']}</b>
</p>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick" />
<input type="hidden" name="business" value="$paypal_email" />
<input type="hidden" name="amount" value="$to_pay" />
<input type="hidden" name="item_name" value="$sub_title" />
<input type="hidden" name="item_number" value="$new_sub_id" />
<input type="hidden" name="no_shipping" value="1" />
<input type="hidden" name="custom" value="$member_id" />
<input type="hidden" name="notify_url" value="{$ibforums->base_url}act=module&module=subscription&CODE=incoming&type=paypal" />
<input type="hidden" name="currency_code" value="$ccode" />
<input type="hidden" name="return" value="{$ibforums->base_url}act=module&module=subscription&CODE=paydone&type=paypal" />
<input type="hidden" name="cancel_return" value="{$ibforums->base_url}act=module&module=subscription&CODE=paydone&type=paypal" />
	<br /><br />
	<div>
		<input type="image" src="https://www.paypal.com/images/x-click-but6.gif" name="submit" alt="Make payments with PayPal - it"s fast, free and secure!" />
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// do_paypal_upgrade_recurring_screen
//===========================================================================
function do_paypal_upgrade_recurring_screen($ccode="",$member_id="",$new_sub_id="",$to_pay="",$time_left_to_run="",$time_left_unit="",$unit="",$length="",$cost="",$paypal_email="",$sub_title="",$cur_tran_id="",$desc_string="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['sc_complete']}</div>
<p>
	{$ibforums->lang['sc_upgrade_explain']}<br /><br />
	$desc_string<br /><br />
	<b>{$ibforums->lang['gw_paypal']}</b>
</p>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick-subscriptions" />
<input type="hidden" name="business" value="$paypal_email" />
<input type="hidden" name="item_name" value="$sub_title" />
<input type="hidden" name="item_number" value="$new_sub_id" />
<input type="hidden" name="no_shipping" value="1" />
<input type="hidden" name="src" value="1" />
<input type="hidden" name="a1" value="$to_pay" />
<input type="hidden" name="p1" value="$time_left_to_run" />
<input type="hidden" name="t1" value="$time_left_unit" />
<input type="hidden" name="a3" value="$cost" />
<input type="hidden" name="p3" value="$length" />
<input type="hidden" name="t3" value="$unit" />
<input type="hidden" name="invoice" value="{$cur_tran_id}x{$new_sub_id}x{$member_id}" />
<input type="hidden" name="custom" value="$member_id" />
<input type="hidden" name="memo" value="upgrade" />
<input type="hidden" name="notify_url" value="{$ibforums->base_url}act=module&module=subscription&CODE=incoming&type=paypal" />
<input type="hidden" name="currency_code" value="$ccode" />
<input type="hidden" name="return" value="{$ibforums->base_url}act=module&module=subscription&CODE=paydone&type=paypal" />
<input type="hidden" name="cancel_return" value="{$ibforums->base_url}act=module&module=subscription&CODE=paydone&type=paypal" />
	<br /><br />
	<div>
		<input type="image" src="https://www.paypal.com/images/x-click-but6.gif" name="submit" alt="Make payments with PayPal - it"s fast, free and secure!" />
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// do_paypal_upgrade_screen
//===========================================================================
function do_paypal_upgrade_screen($ccode="",$member_id="",$new_sub_id="",$to_pay="",$paypal_email="",$sub_title="",$cur_tran_id="",$desc_string="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['sc_complete']}</div>
<p>
	{$ibforums->lang['sc_upgrade_explain']}<br /><br />
	$desc_string<br /><br />
	<b>{$ibforums->lang['gw_paypal']}</b>
</p>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick" />
<input type="hidden" name="business" value="$paypal_email" />
<input type="hidden" name="amount" value="$to_pay" />
<input type="hidden" name="item_name" value="$sub_title" />
<input type="hidden" name="item_number" value="$new_sub_id" />
<input type="hidden" name="no_shipping" value="1" />
<input type="hidden" name="invoice" value="{$cur_tran_id}x{$new_sub_id}x{$member_id}" />
<input type="hidden" name="custom" value="$member_id" />
<input type="hidden" name="memo" value="upgrade" />
<input type="hidden" name="notify_url" value="{$ibforums->base_url}act=module&module=subscription&CODE=incoming&type=paypal" />
<input type="hidden" name="currency_code" value="$ccode" />
<input type="hidden" name="return" value="{$ibforums->base_url}act=module&module=subscription&CODE=paydone&type=paypal" />
<input type="hidden" name="cancel_return" value="{$ibforums->base_url}act=module&module=subscription&CODE=paydone&type=paypal" />
	<br /><br />
	<div>
		<input type="image" src="https://www.paypal.com/images/x-click-but6.gif" name="submit" alt="Make payments with PayPal - it"s fast, free and secure!" />
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// do_protx_normal_screen
//===========================================================================
function do_protx_normal_screen($crypt="",$protx_user="",$sub_title="",$desc_string="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['sc_complete']}</div>
<p>
	{$ibforums->lang['sc_upgrade_explain']}<br /><br />
	$desc_string<br /><br />
	<b>{$ibforums->lang['gw_protx']}</b>
</p>
<!--<form action="https://ukvpstest.protx.com/vps2form/submit.asp" method="post">-->
<form action="https://ukvps.protx.com/vps2form/submit.asp" method="post">
<input type="hidden" name="VPSProtocol" value="2.21" />
<input type="hidden" name="TxType" value="PAYMENT" />
<input type="hidden" name="Vendor" value="$protx_user" />
<input type="hidden" name="Crypt" value="$crypt" />
	<br /><br />
	<div>
		<input type="submit" value="Pay Using Protx" />
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// do_protx_upgrade_screen
//===========================================================================
function do_protx_upgrade_screen($crypt="",$protx_user="",$sub_title="",$desc_string="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['sc_complete']}</div>
<p>
	{$ibforums->lang['sc_upgrade_explain']}<br /><br />
	$desc_string<br /><br />
	<b>{$ibforums->lang['gw_protx']}</b>
</p>
<!--<form action="https://ukvpstest.protx.com/vps2form/submit.asp" method="post">-->
<form action="https://ukvps.protx.com/vps2form/submit.asp" method="post">
<input type="hidden" name="VPSProtocol" value="2.21" />
<input type="hidden" name="TxType" value="PAYMENT" />
<input type="hidden" name="Vendor" value="$protx_user" />
<input type="hidden" name="Crypt" value="$crypt" />
	<br /><br />
	<div>
		<input type="submit" value="Pay Using Protx" />
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// do_safshop_normal_screen
//===========================================================================
function do_safshop_normal_screen($ccode="",$member_id="",$new_sub_id="",$to_pay="",$nochex_email="",$sub_title="",$desc_string="",$vendor_id="",$product_id="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['sc_complete']}</div>
<p>
	{$ibforums->lang['sc_upgrade_explain']}<br /><br />
	$desc_string<br /><br />
	<b>{$ibforums->lang['gw_safshop']}</b>
</p>
<form method="POST" action="https://order.safshop.net/servicepayment.cgi">
<input type="hidden" name="vendorid" value="$vendor_id" />
<input type="hidden" name="productid" value="$product_id" />
<input type="hidden" name="buttonid" value="Buy" />
<input type="hidden" name="item1" value="$to_pay" />
<input type="hidden" name="myurl" value="{$ibforums->base_url}" />
<input type="hidden" name="act" value="module" />
<input type="hidden" name="module" value="subscription" />
<input type="hidden" name="CODE" value="incoming" />
<input type="hidden" name="type" value="safshop" />
<input type="hidden" name="ordernumber" value="{$member_id}x{$new_sub_id}" />
	<br /><br />
	<div>
		<input type="submit" name="b1" value="Purchase" />
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// show_ticket
//===========================================================================
function show_ticket($sub="",$id="",$paid="",$extra="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<h2>{$ibforums->lang['man_title']}</h2>
<table cellspacing="1" class="ticket">
	<tr>
		<td>
			<table cellspacing="1">
				<tr>
					<td width="50%" bgcolor="#FFFFFF">{$ibforums->lang['man_mem']}</td>
					<td width="50%" bgcolor="#FFFFFF">{$ibforums->member['name']}</td>
				</tr>
				<tr>
					<td width="50%" bgcolor="#FFFFFF">{$ibforums->lang['man_mem_id']}</td>
					<td width="50%" bgcolor="#FFFFFF">{$ibforums->member['id']}</td>
				</tr>
				<tr>
					<td width="50%" bgcolor="#FFFFFF">{$ibforums->lang['man_email']}</td>
					<td width="50%" bgcolor="#FFFFFF">{$ibforums->member['email']}</td>
				</tr>
				<tr>
					<td width="50%" bgcolor="#FFFFFF">{$ibforums->lang['man_trans_id']}</td>
					<td width="50%" bgcolor="#FFFFFF">{$id}</td>
				</tr>
				<tr>
					<td width="50%" bgcolor="#FFFFFF">{$ibforums->lang['man_sub']}</td>
					<td width="50%" bgcolor="#FFFFFF">{$sub['sub_title']} $extra</td>
				</tr>
				<tr>
					<td width="50%" bgcolor="#FFFFFFF">{$ibforums->lang['man_pay']}</td>
					<td width="50%" bgcolor="#FFFFFF">{$paid}</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_choose_current_bottom
//===========================================================================
function sub_choose_current_bottom() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</table>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_choose_current_row
//===========================================================================
function sub_choose_current_row($id="",$name="",$start="",$end="",$paid="",$state="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
			<td class="row3" align="center">$id</td>
			<td class="row3"><b>$name</b></td>
			<td class="row3" align="center">$start</td>
			<td class="row3" align="center">$end</td>
			<td class="row3" align="center">{$paid}</td>
			<td class="row3" align="center">$state</td>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_choose_current_top
//===========================================================================
function sub_choose_current_top() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['s_current_subs']}</div>
<p>{$ibforums->lang['s_current_explain']}</p>             
<div class="borderwrapm">
	<table cellspacing="1">
		<tr>
			<th width="5%" align="center">{$ibforums->lang['s_transid']}</th>
			<th width="35%">{$ibforums->lang['s_detail']}</th>
			<th width="20%" align="center">{$ibforums->lang['s_started']}</th>
			<th width="20%" align="center">{$ibforums->lang['s_end']}</th>
			<th width="10%" align="center">{$ibforums->lang['s_paid']}</th>
			<th width="10%" align="center">{$ibforums->lang['s_status']}</th>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_choose_dead_bottom
//===========================================================================
function sub_choose_dead_bottom() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</table>
</div>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_choose_dead_row
//===========================================================================
function sub_choose_dead_row($id="",$name="",$start="",$end="",$paid="",$state="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
			<td class="row3" align="center">$id</td>
			<td class="row3"><b>$name</b></td>
			<td class="row3" align="center">$start</td>
			<td class="row3" align="center">$end</td>
			<td class="row3" align="center">{$paid}</td>
			<td class="row3" align="center">$state</td>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_choose_dead_top
//===========================================================================
function sub_choose_dead_top() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['s_dead_subs']}</div>
<p>{$ibforums->lang['s_dead_explain']}</p>             
<div class="borderwrapm">
	<table cellspacing="1">
		<tr>
			<th width="5%" align="center">{$ibforums->lang['s_transid']}</th>
			<th width="35%">{$ibforums->lang['s_detail']}</th>
			<th width="20%" align="center">{$ibforums->lang['s_started']}</th>
			<th width="20%" align="center">{$ibforums->lang['s_end']}</th>
			<th width="10%" align="center">{$ibforums->lang['s_paid']}</th>
			<th width="10%" align="center">{$ibforums->lang['s_status']}</th>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_choose_new_bottom
//===========================================================================
function sub_choose_new_bottom() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</table>
</div>
<div class="borderwrapm">
	<div class="formsubtitle" align="center"><input type="submit" value="{$ibforums->lang['s_continue_button']}" /></div>
</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_choose_new_row
//===========================================================================
function sub_choose_new_row($id="",$name="",$desc="",$cost="",$duration="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
			<td class="row3" align="center"><input type="radio" name="sub" value="$id" /></td>
			<td class="row3"><b>$name</b><br /><i>$desc</i></td>
			<td class="row3" align="center">$duration</td>
			<td class="row3" align="center">{$cost}</td>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_choose_new_top
//===========================================================================
function sub_choose_new_top($currency="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['s_available_subs']}</div>
<p>{$ibforums->lang['s_explain']}</p>
<br />
<form action="{$ibforums->base_url}act=module&amp;module=subscription&amp;nocp={$ibforums->input['nocp']}&amp;CODE=paymentmethod&amp;currency=$currency" method="post">             
	<div class="borderwrapm">
		<table cellspacing="1">
			<tr>
				<th width="5%">&nbsp;</th>
				<th width="55%">{$ibforums->lang['s_detail']}</th>
				<th width="20%" align="center">{$ibforums->lang['s_duration']}</th>
				<th width="20%" align="center">{$ibforums->lang['s_cost']}</th>
			</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_choose_upgrade_bottom
//===========================================================================
function sub_choose_upgrade_bottom() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</table>
</div>
<div class="borderwrapm">
	<div class="formsubtitle" align="center"><input type="submit" value="{$ibforums->lang['s_continue_button']}" /></div>
</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_choose_upgrade_row
//===========================================================================
function sub_choose_upgrade_row($id="",$name="",$desc="",$cost="",$duration="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
				<td class="row3" align="center"><input type="radio" name="sub" value="$id" /></td>
				<td class="row3"><b>$name</b><br /><i>$desc</i></td>
				<td class="row3" align="center">$duration</td>
				<td class="row3" align="center">{$cost}</td>
			</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_choose_upgrade_top
//===========================================================================
function sub_choose_upgrade_top($cur_id="",$currency="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br />
<div class="formsubtitle">{$ibforums->lang['s_upgrade_subs']}</div>
<p>{$ibforums->lang['s_upgrade_explain']}</p>
<br /> 
<form action="{$ibforums->base_url}act=module&amp;module=subscription&amp;nocp={$ibforums->input['nocp']}&amp;upgrade=1&amp;CODE=paymentmethod&amp;curid=$cur_id&amp;currency=$currency" method="post">             
	<div class="borderwrapm">
		<table cellspacing="1">
			<tr>
				<th width="5%">&nbsp;</th>
				<th width="55%">{$ibforums->lang['s_detail']}</th>
				<th width="20%" align="center">{$ibforums->lang['s_end']}</th>
				<th width="20%" align="center">{$ibforums->lang['s_balance_cost']}</th>
			</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_currency_change_bottom
//===========================================================================
function sub_currency_change_bottom() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</select>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_currency_change_form
//===========================================================================
function sub_currency_change_form($select="",$url="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div align="right">
	<form action="$url" method="post">
		{$ibforums->lang['cc_currency_in']} $select 
		<input type="submit" value="{$ibforums->lang['cc_change']}" />
	</form>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_currency_change_row
//===========================================================================
function sub_currency_change_row($id="",$name="",$default="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<option value="$id" $default>$id $name</option>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_currency_change_top
//===========================================================================
function sub_currency_change_top() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<select name="currency">
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_msg_force
//===========================================================================
function sub_msg_force() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="borderwrapm">
	<div class="row1">
		<b>{$ibforums->lang['msg_force_title']}</b><br /><br />
		{$ibforums->lang['msg_force_text']}
EOF;
//startif
if ( $ibforums->input['CODE'] == "paymentmethod" )
{
$IPBHTML .= <<<EOF
<br /><br />
		<div>
			<input type="button" class="button" value="&lt; &lt; Choose Another Package" onclick="locationjump('automodule=subscription&nocp=1&msgtype=general');" />
		</div>
EOF;
}//endif
$IPBHTML .= <<<EOF
		</div>
	</div>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_msg_fromreg
//===========================================================================
function sub_msg_fromreg() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="borderwrapm">
	<div class="row1">
		<b>{$ibforums->lang['msg_reg_title']}</b><br /><br />
		{$ibforums->lang['msg_reg_text']}
			<br /><br />
		<div>
			<input type="button" class="button" value="&lt; &lt; Choose Another Package" onclick="locationjump('automodule=subscription&nocp=1&msgtype=general');" />
EOF;
//startif
if ( $ibforums->vars['subsm_enforce'] != 1 )
{
$IPBHTML .= <<<EOF
&nbsp; &nbsp;<input type="button" class="button" value="Cancel Purchase & View Forums &gt; &gt;" onclick="locationjump('automodule=subscription&nocp=1&CODE=cancelfromreg');" />
EOF;
}//endif
$IPBHTML .= <<<EOF
		</div>
	</div>
</div>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_msg_general
//===========================================================================
function sub_msg_general() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="borderwrapm">
	<div class="row1">
		<b>{$ibforums->lang['msg_gen_title']}</b><br /><br />
		{$ibforums->lang['msg_gen_text']}<br /><br />
		<div>
EOF;
//startif
if ( $ibforums->vars['subsm_enforce'] != 1 )
{
$IPBHTML .= <<<EOF
&nbsp; &nbsp;<input type="button" class="button" value="Cancel Purchase & View Forums &gt; &gt;" onclick="locationjump('automodule=subscription&nocp=1&CODE=cancelfromreg');" />
EOF;
}//endif
$IPBHTML .= <<<EOF
		</div>
	</div>
</div>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_no_cp_end
//===========================================================================
function sub_no_cp_end() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</div>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_no_cp_start
//===========================================================================
function sub_no_cp_start() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<!--{MSG}-->
<div class="borderwrapm">
	<div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_page_bottom
//===========================================================================
function sub_page_bottom() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<p>{$ibforums->lang['s_current_bottom']}</p>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_two_methods_bottom
//===========================================================================
function sub_two_methods_bottom() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</table>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_two_methods_continue_button
//===========================================================================
function sub_two_methods_continue_button() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br />
<div class="borderwrapm">
	<div class="formsubtitle" align="center"><input type="submit" value="{$ibforums->lang['s_continue_button2']}" /></div>
</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_two_methods_row
//===========================================================================
function sub_two_methods_row($mid="",$name="",$desc="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
			<td class="row3" align="center"><input type="radio" name="methodid" value="$mid" /></td>
			<td class="row3"><b>$name</b><br /><i>$desc</i></td>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_two_methods_top
//===========================================================================
function sub_two_methods_top($sub_chosen="",$upgrade="",$curid="",$currency="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['sc_available_methods']}</div>
<form action="{$ibforums->base_url}act=module&amp;module=subscription&amp;nocp={$ibforums->input['nocp']}&amp;upgrade=$upgrade&amp;CODE=paymentscreen&amp;curid=$curid&amp;sub=$sub_chosen&amp;currency=$currency" method="post">             
	<div class="borderwrapm">
		<table cellspacing="1">
			<tr>
				<th width="5%" align="center">&nbsp;</th>
				<th width="95%">{$ibforums->lang['sc_method']}</th>
			</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_two_normal_summary
//===========================================================================
function sub_two_normal_summary() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['sc_normal_title']}</div>
	<p>{$ibforums->lang['sc_upgrade_explain']}<br /><br />
		{$ibforums->lang['sc_normal_string']}
	</p>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// sub_two_upgrade_summary
//===========================================================================
function sub_two_upgrade_summary() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['sc_upgrade_title']}</div>
	<p>{$ibforums->lang['sc_upgrade_explain']}<br /><br />
		{$ibforums->lang['sc_upgrade_string']}
	</p>
EOF;

//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>