<?php
$string['install']="Setup";
$string['lang_select']="Please, select your language:";
$string['license']="<b>License Agreement</b>";
$string['license_agree']="<b>By proceed you agree at this License Agreement</b>";
$string['license_ok']="I AGREE";
$string['license_no']="I DON'T AGREE";
$string['next']="Next ->";
$string['end']=">> End <<";
$string['step_1_1']="Now, the necessary tables will be create.";
$string['step_1_2']="<b>WARNING</b>: if the tables already exist will be deleted.";
$string['step_3_1']="Insert Password :";
$string['step_3_2']="Re-Type Password :";
$string['step_4_1']="<b>WARNING</b>: Remember to delete <b>setup.php</b> and related dir <b>setup_files</b>.";
$string['step_4_2']="<b>NOTE</b>: in your HTML pages you can insert the follow script:";
$string['step_4_3']="<b>NOTE</b>: in your PHP pages you can insert the follow script:";
$string['step_4_4']="For problems and questions use our <a href=\"http://www.php-stats.com/forum/\" target=\"_blank\">discussion board</a>. (italian or english language please)";
$string['box_title']="Warning:";
$string['done']="Tables are succesfully created.";
// ERROR HANDLING
$error['error_updating']="<b>WARNING: CRITICAL ERROR</b><br><br>You can annotate the possible errors and bring them on the support forum at : <a href=\"http://www.php-stats.com/forum/\" target=\"_BLANK\">http://www.php-stats.com/forum/</a><br><br><b>Setup is halted.</b>";
$error['locked']="Php-Stats seems to be already installed, setup is halted.<br><br>In order to re-install php-stats, please delete file <b>php-stats.lock</b>";						  
$error['error_config']="Php-Stats can't create config file, setup is halted.<br><br>In order to re-install php-stats, please delete file <b>php-stats.lock</b>"; 
$error['nowrite_server']="<b>WARNING:</b> It's impossible to write files on your server.<br>Set 777 permits to option folder<br>Otherwise, before to continue <b>you must replace</b> the files:<br><b>php-stats.php, php-stats.recphp.php, php-stats.recjs.php and admin.php</b><br>with the same in <b>files_noWrite</b> folder<br>"; 
?>
