<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 31 Aug 2005 00:22:42 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_search {

//===========================================================================
// boolean_explain_link
//===========================================================================
function boolean_explain_link() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
&#091; <a href="#" title="{$ibforums->lang['be_ttip']}" onclick="win_pop()">{$ibforums->lang['be_link']}</a> &#093;
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// boolean_explain_page
//===========================================================================
function boolean_explain_page() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="borderwrap">
	<div class="maintitle"><{CAT_IMG}>&nbsp;{$ibforums->lang['be_link']}</div>
	<table cellspacing="1">
		<tr>
			<th width="30%" class="formsubtitle">{$ibforums->lang['be_use']}</th>
			<th width="70%" class="formsubtitle">{$ibforums->lang['be_means']}</th>
		</tr>
		<tr>
			<td class="pformleft">{$ibforums->lang['be_u1']}</td>
			<td class="pformleft">{$ibforums->lang['be_m1']}</td>
		</tr>
		<tr>
			<td class="pformleft">{$ibforums->lang['be_u2']}</td>
			<td class="pformleft">{$ibforums->lang['be_m2']}</td>
		</tr>
		<tr>
			<td class="pformleft">{$ibforums->lang['be_u3']}</td>
			<td class="pformleft">{$ibforums->lang['be_m3']}</td>
		</tr>
		<tr>
			<td class="pformleft">{$ibforums->lang['be_u4']}</td>
			<td class="pformleft">{$ibforums->lang['be_m4']}</td>
		</tr>
		<tr>
			<td class="pformleft">{$ibforums->lang['be_u5']}</td>
			<td class="pformleft">{$ibforums->lang['be_m5']}</td>
		</tr>
		<tr>
			<td class="catend" colspan="2"><!-- no content --></td>
		</tr>
	</table>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// end_results_table
//===========================================================================
function end_results_table($data="",$as_post="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<!-- END RESULTS TABLE -->
EOF;
//startif
if ( $as_post != 1 )
{
$IPBHTML .= <<<EOF
<tr>
	<td class="formbuttonrow" colspan="8" style="text-align: right;">
	<form action="{$ibforums->base_url}act=search&CODE=getnew&active=1" method="post">
		{$ibforums->lang['active_start']}&nbsp;
		<select class="dropdown" name="lastdate">
			<option value="86400">{$ibforums->lang['active_today']}</option>
			<option value="604800">{$ibforums->lang['active_week']}</option>
			<option value="1209600">{$ibforums->lang['active_week2']}</option>
			<option value="2419200">{$ibforums->lang['active_month']}</option>
			<option value="7257600">{$ibforums->lang['active_month3']}</option>
			<option value="31449600">{$ibforums->lang['active_year']}</option>
		</select>
		<input type="submit" value="{$ibforums->lang['active_go']}" class="button" /></form></td>
</tr><tr>
	<td class="catend" colspan="8"><!-- no content --></td>
</tr>
</table>
</div>
EOF;
}//endif
$IPBHTML .= <<<EOF
<br />
<div>{$data[SHOW_PAGES]}</div>
<br />
<div class="borderwrap">
	<table cellspacing="0">
		<tr>
			<td width="5%" class="row2" nowrap="nowrap"><{B_NEW}>&nbsp;&nbsp;{$ibforums->lang['pm_open_new']}<br /><{B_NORM}>&nbsp;&nbsp;{$ibforums->lang['pm_open_no']}<br /><{B_HOT}>&nbsp;&nbsp;{$ibforums->lang['pm_hot_new']}<br /><{B_HOT_NN}>&nbsp;&nbsp;{$ibforums->lang['pm_hot_no']}</td>
			<td width="5%" class="row2" nowrap="nowrap"><{B_POLL}>&nbsp;&nbsp;{$ibforums->lang['pm_poll']}<br /><{B_POLL_NN}>&nbsp;&nbsp;{$ibforums->lang['pm_poll_no']}<br /><{B_LOCKED}>&nbsp;&nbsp;{$ibforums->lang['pm_locked']}<br /><{B_MOVED}>&nbsp;&nbsp;{$ibforums->lang['pm_moved']}</td>
			<td align="right" width="90%" class="row2">{$ibforums->forum_jump}</td>
		</tr>
	</table>
</div>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// Form
//===========================================================================
function Form($forums="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
	function go_gadget_simple(){
		window.location = "{$ibforums->js_base_url}act=Search&mode=simple&f={$ibforums->input['f']}";
	}
	
	function win_pop(){
		window.open("{$ibforums->js_base_url}act=Search&CODE=explain","WIN","width=400,height=300,resizable=yes,scrollbars=yes"); 
	}
-->
</script>
<form action="{$ibforums->base_url}act=Search&amp;CODE=01" method="post" name="sForm">
$hidden_fields
<div class="borderwrap">
	<table cellspacing="0">
		<tr>
			<td colspan="2" class="maintitle"  align="center">{$ibforums->lang['keywords_title']}</td>
		</tr>
		<tr>
			<td class="formsubtitle" width="50%">{$ibforums->lang['key_search']}</td>
			<td class="formsubtitle" width="50%">{$ibforums->lang['mem_search']}</td>
		</tr>
		<tr>
			<td class="row1" valign="top">
				<input type="text" maxlength="100" size="40" name="keywords" id="keywords" />
				<br /><br />
				<label for="keywords">{$ibforums->lang['keysearch_text']}</label> <!--IBF.BOOLEAN_EXPLAIN-->
			</td>
			<td class="row1" valign="top">
				<table cellspacing="0">
					<tr>
						<td><input type="text" maxlength="100" size="50" name="namesearch" /></td>
					</tr>
					<tr>
						<td width="40%"><input type="checkbox" name="exactname" id="matchexact" value="1" class="checkbox" /><label for="matchexact">{$ibforums->lang['match_name_ex']}</label></td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</div>
<br />
<div class="borderwrap">
	<table cellspacing="0">         
		<tr>
			<td colspan="2" class="maintitle"  align="center">{$ibforums->lang['search_options']}</td>
		</tr>
		<tr>
			<td class="formsubtitle" width="50%" valign="middle">{$ibforums->lang['search_where']}</td>
			<td class="formsubtitle" width="50%" valign="middle">{$ibforums->lang['search_refine']}</td>
		</tr>
		<tr>
			<td class="row1" valign="middle">
				$forums
				<br />
				<input type="checkbox" name="searchsubs" value="1" id="searchsubs" checked="checked" />&nbsp;<label for="searchsubs">{$ibforums->lang['search_in_subs']}</label>
			</td>
			<td class="row1" valign="top">
				<table cellspacing="1">
					<tr>
						<td valign="top">
							<fieldset class="search">
							<legend><b>{$ibforums->lang['search_from']}</b></legend>
								<select name="prune">
									<option value="1">{$ibforums->lang['today']}</option>
									<option value="7">{$ibforums->lang['this_week']}</option>
									<option value="30">{$ibforums->lang['this_month']}</option>
									<option value="60">{$ibforums->lang['this_60']}</option>
									<option value="90">{$ibforums->lang['this_90']}</option>
									<option value="180">{$ibforums->lang['this_180']}</option>
									<option value="365">{$ibforums->lang['this_year']}</option>
									<option value="0" selected="selected">{$ibforums->lang['ever']}</option>
								</select><br />
								<input type="radio" name="prune_type" id="prune_older" value="older" class="radiobutton" />&nbsp;<label for="prune_older">{$ibforums->lang['older']}</label><br />
								<input type="radio" name="prune_type" id="prune_newer" value="newer" class="radiobutton" checked="checked" />&nbsp;<label for="prune_newer">{$ibforums->lang['newer']}</label>
							</fieldset>
						</td>
						<td valign="top">
							<fieldset class="search">
								<legend><b>{$ibforums->lang['sort_results']}</b></legend>
									<select name="sort_key">
										<option value="last_post">{$ibforums->lang['last_date']}</option>
										<option value="posts">{$ibforums->lang['number_topics']}</option>
										<option value="starter_name">{$ibforums->lang['poster_name']}</option>
										<option value="forum_id">{$ibforums->lang['forum_name']}</option>
									</select><br />
									<input type="radio" name="sort_order" id="sort_desc" class="radiobutton" value="desc" checked="checked" /><label for="sort_desc">{$ibforums->lang['descending']}</label><br />
									<input type="radio" name="sort_order" id="sort_asc" class="radiobutton" value="asc" /><label for="sort_asc">{$ibforums->lang['ascending']}</label>
								</fieldset>
							</td>
						</tr>
						<tr>
							<td nowrap="nowrap">
								<fieldset class="search">
								<legend><b>{$ibforums->lang['search_where']}</b></legend>
									<input type="radio" name="search_in" class="radiobutton" id="search_in_posts" value="posts" checked="checked" /><label for="search_in_posts">{$ibforums->lang['in_posts']}</label><br />
									<input type="radio" name="search_in" class="radiobutton" id="search_in_titles" value="titles" /><label for="search_in_titles">{$ibforums->lang['in_topics']}</label>
								</fieldset>
							</td>
							<td>
								<fieldset class="search">
								<legend><b>{$ibforums->lang['result_type']}</b></legend>
									<input type="radio" name="result_type" class="radiobutton" value="topics" id="result_topics" checked="checked" /><label for="result_topics">{$ibforums->lang['results_topics']}</label><br />
									<input type="radio" name="result_type" class="radiobutton" value="posts" id="result_posts" /><label for="result_posts">{$ibforums->lang['results_post']}</label>
								</fieldset>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td class="formsubtitle" colspan="2" align="center"><input type="submit" value="{$ibforums->lang['do_search']}" /><!--IBF.SIMPLE_BUTTON--></td>
			</tr>
		</table>
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// form_simple_button
//===========================================================================
function form_simple_button() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
&nbsp;<input type="button" value="{$ibforums->lang['so_less_opts']}" onclick="go_gadget_simple()" />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// no_results_row
//===========================================================================
function no_results_row() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<!-- Begin Topic Entry {$data['tid']} -->
	<tr>
		<td align="center" colspan="8" class="row1"><b>{$ibforums->lang['no_search_topics']}</b></td>
	</tr>
    <!-- End Topic Entry {$data['tid']} -->
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// RenderPostRow
//===========================================================================
function RenderPostRow($data="",$author="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br />
<div class="borderwrap">
	<div class="maintitle">{$data['prefix']} <a href="{$ibforums->base_url}showtopic={$data['tid']}&amp;hl={$data['keywords']}">{$data['topic_title']}</a></div>
	<table cellspacing="1">
		<tr>
			<td width="150" class="row2"><span class="normalname">{$data['author_name']}</span></td>
			<td class="row2" width="100%"><b>{$ibforums->lang['rp_postedon']} {$data['post_date']}</b></td>
		</tr>
		<tr>
			<td class="post1" valign='top'>
				<span class="postdetails">
					{$author['avatar']}<br /><br />
					{$author['title']}<br />
					{$author['member_rank_img']}<br /><br />
					{$author['member_group']}<br />
					{$author['member_posts']}<br />
					{$author['member_joined']}<br />
					{$author['member_location']}
					{$author['member_number']}<br /><br />
				
					{$author['warn_text']} {$author['warn_minus']}{$author['warn_img']}{$author['warn_add']}
				</span><br />
        		<!--$ author[field_1]-->
        		<img src="{$ibforums->vars['img_url']}/spacer.gif" alt="" width="160" height="1" />
        	</td>
        	<td class="post1" width="100%"><div class="postcolor" style='height:200px;overflow:auto'>{$data['post']}</div></td>
        </tr>
        <tr>
        	<td class="row2">&nbsp;</td>
        	<td class="row2">
        		{$ibforums->lang['rp_forum']} <a href="{$ibforums->base_url}showforum={$data['forum_id']}">{$data['forum_name']}</a>
        		&middot; {$ibforums->lang['rp_post']} <a href="{$ibforums->base_url}act=ST&amp;f={$data['forum_id']}&amp;t={$data['tid']}&amp;hl={$data['keywords']}&amp;view=findpost&amp;p={$data['pid']}" class="linkthru">#{$data['pid']}</a>
        		&middot; {$ibforums->lang['rp_replies']} <b>{$data['topic_posts']}</b>
        		&middot; {$ibforums->lang['rp_hits']} <b>{$data['views']}
        	</td>
  		</tr>
  	</table>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// RenderRow
//===========================================================================
function RenderRow($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<!-- Begin Topic Entry {$data['tid']} -->
	<tr>
		<td align="center" class="row2">{$data['folder_img']}</td>
		<td align="center" width="3%" class="row1">{$data['topic_icon']}</td>
		<td class="row2">
			<table cellspacing="0">
				<tr>
EOF;
//startif
if ( $data['go_new_post'] != '' )
{
$IPBHTML .= <<<EOF
<td valign="middle">{$data['go_new_post']}</td>
EOF;
}//endif
$IPBHTML .= <<<EOF
					<td width="100%">{$data['prefix']} <a href="{$ibforums->base_url}showtopic={$data['tid']}&amp;hl={$data['keywords']}">{$data['title']}</a>  {$data[PAGES]}</td>
				</tr>
			</table>
			<span class="desc">{$data['description']}</span>
		</td>
		<td class="row2" width="15%"><span class="forumdesc"><a href="{$ibforums->base_url}showforum={$data['forum_id']}" title="{$data['forum_full_name']}">{$data['forum_name']}</a></span></td>
		<td align="center" class="row1">{$data['starter']}</td>
		<td align="center" class="row2">{$data['posts']}</td>
		<td align="center" class="row1">{$data['views']}</td>
		<td class="row1"><span class="desc">{$data['last_post']}<br /><a href="{$ibforums->base_url}showtopic={$data['tid']}&amp;view=getlastpost">{$data['last_text']}</a> <b>{$data['last_poster']}</b></span></td>
	</tr>
<!-- End Topic Entry {$data['tid']} -->
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// result_simple_header
//===========================================================================
function result_simple_header($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="plainborder">
	<div class="maintitle"><{CAT_IMG}>&nbsp;{$ibforums->lang['search_results']}</div>
	<div class="formsubtitle">
		<div class="pagelinks">{$ibforums->lang['g_searched_for']} <b>{$data['keyword']}</b></div>
		<div align="right">
			{$ibforums->lang['g_results']} <b>{$data['start']} - {$data['end']}</b> {$ibforums->lang['g_of_about']} <b>{$data['matches']}</b>.
			{$ibforums->lang['g_search_took']} <b>{$data['ex_time']}</b> {$ibforums->lang['g_seconds']}
		</div>
	</div>
</div>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// search_error_page
//===========================================================================
function search_error_page($keywords="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="borderwrap">
	<div class="maintitle"><{CAT_IMG}>&nbsp;{$ibforums->lang['search_results']}</div>
	<table cellspacing="1">
		<tr>
			<th><b>{$ibforums->lang['you_search_for']}</b> {$keywords}</th>
		</tr>
		<tr>
			<td class="row1">{$ibforums->lang['no_results_so_there_ha_ha']}<br /><br /><b><a href="{$ibforums->base_url}act=search">{$ibforums->lang['search_again']}</a></b></td>
		</tr>
		<tr>
			<td class="catend"><!-- no content --></td>
		</tr>
	</table>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// simple_form
//===========================================================================
function simple_form($forums="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
function go_gadget_advanced(){
	window.location = "{$ibforums->js_base_url}act=Search&mode=adv&f={$ibforums->input['f']}";
}
function win_pop(){
	window.open("{$ibforums->js_base_url}act=Search&CODE=explain","WIN","width=400,height=300,resizable=yes,scrollbars=yes"); 
}
-->
</script>
<form action="{$ibforums->base_url}act=Search&amp;CODE=simpleresults&amp;mode=simple" method="post" name="sForm">
$hidden_fields
	<div class="borderwrap">
		<div class="maintitle"  align="center">{$ibforums->lang['search_options']}</div>
		<div class="formsubtitle" align="center">{$ibforums->lang['key_search']}</div>
		<div class="tablepad" align="center">
			<input type="text" maxlength="100" size="40" id="keywords" name="keywords" /><br />
			<label for="keywords">{$ibforums->lang['keysearch_text']}</label> <!--IBF.BOOLEAN_EXPLAIN-->
		</div>
		<div class="formsubtitle" align="center">{$ibforums->lang['search_where']}</div>
		<div class="tablepad" align="center">
			{$forums}<br /><br />
			<b>{$ibforums->lang['sf_show_me']}</b>
			<input type="radio" name="sortby" value="relevant" id="sortby_one" class="radiobutton" />
			<label for="sortby_one">{$ibforums->lang['sf_most_r_f']}</label>&nbsp;
			<input type="radio" name="sortby" value="date" id="sortby_two" checked="checked" class="radiobutton" />
			<label for="sortby_two">{$ibforums->lang['sf_most_date']}</label>
		</div>
		<div class="formsubtitle" align="center">
			<input type="submit" value="{$ibforums->lang['do_search']}" />&nbsp;
			<input type="button" value="{$ibforums->lang['so_more_opts']}" onclick="go_gadget_advanced()" />
		</div>
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// start
//===========================================================================
function start($data="",$extra="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript" src="jscripts/ipb_forum.js"></script>
<div>{$data[SHOW_PAGES]} $extra</div>
<br />
<div class="borderwrap">
	<div class="maintitle">
		<div style="float: left;"><{CAT_IMG}>&nbsp;{$ibforums->lang['your_results']}</div>
		<div align="right"><a href="{$ibforums->base_url}act=Login&amp;CODE=05">{$ibforums->lang['mark_search_as_read']}</a></div>
	</div>
	<table cellspacing="1">
		<tr>
			<th colspan="2">&nbsp;</th>
			<th>{$ibforums->lang['h_topic_title']}</th>
			<th align="center">{$ibforums->lang['h_forum_name']}</th>
			<th align="center">{$ibforums->lang['h_topic_starter']}</th>
			<th align="center">{$ibforums->lang['h_replies']}</th>
			<th align="center">{$ibforums->lang['h_hits']}</th>
			<th>{$ibforums->lang['h_last_action']}</th>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// start_as_post
//===========================================================================
function start_as_post($data="",$extra="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div>{$data[SHOW_PAGES]} $extra</div>
EOF;

//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>