<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 31 Aug 2005 00:22:42 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_ucp {

//===========================================================================
// attachments_row
//===========================================================================
function attachments_row($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr id="{$data['attach_id']}">
		<td align="center" class="row1"><img src="{$ibforums->vars['mime_img']}/{$data['image']}" alt="{$ibforums->lang['attached_file']}" /></td>
		<td class="row2">
			<a href="{$ibforums->base_url}act=Attach&amp;type={$data['_type']}&amp;id={$data['attach_id']}" title="{$data['attach_file']}" target="_blank">{$data['short_name']}</a>
			<div class="desc">( {$ibforums->lang['attach_hits']}: {$data['attach_hits']} )</div>
		</td>
		<td align="center" class="row1">{$data['real_size']}</td>
		<td class="row2">
EOF;
//startif
if ( $data['attach_pid'] > 0 )
{
$IPBHTML .= <<<EOF
<a href="{$ibforums->base_url}showtopic={$data['tid']}&amp;view=findpost&amp;p={$data['attach_pid']}">{$data['title']}</a>
EOF;
}//endif
else
{
$IPBHTML .= <<<EOF
{$data['title']}
EOF;
}//endelse
$IPBHTML .= <<<EOF
				<br />
			<span class="desc">{$data['attach_date']}</span>
		</td>
		<td class="row2" align="center"><input type="checkbox" name="attach_{$data['attach_id']}" value="1" class="checkbox" /></td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// attachments_top
//===========================================================================
function attachments_top($info="",$pages="",$attach_html="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<!-- inbox folder -->
<div class="formsubtitle">{$ibforums->lang['m_attach']}</div>
EOF;
//startif
if ( $info['has_limit'] == 1 )
{
$IPBHTML .= <<<EOF
<table cellspacing="0">
		<tr>
			<td valign="middle">
				<!-- LEFT -->
				<table cellspacing="1" class="inbox">
					<tr>
						<td class="row1" colspan="3">{$ibforums->lang['attach_space_used']}</td>
					</tr>
					<tr>
						<td valign="middle" class="row1" colspan="3"><{BAR_LEFT}><img src="{$ibforums->vars['img_url']}/bar.gif" width="{$info['img_width']}" height="11" align="middle" alt="" /><{BAR_RIGHT}></td>
					</tr>
					<tr>
						<td class="row1" width="33%" valign="middle">0%</td>
						<td class="row1" width="33%" align="center" valign="middle">50%</td>
						<td class="row1" width="33%" align="right" valign="middle">100%</td>
					</tr>
				</table>
			</td>
			
			<!-- RIGHT -->
			<td align="right" valign="bottom">$pages<br /><br />{$ibforums->lang['attach_space_count']}</td>
		</tr>
	</table>
EOF;
}//endif
else
{
$IPBHTML .= <<<EOF
<table cellspacing="0">
	<tr>
		<td>
			<!-- LEFT -->
			{$ibforums->lang['attach_space_used']}
		</td>
		<td align="right">
			<!-- RIGHT -->
			$pages
		</td>
	</tr>
</table>
EOF;
}//endelse

$IPBHTML .= <<<EOF
<!-- ATTACHMENTS TABLE -->
  
<form action="{$ibforums->base_url}act=usercp&amp;CODE=attach&amp;sort={$ibforums->input['sort']}" name="mutliact" method="post">
<div class="borderwrapm">
	<table cellspacing="1">
		<tr>
			<th width="2%">&nbsp;</th>
			<th width="35%"><b>{$ibforums->lang['attach_title']}</b></th>
			<th width="5%"><b>{$ibforums->lang['attach_hsize']}</b></th>
			<th width="27%"><b>{$ibforums->lang['attach_topic']}</b></a></th>
			<th width="5%" align="center"><input name="allbox" type="checkbox" value="Check All" onclick="InboxCheckAll();" /></th>
		</tr>
EOF;
//startif
if ( $attach_html != "" )
{
$IPBHTML .= <<<EOF
{$attach_html}
		<tr>
			<td colspan="6" align="right" class="formbuttonrow"><input type="submit" value="{$ibforums->lang['attach_delete']}" class="button" /></td>
		</tr>
EOF;
}//endif
else
{
$IPBHTML .= <<<EOF
<tr>
			<td colspan="6" align="center">{$ibforums->lang['splash_noattach']}</td>
		</tr>
EOF;
}//endelse
$IPBHTML .= <<<EOF
	</table>
</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_autosize
//===========================================================================
function avatar_autosize() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<table cellspacing="0">
	<tr>
		<td class="pformleft">&nbsp;</td>
		<td class="pformright"><b>{$ibforums->lang['av_autosize']}</b><br />({$ibforums->lang['av_as_desc']})</td>
	</tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_external_title
//===========================================================================
function avatar_external_title() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['avatar_url_title']}</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_gallery_blank_row
//===========================================================================
function avatar_gallery_blank_row() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<td>&nbsp;</td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_gallery_cell_row
//===========================================================================
function avatar_gallery_cell_row($img="",$txt="",$form="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<td align="center"><img src="style_avatars{$img}" alt="txt" /><br /><input type="radio" class="radiobutton" name="avatar" value="$form" id="$form" />&nbsp;<b><label for="$form">$txt</label></b></td>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_gallery_end_row
//===========================================================================
function avatar_gallery_end_row() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_gallery_end_table
//===========================================================================
function avatar_gallery_end_table() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</table>
<div align="center" class="formsubtitle">
	<input type="submit" name="submit" value="{$ibforums->lang['av_gall_submit']}" />
	&nbsp;&nbsp;&nbsp;<input type="button" name="remove" onclick="self.location='{$ibforums->base_url}act=UserCP&amp;CODE=24';" value="{$ibforums->lang['av_gall_cancel']}" />
</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_gallery_start_row
//===========================================================================
function avatar_gallery_start_row() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_gallery_start_table
//===========================================================================
function avatar_gallery_start_table($title="",$av_gals="",$current_folder="",$key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['av_gallery_title']} $title</div>
<form action="{$ibforums->base_url}act=UserCP&amp;CODE=getgallery" method="post">
	<div id="padandcenter"><b>{$ibforums->lang['av_gall_jump']}</b>&nbsp;$av_gals&nbsp;&nbsp;<input type="submit" value="{$ibforums->lang['av_go_go']}" name="submit" /></div>
</form>
<form action="{$ibforums->base_url}auth_key=$key" method="post">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="setinternalavatar" />
<input type="hidden" name="current_folder" value="$current_folder" />
	<table cellspacing="0">
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_limits
//===========================================================================
function avatar_limits() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['av_settings']}</div>
	<p>{$ibforums->lang['av_text_url']} {$ibforums->lang['av_text_upload']}<br />{$ibforums->lang['av_allowed_files']}</p>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_main
//===========================================================================
function avatar_main($data="",$formextra="",$hidden_field="",$key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
var url_input      = "{$data['current_url_avatar']}";
var remove_pressed = 0;
	function select_url(){
		restore_it();
	}
	
	function select_upload(){
		try{
			if ( document.creator.url_avatar.value != "" ) {
				url_input = document.creator.url_avatar.value;
			}
			document.creator.url_avatar.value = "";
		}
		catch(nourl){
			return true;
		}
	}
	
	function restore_it(){
		if (url_input != ""){
			document.creator.url_avatar.value = url_input;
			}
		}
	function checkform(){
		if ( remove_pressed != 1 ){
			return true;
		}
	
		else{
			fcheck = confirm("{$ibforums->lang['av_confirm']}");
			if ( fcheck == true ){
				return true;
			}
			else{
				return false;
				}
			}
	}
-->
</script>
<!--IBF.LIMITS_AVATAR-->
<div class="formsubtitle">{$ibforums->lang['av_current']}</div>
<div class="tablepad" align="center">{$data['current_avatar_image']}<br />{$data['current_avatar_type']} {$data['current_avatar_dims']}</div>
<div class="formsubtitle">{$ibforums->lang['avatar_pre_title']}</div>
<form action="{$ibforums->base_url}act=UserCP&amp;CODE=getgallery" method="post">
	<table cellspacing="0">
		<tr>
			<td class="pformleft">{$ibforums->lang['av_go_gal']}</td>
			<td class="pformright">{$data['avatar_galleries']}&nbsp;&nbsp;<input type="submit" value="{$ibforums->lang['av_go_go']}" name="submit" /></td>
		</tr>
	</table>
</form>
<form action="{$ibforums->base_url}auth_key=$key" method="post" $formextra name="creator" onsubmit="return checkform();">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="25" />
$hidden_field
<!--IBF.EXTERNAL_TITLE-->
<!--IBF.URL_AVATAR-->
<!--IBF.UPLOAD_AVATAR-->
<!--IPB.SIZE-->
	<div align="center" class="formsubtitle">
		<input type="submit" name="submit" value="{$ibforums->lang['av_update']}" />
		&nbsp;&nbsp;&nbsp;<input type="submit" name="remove" onclick="remove_pressed=1;" value="{$ibforums->lang['av_remove']}" />
	</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_mansize
//===========================================================================
function avatar_mansize() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<table cellspacing="0">
	<tr>
		<td class="pformleft">&nbsp;</td>
		<td class="pformright"><b>{$ibforums->lang['width']}</b>&nbsp;<input type="text" size="3" name="man_width" />&nbsp;&nbsp;<b>{$ibforums->lang['height']}</b>&nbsp;<input type="text" size="3" name="man_height" /></td>
	</tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_upload_field
//===========================================================================
function avatar_upload_field() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<table cellspacing="0">
	<tr>
		<td class="pformleft">{$ibforums->lang['av_upload']}</td>
		<td class="pformright"><input type="file" size="30" name="upload_avatar" onfocus="select_upload()" onclick="select_upload()" /></td>
	</tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// avatar_url_field
//===========================================================================
function avatar_url_field($avatar="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<table cellspacing="0">
	<tr>
		<td class="pformleft">{$ibforums->lang['av_url']}</td>
		<td class="pformright"><input type="text" size="40" maxlength="80" name="url_avatar" value="$avatar" onfocus="select_url()" />&nbsp;&nbsp;(<a href="javascript:restore_it()">{$ibforums->lang['pp_restore']}</a>)</td>
	</tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// birthday
//===========================================================================
function birthday($day="",$month="",$year="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td class="pformleft"><b>{$ibforums->lang['birthday']}</b></td>
		<td class="pformright">
			<select name="day">&nbsp;
				{$day}
			</select> 
			<select name="month">&nbsp;
				{$month}
			</select>
			<select name="year">&nbsp;
				{$year}
			</select>
		</td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// CP_end
//===========================================================================
function CP_end() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</div>
		</td>
	</tr>
</table>
	<!-- end main CP area -->
	<br style="clear: all;" />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// dead_section
//===========================================================================
function dead_section() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['dead_section_title']}</div>
<p>
	{$ibforums->lang['dead_section_text']}
</p>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// email
//===========================================================================
function email($Profile="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form action="{$ibforums->base_url}auth_key={$Profile['key']}" method="post">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="03" />
<div class="formsubtitle">{$ibforums->lang['privacy_settings']}</div>
<table cellspacing="0">
	<tr>
		<td align="right" valign="top"><input type="checkbox" name="hide_email" value="1" {$Profile['hide_email']} /></td>
		<td width="100%">{$ibforums->lang['hide_email']}</td>
	</tr>
	<tr>
		<td align="right" valign="top"><input type="checkbox" name="admin_send" value="1" {$Profile['allow_admin_mails']} /></td>
		<td  width="100%">{$ibforums->lang['admin_send']}</td>
	</tr>
</table>
	<br />
<div class="formsubtitle">{$ibforums->lang['board_prefs']}</div>
<table cellspacing="0">
	<tr>
		<td align="right" valign="top"><input type="checkbox" name="send_full_msg" value="1" {$Profile['email_full']} /></td>
		<td  width="100%">{$ibforums->lang['send_full_msg']}</td>
	</tr>
	<tr>
		<td align="right" valign="top"><input type="checkbox" name="pm_reminder" value="1" {$Profile['email_pm']} /></td>
		<td  width="100%">{$ibforums->lang['pm_reminder']}</td>
	</tr>
	<tr>
		<td align="right" valign="top"><input type="checkbox" name="auto_track" value="1" {$Profile['auto_track']} /></td>
		<td  width="100%">
			{$ibforums->lang['auto_track']}
				<select name="trackchoice">
					<option value="none">{$ibforums->lang['subs_none_title']}</option>
					<option value="immediate">{$ibforums->lang['subs_immediate']}</option>
					<option value="delayed">{$ibforums->lang['subs_delayed']}</option>
					<option value="daily">{$ibforums->lang['subs_daily']}</option>
					<option value="weekly">{$ibforums->lang['subs_weekly']}</option>
				</select>
					<br />
			{$ibforums->lang['auto_track_desc']}
		</td>
	</tr>
	<tr>
		<td class="formbuttonrow" colspan="2"><input type="submit" value="{$ibforums->lang['submit_email']}" /></td>
	</tr>
</table>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// email_change
//===========================================================================
function email_change($txt="",$msg="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
var msg = "$msg";
	if ( msg != ""){
		alert(msg);
	}
</script>
<form action="{$ibforums->base_url}" method="post" name="form1">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="09" />
<div class="formsubtitle">{$ibforums->lang['change_email_title']}</div>
<p>
	$txt
</p>
<table cellspacing="0">
	<tr>
		<td width="40%"><b>{$ibforums->lang['ce_new_email']}</b></td>
		<td><input type="text" name="in_email_1" value="" /></td>
	</tr>
	<tr>
		<td><b>{$ibforums->lang['ce_new_email2']}</b></td>
		<td><input type="text" name="in_email_2" value="" /></td>
	</tr>
	<tr>
		<td><b>{$ibforums->lang['ec_passy']}</b></td>
		<td><input type="password" name="password" value="" /></td>
	</tr>
</table>
<!--ANTIBOT-->
	<div class="formsubtitle" style="text-align: center;"><input type="submit" name="change_email" value="{$ibforums->lang['account_email_submit']}" /></div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// email_change_gd
//===========================================================================
function email_change_gd($regid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['ras_title']}</div>
<table cellspacing="0">
	<tr>
		<td width="40%">{$ibforums->lang['ras_numbers']}</td>
		<td>
			<input type="hidden" name="regid" value="$regid" />
			<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}" alt="Code Bit" />
		</td>
	</tr>
	<tr>
		<td width="40%">{$ibforums->lang['ras_text']}</td>
		<td><input type="text" size="32" maxlength="32" name="reg_code" /></td>
	</tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// email_change_img
//===========================================================================
function email_change_img($regid="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['ras_title']}</div>
<table cellspacing="0">
	<tr>
		<td width="40%">{$ibforums->lang['ras_numbers']}</td>
		<td>
			<input type="hidden" name="regid" value="$regid" />
				<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}&amp;p=1" alt="Code Bit" />
				&nbsp;<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}&amp;p=2" alt="Code Bit" />
				&nbsp;<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}&amp;p=3" alt="Code Bit" />
				&nbsp;<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}&amp;p=4" alt="Code Bit" />
				&nbsp;<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}&amp;p=5" alt="Code Bit" />
				&nbsp;<img src="{$ibforums->base_url}act=UserCP&amp;CODE=show_image&amp;rc={$regid}&amp;p=6" alt="Code Bit" />
		</td>
	</tr>
	<tr>
		<td width="40%">{$ibforums->lang['ras_text']}</td>
		<td><input type="text" size="32" maxlength="32" name="reg_code" /></td>
	</tr>
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// field_dropdown
//===========================================================================
function field_dropdown($name="",$options="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<select name="$name">
	$options
</select>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// field_entry
//===========================================================================
function field_entry($title="",$desc="",$content="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td class="pformleft" valign="top"><b>$title</b><br />$desc</td>
		<td class="pformright">$content</td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// field_textarea
//===========================================================================
function field_textarea($name="",$value="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<textarea cols="60" rows="5" wrap="soft" name="$name">$value</textarea>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// field_textinput
//===========================================================================
function field_textinput($name="",$value="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<input type="text" size="50" name="$name" value="$value" />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// forum_jump
//===========================================================================
function forum_jump($data="",$menu_extra="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="borderwrap">
<div align="right" class="row1" style="padding: 5px;">{$data}</div>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// forum_subs_end
//===========================================================================
function forum_subs_end() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td align="right" class="formbuttonrow" valign="middle" colspan="6">
			<select name="trackchoice">
				<option value="unsubscribe">{$ibforums->lang['subs_delete']}</option>
				<option value="none">{$ibforums->lang['subs_c_change']} {$ibforums->lang['subs_none_title']}</option>
				<option value="immediate">{$ibforums->lang['subs_c_change']} {$ibforums->lang['subs_immediate']}</option>
				<option value="delayed">{$ibforums->lang['subs_c_change']} {$ibforums->lang['subs_delayed']}</option>
				<option value="daily">{$ibforums->lang['subs_c_change']} {$ibforums->lang['subs_daily']}</option>
				<option value="weekly">{$ibforums->lang['subs_c_change']} {$ibforums->lang['subs_weekly']}</option>
			</select>&nbsp;&nbsp;
			<input type="submit" class="button" value="{$ibforums->lang['with_selected']}" />
		</td>
	</tr>
</table>
</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// forum_subs_header
//===========================================================================
function forum_subs_header() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form action="{$ibforums->base_url}" name="mutliact" method="post">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="51" />
<div class="formsubtitle">{$ibforums->lang['forum_subs_header']}</div>
<div class="borderwrapm">
	<table cellspacing="1">
		<tr>
			<th width="5%">&nbsp;</th>
			<th width="50%">{$ibforums->lang['ft_forum']}</th>
			<th align="center" width="5%">{$ibforums->lang['ft_topics']}</th>
			<th align="center" width="5%">{$ibforums->lang['ft_posts']}</th>
			<th align="center" width="35%">{$ibforums->lang['ft_last_post']}</th>
			<th width="1%">&nbsp;</th>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// forum_subs_none
//===========================================================================
function forum_subs_none() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td class="row1" align="center" colspan="6">{$ibforums->lang['forum_subs_none']}</td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// forum_subs_row
//===========================================================================
function forum_subs_row($data="",$type="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td class="row1" align="center" width="5%">{$data['folder_icon']}</td>
		<td class="row1">
			<b><a href="{$ibforums->base_url}act=SF&amp;f={$data['id']}">{$data['name']}</a></b>
			<div class="desc">
				{$data['description']}
					<br />
				{$ibforums->lang['subs_c_type']}: {$ibforums->lang[$type]}
			</div>
		</td>
		<td class="row1" align="center">{$data['topics']}</td>
		<td class="row1" align="center">{$data['posts']}</td>
		<td class="row1">{$data['last_post']}<br />{$ibforums->lang['in']} {$data['last_topic']}<br />{$ibforums->lang['by']} {$data['last_poster']}</td>
		<td class="row1" align="center"><input type="checkbox" name="id-{$data['forum_id']}" value="yes" /></td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// iu_add_new
//===========================================================================
function iu_add_new() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td colspan="4" class="formsubtitle">{$ibforums->lang['mi5_addem']}</td>
	</tr>
	<tr>
		<td colspan="2" class="row1"><input type="text" name="newbox_1" value="{$ibforums->input['newbox_1']}" /></td>
		<td colspan="2" class="row2"><input type="button" value="{$ibforums->lang['mi5_finduser']}" name="findusers" onclick="find_users('newbox_1')"  /></td>
	</tr>
	<tr>
		<td colspan="2" class="row1"><input type="text" name="newbox_2" value="{$ibforums->input['newbox_2']}" /></td>
		<td colspan="2" class="row2"><input type="button" value="{$ibforums->lang['mi5_finduser']}" onclick="find_users('newbox_2')" /></td>
	</tr>
	<tr>
		<td colspan="2" class="row1"><input type="text" name="newbox_3" value="{$ibforums->input['newbox_3']}" /></td>
		<td colspan="2" class="row2"><input type="button" value="{$ibforums->lang['mi5_finduser']}" onclick="find_users('newbox_3')" /></td>
	</tr>
	<tr>
		<td class="formbuttonrow" colspan="4"><input type="submit" value="{$ibforums->lang['mi5_edit']}" /></td>
	</tr>
</table>
</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// iu_populated_row
//===========================================================================
function iu_populated_row($member="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td><b><a href="{$ibforums->base_url}showuser={$member['id']}">{$member['name']}</a></b></td>
		<td>{$member['prefix']}{$member['g_title']}{$member['suffix']}</td>
		<td>{$member['posts']}</td>
		<td><a href="{$ibforums->base_url}act=UserCP&amp;CODE=ignoreremove&amp;id={$member['id']}">{$ibforums->lang['mi5_remove']}</a></td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// iu_start
//===========================================================================
function iu_start() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
	function find_users(field){
		url = "index.{$ibforums->vars['php_ext']}?act=legends&CODE=finduser_one&s={$ibforums->session_id}&entry=textarea&name="+field+"&sep=none";
		window.open(url,"FindUsers","width=400,height=250,resizable=yes,scrollbars=yes"); 
	}
-->
</script>
<form action="{$ibforums->base_url}" method="post" name="REPLIER">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="ignoreadd" />
<div class="formsubtitle">{$ibforums->lang['mi5_title']}</div>
<p>{$ibforums->lang['mi5_text']}</p>
<div class="borderwrapm">
	<table cellspacing="1">
		<tr>
			<th width="30%">{$ibforums->lang['mi5_name']}</th>
			<th width="30%">{$ibforums->lang['mi5_group']}</th>
			<th width="20%">{$ibforums->lang['mi5_posts']}</th>
			<th width="20%">&nbsp;</th>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// member_title
//===========================================================================
function member_title($title="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
			<td class="pformleft"><b>{$ibforums->lang['member_title']}</b></td>
			<td class="pformright"><input type="text" size="40" maxlength="120" name="member_title" value="$title" /></td>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// Menu_bar
//===========================================================================
function Menu_bar($base_url="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<!--
TABLE TO FIX IE/6 ISSUE
The one where 23% margin + 100% table = 123% in IE6 o_O
-->
<script type="text/javascript" src="jscripts/ipb_pm.js"></script>
<table cellspacing="0">
	<tr>
		<td valign="top" class="nopad" width="25%">
			<div id="ucpmenu">
			<div class="maintitle">{$ibforums->lang['tt_menu']}</div>
EOF;
//startif
if ( $ibforums->vars['blog_default_view'] != "" )
{
$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['m_blog']}</div>
			<p>
				&middot; <a href="{$ibforums->base_url}automodule=blog&amp;cmd=ucp_main">{$ibforums->lang['m_blog_ucp_main']}</a><br />
EOF;
}//endif
//startif
if ( $ibforums->vars['blog_allow_cblockchange'] == 1 and $ibforums->member['has_blog'] == 1 )
{
$IPBHTML .= <<<EOF
&middot; <a href="{$ibforums->base_url}automodule=blog&amp;cmd=ucp_cblocks">{$ibforums->lang['m_blog_cblocks']}</a><br />
EOF;
}//endif
//startif
if ( $ibforums->member['has_blog'] == 1 )
{
$IPBHTML .= <<<EOF
&middot; <a href="{$ibforums->base_url}automodule=blog&amp;cmd=ucp_aboutme">{$ibforums->lang['m_blog_aboutme']}</a><br />
				&middot; <a href="{$ibforums->base_url}automodule=blog&amp;cmd=showblog&amp;mid={$ibforums->member['id']}">{$ibforums->lang['m_blog_your_blog']}</a><br />
			</p>
EOF;
}//endif
//startif
if ( $ibforums->vars['top_site_list_integrate'] == 1 )
{
$IPBHTML .= <<<EOF
<!-- Top Site List -->
			<div class="formsubtitle">{$ibforums->lang['m_top_list']}</div>
			<p>
				<{ITEM_START}> <a href="{$ibforums->base_url}act=module&module=toplist"><b>{$ibforums->lang['tsl_home']}</b></a><br />
				<{ITEM_START}> <a href="{$ibforums->base_url}act=module&module=toplist&amp;CODE=01"><b>{$ibforums->lang['tsl_your_sites']}</b></a><br />
			</p>
EOF;
}//endif
//startif
if ( $ibforums->vars['gallery_images_path'] != "" )
{
$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['m_gallery']}</div>
			<p>
				&middot; <a href="{$ibforums->base_url}act=module&module=gallery&cmd=albums">{$ibforums->lang['m_gallery_albums']}</a><br />
				&middot; <a href="{$ibforums->base_url}act=module&module=gallery&cmd=favs">{$ibforums->lang['m_gallery_favs']}</a><br />
			</p>
EOF;
}//endif

$IPBHTML .= <<<EOF
	 		<!-- Messenger Links -->
EOF;
//startif
if ( $ibforums->member['g_use_pm'] == 1 )
{
$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['m_messenger']}</div>
			<p>
				<{ITEM_START}> <a href="{$base_url}act=Msg&amp;CODE=04"><b>{$ibforums->lang['mess_new']}</b></a><br />
				<!--IBF.FOLDER_LINKS-->
				&nbsp;&nbsp; <{MSG_FOLDER}>&nbsp;<a href="{$base_url}act=Msg&amp;CODE=20">{$ibforums->lang['mess_saved']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=Msg&amp;CODE=delete">{$ibforums->lang['mi_prune_msg']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=Msg&amp;CODE=07">{$ibforums->lang['mess_folders']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=Msg&amp;CODE=02">{$ibforums->lang['mess_contact']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=Msg&amp;CODE=14">{$ibforums->lang['mess_archive']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=Msg&amp;CODE=30">{$ibforums->lang['mess_tracker']}</a><br />
			</p>
	 	<!-- End Messenger -->
EOF;
}//endif

$IPBHTML .= <<<EOF
		<!-- Topic Tracker -->
			<div class="formsubtitle">{$ibforums->lang['m_tracker']}</div>
			<p>
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=26">{$ibforums->lang['m_view_subs']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=50">{$ibforums->lang['m_view_forum']}</a><br />
			</p>
		<!-- Profile -->
			<div class="formsubtitle">{$ibforums->lang['m_personal']}</div>
			<p>
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=01">{$ibforums->lang['m_contact_info']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=22">{$ibforums->lang['m_sig_info']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=24">{$ibforums->lang['m_avatar_info']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=photo">{$ibforums->lang['m_change_photo']}</a><br />
			</p>
		<!-- Options -->
			<div class="formsubtitle">{$ibforums->lang['m_options']}</div>
			<p>
				<!--IBF.OPTION_LINKS-->
EOF;
//startif
if ( $ibforums->member['g_attach_max'] != -1 )
{
$IPBHTML .= <<<EOF
<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=attach">{$ibforums->lang['m_attach']}</a><br />
EOF;
}//endif

$IPBHTML .= <<<EOF
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=ignore">{$ibforums->lang['m_ignore_users']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=02">{$ibforums->lang['m_email_opt']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=04">{$ibforums->lang['m_board_opt']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=08">{$ibforums->lang['m_email_change']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=28">{$ibforums->lang['m_passy_opt']}</a>
			</p>
EOF;
//startif
if ( $ibforums->member['g_is_supmod'] == 1 )
{
$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['menu_title_mod']}</div>
			<p>
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=iptool">{$ibforums->lang['menu_ipsearch']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=memtool">{$ibforums->lang['menu_memsearch']}</a><br />
				<{ITEM_START}> <a href="{$base_url}act=UserCP&amp;CODE=announce_start">{$ibforums->lang['menu_announcements']}</a>
			</p>
EOF;
}//endif
$IPBHTML .= <<<EOF
		</div>
		</td>
		<td class="nopad" width="1%"><!-- --></td>
		<!-- Start main CP area -->
		<td valign="top" class="nopad" width="75%">
			<div id="ucpcontent">
			<div class="maintitle">{$ibforums->lang['welcome']}</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// menu_bar_msg_folder_link
//===========================================================================
function menu_bar_msg_folder_link($id="",$real="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
&nbsp;&nbsp; <{MSG_FOLDER}>&nbsp;<a href="{$ibforums->base_url}act=Msg&amp;CODE=01&amp;VID=$id">$real</a><br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// menu_bar_new_link
//===========================================================================
function menu_bar_new_link($url="",$name="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<{ITEM_START}> <a href="$url">$name</a><br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mod_find_user
//===========================================================================
function mod_find_user($msg="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form name="ibform" action="{$ibforums->base_url}act=usercp&amp;CODE=domemtool" method="post">
EOF;
//startif
if ( $msg )
{
$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['ipm_title']}</div>
<p>
	$msg
</p>
<br />
EOF;
}//endif
$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['cp_edit_user']}</div>
	<table cellspacing="1">
		<tr>
			<td width="40%" class="row1">{$ibforums->lang['cp_find_user']}</td>
			<td class="row1"><input type="text" size="40" name="name" value="{$ibforums->input['name']}" /></td>
		</tr>
	<tr>
		<td class="formbuttonrow" colspan="2"><input type="submit" value="{$ibforums->lang['cp_find_submit']}" /></td>
	</tr>
	</table>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mod_ip_member_results
//===========================================================================
function mod_ip_member_results($pages="",$content="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div>
	<div class="borderwrapm">
		<table cellspacing="0">
			<tr>
				<th width="20%">{$ibforums->lang['ipm_name']}</th>
				<th width="20%">{$ibforums->lang['ipm_ip']}</th>
				<th width="10%">{$ibforums->lang['ipm_posts']}</th>
				<th width="15%">{$ibforums->lang['ipm_reg']}</th>
				<th width="15%">{$ibforums->lang['ipm_group']}</th>
				<th width="20%">{$ibforums->lang['ipm_options']}</th>
			</tr>
			{$content}
		</table>
	</div>
	<div>$pages</div>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mod_ip_member_row
//===========================================================================
function mod_ip_member_row($row="",$auth_key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
	<td class="row1"><a href="{$ibforums->base_url}showuser={$row['id']}">{$row['name']}</a></td>
	<td class="row1">{$row['ip_address']}</td>
	<td class="row1">{$row['posts']}</td>
	<td class="row1">{$row['joined']}</td>
	<td class="row1">{$row['groupname']}</td>
	<td class="row1" align="center"><a href="{$ibforums->base_url}act=mod&amp;CODE=editmember&amp;mid={$row['id']}&amp;auth_key=$auth_key">{$ibforums->lang['ipm_edit']}</a></td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mod_ip_post_results
//===========================================================================
function mod_ip_post_results($uid="",$count="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
{$ibforums->lang['ipp_found']} $count
<br />
<br />
<a target="_blank" href="{$ibforums->base_url}act=Search&amp;CODE=show&amp;searchid=$uid&amp;search_in=posts&amp;result_type=posts">{$ibforums->lang['ipp_click']}</a>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// mod_ip_start_form
//===========================================================================
function mod_ip_start_form($ip="",$msg="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form name="ibform" action="{$ibforums->base_url}" method="post">
<input type="hidden" name="s" value="{$ibforums->session_id}" />
<input type="hidden" name="act" value="usercp" />
<input type="hidden" name="CODE" value="doiptool" />
EOF;
//startif
if ( $msg )
{
$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['ipm_title']}</div>
<p>
	$msg
</p>
<br />
EOF;
}//endif
$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['menu_ipsearch']}</div>
	<table cellspacing="0">
		<tr>
			<td width="40%" class="row1">{$ibforums->lang['ip_enter']}</td>
			<td class="row1">
				<input type="text" size="20" maxlength="24" name="ip" value="{$ip}" />
				<select name="iptool">
					<option value="resolve">{$ibforums->lang['ip_resolve']}</option>
					<option value="posts">{$ibforums->lang['ip_posts']}</option>
					<option value="members">{$ibforums->lang['ip_members']}</option>
				</select>
			</td>
		</tr>
	<tr>
		<td class="formsubtitle" style="text-align: center;" colspan="2"><input type="submit" value="{$ibforums->lang['ip_submit']}" /></td>
	</tr>
	</table>
</form>
	<br />
<div class="tablepad">
	{$ibforums->lang['ip_desc_text']}
	<br /><br />{$ibforums->lang['ip_warn_text']}
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// pass_change
//===========================================================================
function pass_change() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form action="{$ibforums->base_url}" method="post" name="form1">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="29" />
<div class="formsubtitle">{$ibforums->lang['account_pass_title']}</div>
<p>{$ibforums->lang['pass_change_text']}</p>
<table cellspacing="0">
	<tr>
		<td><b>{$ibforums->lang['account_pass_old']}</b></td>
		<td><input type="password" name="current_pass" value="" /></td>
	</tr>
	<tr>
		<td><b>{$ibforums->lang['account_pass_new']}</b></td>
		<td><input type="password" name="new_pass_1" value="" /></td>
	</tr>
	<tr>
		<td><b>{$ibforums->lang['account_pass_new2']}</b></td>
		<td><input type="password" name="new_pass_2" value="" /></td>
	</tr>
	<tr>
		<td class="formbuttonrow" colspan="2"><input type="submit" name="s_pass" value="{$ibforums->lang['account_pass_submit']}" /></td>
	</tr>
</table>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// personal_panel
//===========================================================================
function personal_panel($Profile="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
var LocationMax  = "{$ibforums->vars['max_location_length']}";
var InterestMax  = "{$ibforums->vars['max_interest_length']}";
	function CheckLength(Type){
		LocationLength  = document.theForm.Location.value.length;
		InterestLength  = document.theForm.Interests.value.length;
		message  = "";
			if (Type == "location"){
				if (LocationMax !=0) {
					message = "{$ibforums->lang['js_location']}: {$ibforums->lang['js_max']} " + LocationMax + " {$ibforums->lang['js_characters']}.";
				}
			else{
            	message = "";
            }
            	alert(message + "  {$ibforums->lang['js_used']} " + LocationLength + " {$ibforums->lang['js_so_far']}.");
            }
    		
            if (Type == "interest"){
	            if (InterestMax !=0){
		            message = "{$ibforums->lang['js_interests']}: {$ibforums->lang['js_max']} " + InterestMax + " {$ibforums->lang['js_characters']}.";
		        }
		        else{
			        message = "";
			    }
			    alert(message + "  {$ibforums->lang['js_used']} " + InterestLength + " {$ibforums->lang['js_so_far']}.");
			}
	}
	
	function ValidateProfile(){
    	LocationLength  = document.theForm.Location.value.length;
    	InterestLength  = document.theForm.Interests.value.length;
    	errors = "";
    		if (LocationMax !=0){
	    		if (LocationLength > LocationMax) {
		    		errors = "{$ibforums->lang['js_location']}:  {$ibforums->lang['js_max']} " + LocationMax + " {$ibforums->lang['js_characters']}.  {$ibforums->lang['js_used']}: " + LocationLength;
		    	}
		    }
		   	if (InterestMax !=0){
        		if (InterestLength > InterestMax){
	        		errors = errors + "  {$ibforums->lang['js_interests']}:  {$ibforums->lang['js_max']} " + InterestMax + " {$ibforums->lang['js_characters']}.  {$ibforums->lang['js_used']}: " + InterestLength;
	        	}
	        }
	        if (errors != ""){
		        alert(errors);
		        return false;
		       	}
		    else{
			    return true;
			   	}
	}
-->
</script>
<form action="{$ibforums->base_url}auth_key={$Profile['key']}" method="post" name="theForm" onsubmit="return ValidateProfile()">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="21" />
<!--{REQUIRED.FIELDS}-->
<div class="formsubtitle">{$ibforums->lang['profile_title']}</div>
<table cellspacing="0">
	<!--{MEMBERTITLE}-->
	<!--{BIRTHDAY}-->
	<tr>
		<td class="pformleft">{$ibforums->lang['website']}</td>
		<td class="pformright"><input type="text" size="40" maxlength="1200" name="WebSite" value="{$Profile['website']}" /></td>
	</tr>  
	<tr>
		<td class="pformleft">{$ibforums->lang['icq']}</td>
		<td class="pformright"><input type="text" size="40" maxlength="20" name="ICQNumber" value="{$Profile['icq_number']}" /></td>
	</tr>
	<tr>
		<td class="pformleft">{$ibforums->lang['aol']}</td>
		<td class="pformright"><input type="text" size="40" maxlength="30" name="AOLName" value="{$Profile['aim_name']}" /></td>
	</tr>
	<tr>
		<td class="pformleft">{$ibforums->lang['yahoo']}</td>
		<td class="pformright"><input type="text" size="40" maxlength="30" name="YahooName" value="{$Profile['yahoo']}" /></td>
	</tr>
	<tr>
		<td class="pformleft">{$ibforums->lang['msn']}</td>
		<td class="pformright"><input type="text" size="40" maxlength="30" name="MSNName" value="{$Profile['msnname']}" /></td>
	</tr>
	<tr>
		<td class="pformleft">{$ibforums->lang['location']}<br />(<a href="javascript:CheckLength('location');">{$ibforums->lang['check_length']}</a>)</td>
		<td class="pformright"><input type="text" size="40" name="Location" value="{$Profile['location']}" /></td>
	</tr>
	<tr>
		<td class="pformleft" valign="top">{$ibforums->lang['interests']}<br />(<a href="javascript:CheckLength('interest');">{$ibforums->lang['check_length']}</a>)</td>
		<td class="pformright"><textarea cols="60" rows="10" wrap="soft" name="Interests">{$Profile['interests']}</textarea></td>
	</tr>
	<!--{OPTIONAL.FIELDS}-->
	<tr>
		<td class="formbuttonrow" align="center" colspan="2"><input type="submit" value="{$ibforums->lang['submit_profile']}" /></td>
	</tr>
</table>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// photo_page
//===========================================================================
function photo_page($cur_photo="",$cur_type="",$url_photo="",$show_size="",$key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
var url_input = "$url_photo";
var remove_pressed = 0;
	
	function clear_it(){
		if ( document.bob.url_photo.value != "" ){
			url_input = document.bob.url_photo.value;
		}
      	document.bob.url_photo.value = "";
	}
   
	function restore_it(){
		if (url_input != ""){
		document.bob.url_photo.value = url_input;
		}
	}
   
	function checkform(){
		if ( remove_pressed != 1 ){
			return true;
		}
   		else{
   			fcheck = confirm("{$ibforums->lang['pp_confirm']}");
   			if ( fcheck == true ){
   				return true;
   			}
   			else{
   				return false;
   			}
   		}
	}
-->
</script>
<form action="{$ibforums->base_url}auth_key=$key" enctype="multipart/form-data" method="post" name="bob" onsubmit="return checkform();">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="dophoto" />
<div class="formsubtitle">{$ibforums->lang['pph_title']}</div>
<p>{$ibforums->lang['pph_desc']}<br />{$ibforums->lang['pph_max']}</p>
<div class="formsubtitle">{$ibforums->lang['pph_current']}</div>
<div align="center">
 <p>$cur_photo<br />$cur_type ($show_size)</p>
</div>
<div class="formsubtitle">{$ibforums->lang['pph_change']}</div>
<table cellspacing="0">
	<tr>
		<td class="pformleft">{$ibforums->lang['pph_url']}</td>
		<td class="pformright"><input type="text" onfocus="restore_it()" name="url_photo" value="$url_photo" size="40" />&nbsp;&nbsp;(<a href="javascript:restore_it()">{$ibforums->lang['pp_restore']}</a>)</td>
	</tr>
	<!--IPB.UPLOAD-->
	<!--IPB.SIZE-->
</table>
<div align="center" class="formsubtitle">
	<input type="submit" name="submit" value="{$ibforums->lang['pph_submit']}" />
	&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" onclick="remove_pressed=1;" name="remove" value="{$ibforums->lang['pph_remove']}" />
</div>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// photo_page_autosize
//===========================================================================
function photo_page_autosize() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td class="pformleft">&nbsp;</td>
		<td class="pformright"><b>{$ibforums->lang['pph_autosize']}</b><br />({$ibforums->lang['pph_as_desc']})</td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// photo_page_mansize
//===========================================================================
function photo_page_mansize() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td class="pformleft">&nbsp;</td>
		<td class="pformright"><b>{$ibforums->lang['width']}</b>&nbsp;<input type="text" size="3" name="man_width" />&nbsp;&nbsp;<b>{$ibforums->lang['height']}</b>&nbsp;<input type="text" size="3" name="man_height" /></td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// photo_page_upload
//===========================================================================
function photo_page_upload($max_filesize="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td class="pformleft">{$ibforums->lang['pph_upload']}</td>
		<td class="pformright"><input type="hidden" name="MAX_FILE_SIZE" value="$max_filesize" /><input type="file" name="upload_photo" value="" size="40" onclick="clear_it()" /></td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// required_end
//===========================================================================
function required_end() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</table>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// required_title
//===========================================================================
function required_title() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['cf_required']}</div>
	<table cellspacing="0">
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// settings_end
//===========================================================================
function settings_end($data="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['settings_display']}</div>
<table cellspacing="0">
	<tr>
		<td width="70%">{$ibforums->lang['settings_viewsig']}</td>
		<td>{$data[SIG]}</td>
	</tr>
	<tr>
		<td>{$ibforums->lang['settings_viewimg']}</td>
		<td>{$data[IMG]}</td>
	</tr>
	<tr>
		<td>{$ibforums->lang['settings_viewava']}</td>
		<td>{$data[AVA]}</td>
	</tr>
	<tr>
		<td>{$ibforums->lang['settings_dopopup']}</td>
		<td>{$data[POP]}</td>
	</tr>
<!--
	<tr>
		<td>{$ibforums->lang['hide_session_txt']}<br/ ><span class="desc">{$ibforums->lang['hs_exp']}</span></td>
		<td>{$data[SESS]}</td>
	</tr>
-->
	<tr>
		<td>{$ibforums->lang['open_qr']}<br/ ></td>
		<td>{$data[QR]}</td>
	</tr>
	<tr>
		<td>{$ibforums->lang['pp_number_posts']}</td>
		<td>
			<select name="postpage">
				{$data['PPS']}
			</select>
		</td>
		</tr>
		<tr>
			<td>{$ibforums->lang['pp_number_topics']}</td>
			<td><select name="topicpage">{$data['TPS']}</select></td>
		</tr>
	<tr>
		<td class="formbuttonrow" colspan="2"><span class="desc">{$ibforums->lang['need_cookie_yum_yum']}</span><br /><input type="submit" name="submit" value="{$ibforums->lang['settings_submit']}" /></td>
	</tr>
	</table>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// settings_header
//===========================================================================
function settings_header($Profile="",$time_select="",$time="",$dst_check="",$key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form action="{$ibforums->base_url}auth_key=$key" method="post">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="05" />
<div class="formsubtitle">{$ibforums->lang['settings_time']}</div>
<p>
{$ibforums->lang['settings_time_txt']}&nbsp;$time
<br />
$time_select
<br /><br />
<input type="checkbox" name="DST" value="1" $dst_check /> &nbsp;{$ibforums->lang['dst_box']}
</p>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// signature
//===========================================================================
function signature($sig="",$t_sig="",$key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
var MessageMax  = "{$ibforums->lang['the_max_length']}";
var Override    = "{$ibforums->lang['override']}";
	function CheckLength(){
    	MessageLength  = document.REPLIER.Post.value.length;
    	message  = "";
	        if (MessageMax > 0){
    	        message = "{$ibforums->lang['js_max_length']} " + MessageMax + " {$ibforums->lang['js_characters']}.";
	        }
	        else{
            message = "";
        	}
        alert(message + " {$ibforums->lang['js_used']} " + MessageLength + " {$ibforums->lang['js_characters']}.");
	}
	
	function ValidateForm(){
    	MessageLength  = document.REPLIER.Post.value.length;
    	errors = "";
    		if (MessageMax !=0){
        		if (MessageLength > MessageMax){
            		errors = "{$ibforums->lang['js_max_length']} " + MessageMax + " {$ibforums->lang['js_characters']}. {$ibforums->lang['js_current']}: " + MessageLength;
            	}
            }
			if (errors != "" && Override == ""){
				alert(errors);
				return false;
			}
			else{
				document.REPLIER.submit.disabled = true;
				return true;
			}
	}
// IBC Code stuff
	var text_enter_url      = "{$ibforums->lang['jscode_text_enter_url']}";
	var text_enter_url_name = "{$ibforums->lang['jscode_text_enter_url_name']}";
	var text_enter_image    = "{$ibforums->lang['jscode_text_enter_image']}";
	var text_enter_email    = "{$ibforums->lang['jscode_text_enter_email']}";
	var text_enter_flash    = "{$ibforums->lang['jscode_text_enter_flash']}";
	var text_code           = "{$ibforums->lang['jscode_text_code']}";
	var text_quote          = "{$ibforums->lang['jscode_text_quote']}";
	var error_no_url        = "{$ibforums->lang['jscode_error_no_url']}";
	var error_no_title      = "{$ibforums->lang['jscode_error_no_title']}";
	var error_no_email      = "{$ibforums->lang['jscode_error_no_email']}";
	var error_no_width      = "{$ibforums->lang['jscode_error_no_width']}";
	var error_no_height     = "{$ibforums->lang['jscode_error_no_height']}";
	var prompt_start        = "{$ibforums->lang['js_text_to_format']}";
	
	var help_bold           = "{$ibforums->lang['hb_bold']}";
	var help_italic         = "{$ibforums->lang['hb_italic']}";
	var help_under          = "{$ibforums->lang['hb_under']}";
	var help_font           = "{$ibforums->lang['hb_font']}";
	var help_size           = "{$ibforums->lang['hb_size']}";
	var help_color          = "{$ibforums->lang['hb_color']}";
	var help_close          = "{$ibforums->lang['hb_close']}";
	var help_url            = "{$ibforums->lang['hb_url']}";
	var help_img            = "{$ibforums->lang['hb_img']}";
	var help_email          = "{$ibforums->lang['hb_email']}";
	var help_quote          = "{$ibforums->lang['hb_quote']}";
	var help_list           = "{$ibforums->lang['hb_list']}";
	var help_code           = "{$ibforums->lang['hb_code']}";
	var help_click_close    = "{$ibforums->lang['hb_click_close']}";
	var list_prompt         = "{$ibforums->lang['js_tag_list']}";
-->
</script>
<form action="{$ibforums->base_url}" method="post" name="REPLIER">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="23" />
<input type="hidden" name="key" value="$key" />
<div class="formsubtitle">{$ibforums->lang['cp_current_sig']}</div>
<div class="signature" style="padding: 5px;">$sig</div>
<div class="formsubtitle">{$ibforums->lang['cp_edit_sig']}</div>
<table cellspacing="0">
	<tr>
		<td class="pformleft">
			<input type="radio" name="bbmode" value="ezmode" onclick="setmode(this.value)" />&nbsp;<b>{$ibforums->lang['bbcode_guided']}</b><br />
			<input type="radio" name="bbmode" value="normal" onclick="setmode(this.value)" checked="checked" />&nbsp;<b>{$ibforums->lang['bbcode_normal']}</b>
			<script type="text/javascript" src="jscripts/ipb_bbcode.js"></script>
		</td>
		<td class="pformright" valign="top">
			<input type="button" accesskey="b" value=" B " onclick="simpletag('B')" class="codebuttons" name="B" style="font-weight: bold;" onmouseover="hstat('bold')" />
			<input type="button" accesskey="i" value=" I " onclick="simpletag('I')" class="codebuttons" name="I" style="font-style: italic;" onmouseover="hstat('italic')" />
			<input type="button" accesskey="u" value=" U " onclick="simpletag('U')" class="codebuttons" name="U" style="text-decoration: underline;" onmouseover="hstat('under')" />
			
			<select name="ffont" class="codebuttons" onchange="alterfont(this.options[this.selectedIndex].value, 'FONT')"  onmouseover="hstat('font')">
				<option value="0">{$ibforums->lang['ct_font']}</option>
				<option value="Arial" style="font-family: Arial;">{$ibforums->lang['ct_arial']}</option>
				<option value="Times" style="font-family: Times;">{$ibforums->lang['ct_times']}</option>
				<option value="Courier" style="font-family: Courier;">{$ibforums->lang['ct_courier']}</option>
				<option value="Impact" style="font-family: Impact;">{$ibforums->lang['ct_impact']}</option>
				<option value="Geneva" style="font-family: Geneva;">{$ibforums->lang['ct_geneva']}</option>
				<option value="Optima" style="font-family: Optima;">Optima</option>
			</select>
			<select name="fsize" class="codebuttons" onchange="alterfont(this.options[this.selectedIndex].value, 'SIZE')" onmouseover="hstat('size')">
				<option value="0">{$ibforums->lang['ct_size']}</option>
				<option value="1">{$ibforums->lang['ct_sml']}</option>
				<option value="7">{$ibforums->lang['ct_lrg']}</option>
				<option value="14">{$ibforums->lang['ct_lest']}</option>
			</select>
			<select name="fcolor" class="codebuttons" onchange="alterfont(this.options[this.selectedIndex].value, 'COLOR')" onmouseover="hstat('color')">
				<option value="0">{$ibforums->lang['ct_color']}</option>
				<option value="blue" style="color: blue;">{$ibforums->lang['ct_blue']}</option>
				<option value="red" style="color: red;">{$ibforums->lang['ct_red']}</option>
				<option value="purple" style="color: purple;">{$ibforums->lang['ct_purple']}</option>
				<option value="orange" style="color: orange;">{$ibforums->lang['ct_orange']}</option>
				<option value="yellow" style="color: yellow;">{$ibforums->lang['ct_yellow']}</option>
				<option value="gray" style="color: gray;">{$ibforums->lang['ct_grey']}</option>
				<option value="green" style="color: green;">{$ibforums->lang['ct_green']}</option>
			</select>
			&nbsp; <a href="javascript:closeall();" onmouseover="hstat('close')">{$ibforums->lang['js_close_all_tags']}</a>
				<br />
			<input type="button" accesskey="h" value=" http:// " onclick="tag_url()" class="codebuttons" name="url" onmouseover="hstat('url')" />
			<input type="button" accesskey="g" value=" IMG " onclick="tag_image()" class="codebuttons" name="img" onmouseover="hstat('img')" />
			<input type="button" accesskey="e" value="  @  " onclick="tag_email()" class="codebuttons" name="email" onmouseover="hstat('email')" />
			<input type="button" accesskey="q" value=" QUOTE " onclick="simpletag('QUOTE')" class="codebuttons" name="QUOTE" onmouseover="hstat('quote')" />
			<input type="button" accesskey="p" value=" CODE " onclick="simpletag('CODE')" class="codebuttons" name="CODE" onmouseover="hstat('code')" />
			<input type="hidden" accesskey="l" value=" LIST " onclick="tag_list()" class="codebuttons" name="LIST" onmouseover="hstat('list')" />
			<!--
			<input type="button" accesskey="l" value=" SQL "     onclick="simpletag("SQL")"     class="codebuttons" name="SQL" />
			<input type="button" accesskey="t" value=" HTML "    onclick="simpletag("HTML")"    class="codebuttons" name="HTML" />
			-->
				<br />
			<input type="text" name="helpbox" size="50" maxlength="120" readonly="readonly" class="helpbox" value="{$ibforums->lang['hb_start']}" />
				<br />
			<b>{$ibforums->lang['hb_open_tags']}:</b>&nbsp;<input type="text" name="tagcount" size="3" maxlength="3" readonly="readonly" class="helpbox" value="0" />
		</td>
	</tr>
	<tr>
		<td class="pformleft" colspan="2" align="center"><textarea cols="60" rows="12" name="Post" tabindex="3" class="textinput">$t_sig</textarea><br />(<a href="javascript:CheckLength()">{$ibforums->lang['check_length']}</a>)</td>
	</tr>
	<tr>
		<td class="formbuttonrow" colspan="2"><input type="submit" value="{$ibforums->lang['cp_submit_sig']}" /></td>
	</tr>
</table>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// splash
//===========================================================================
function splash($member="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$ibforums->lang['stats_header']}</div>
EOF;
//startif
if ( $ibforums->member['bio'] == "dupemail" )
{
$IPBHTML .= <<<EOF
<div><b>{$ibforums->lang['conv_email_warning_title']}<br /><br />{$ibforums->lang['conv_email_warning']}</b></div>
EOF;
}//endif

$IPBHTML .= <<<EOF
<table cellspacing="0">
	<tr>
		<td width="50%" valign="top">
			<fieldset class="search">
			<legend><b>{$ibforums->lang['splash_attach']}</b></legend>
EOF;
//startif
if ( $member['attach_html'] != "" )
{
$IPBHTML .= <<<EOF
{$member['attach_html']}
EOF;
}//endif
else
{
$IPBHTML .= <<<EOF
<br /><br /><div align="center">{$ibforums->lang['splash_noattach']}</div><br /><br />&nbsp;
EOF;
}//endelse

$IPBHTML .= <<<EOF
			</fieldset>
		</td>
		<td width="50%" valign="top">
			<fieldset class="search">
			<legend><b>{$ibforums->lang['stats_header']}</b></legend>
				<table cellspacing="0">
					<tr>
						<td width="50%"><b>{$ibforums->lang['email_address']}</b></td>
						<td width="50%">{$member['member_email']}</td>
					</tr>
					<tr>
						<td width="50%"><b>{$ibforums->lang['number_posts']}</b></td>
						<td width="50%">{$member['member_posts']}</td>
					</tr>
					<tr>
						<td width="50%"><b>{$ibforums->lang['registered']}</b></td>
						<td width="50%">{$member['date_registered']}</td>
					</tr>
					<tr>
						<td width="50%"><b>{$ibforums->lang['daily_average']}</b></td>
						<td width="50%">{$member['daily_average']}</td>
					</tr>
				</table>
			</fieldset>
		</td>
	</tr>
</table>
<script type="text/javascript" src="jscripts/ipb_forum.js"></script>
<div class="borderwrapm">
<div class="maintitle">{$ibforums->lang['splash_last5']}</div>
	<table cellspacing="1">
EOF;
//startif
if ( $member['topic_html'] != "" )
{
$IPBHTML .= <<<EOF
<tr>
			<th width="40%" nowrap="nowrap" colspan="3">{$ibforums->lang['h_topic_title']}</th>
			<th width="7%" align="center" nowrap="nowrap">{$ibforums->lang['h_replies']}</th>
			<th width="14%" align="center" nowrap="nowrap">{$ibforums->lang['h_topic_starter']}</th>
			<th width="7%" align="center" nowrap="nowrap">{$ibforums->lang['h_hits']}</th>
			<th width="32%" nowrap="nowrap">{$ibforums->lang['h_last_action']}</th>
		</tr>
      {$member['topic_html']}
EOF;
}//endif
else
{
$IPBHTML .= <<<EOF
<tr>
			<td colspan="7" align="center"><b>{$ibforums->lang['splash_nopost']}</b></td>
		</tr>
EOF;
}//endelse
$IPBHTML .= <<<EOF
	</table>
</div>
<div class="formsubtitle">{$ibforums->lang['note_pad']}</div>
<div align="center">
<p>
	<form name="notepad" action="{$ibforums->base_url}" method="post">
	<input type="hidden" name="act" value="UserCP" />
	<input type="hidden" name="s" value="{$ibforums->session_id}" />
	<input type="hidden" name="CODE" value="20" />
	
        <textarea cols="65" rows="{$member['SIZE']}" name="notes">{$member['NOTES']}</textarea>
        	<br />
	    {$ibforums->lang['ta_size']}&nbsp;
	    <select name="ta_size">
	    	{$member['SIZE_CHOICE']}
	    </select>
	<input type="submit" value="{$ibforums->lang['submit_notepad']}" />
	</form>
</p>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// subs_end
//===========================================================================
function subs_end($text="",$days="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td align="center" class="formbuttonrow" valign="middle" colspan="6">
			<select name="trackchoice">
				<option value="unsubscribe">{$ibforums->lang['subs_delete']}</option>
				<option value="none">{$ibforums->lang['subs_c_change']} {$ibforums->lang['subs_none_title']}</option>
				<option value="immediate">{$ibforums->lang['subs_c_change']} {$ibforums->lang['subs_immediate']}</option>
				<option value="delayed">{$ibforums->lang['subs_c_change']} {$ibforums->lang['subs_delayed']}</option>
				<option value="daily">{$ibforums->lang['subs_c_change']} {$ibforums->lang['subs_daily']}</option>
				<option value="weekly">{$ibforums->lang['subs_c_change']} {$ibforums->lang['subs_weekly']}</option>
			</select>&nbsp;&nbsp;
			<input type="submit" class="button" value="{$ibforums->lang['with_selected']}" />
		</td>
	</tr>
</table>
</div>
</form>
<div align="right" style="padding: 5px;"><i>$text</i></div>
<div align="right" style="padding: 5px;">
	<form action="{$ibforums->base_url}act=UserCP&amp;CODE=26" method="post">
		{$ibforums->lang['show_topics_from']}
		<select name="datecut">
			$days
		</select>
 	<input type="submit" value="{$ibforums->lang['jmp_go']}" />
 	</form>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// subs_forum_row
//===========================================================================
function subs_forum_row($fid="",$fname="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
		<td colspan="6" class="row1"><b>$fname</b></td>
	</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// subs_header
//===========================================================================
function subs_header() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<!-- inbox folder -->
<script type="text/javascript">
<!--
	function CheckAll(cb){
		var fmobj = document.mutliact;
			for (var i=0;i<fmobj.elements.length;i++){
				var e = fmobj.elements[i];
				if ((e.name != "allbox") && (e.type=="checkbox") && (!e.disabled)){
				e.checked = fmobj.allbox.checked;
				}
			}
	}
	function CheckCheckAll(cb){	
		var fmobj = document.mutliact;
		var TotalBoxes = 0;
		var TotalOn = 0;
			for (var i=0;i<fmobj.elements.length;i++){
		  		var e = fmobj.elements[i];
		 		 if ((e.name != "allbox") && (e.type=="checkbox")){
			 		 TotalBoxes++;
			 		 if (e.checked){
				 		 TotalOn++;
				 	}
				 }
			}
			
			if (TotalBoxes==TotalOn) {fmobj.allbox.checked=true;}
			else{
				fmobj.allbox.checked=false;
			}
	}
-->
</script>
<div class="formsubtitle">{$ibforums->lang['subs_header']}</div>
<form action="{$ibforums->base_url}" name="mutliact" method="post">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="27" />
<div class="borderwrapm">
	<table cellspacing="1">
		<tr>
			<th width="5%">&nbsp;</th>
			<th width="55%">{$ibforums->lang['subs_topic']}</th>
			<th align="center" width="5%">{$ibforums->lang['subs_replies']}</th>
			<th align="center" width="5%">{$ibforums->lang['subs_view']}</th>
			<th width="25%">{$ibforums->lang['subs_last_post']}</th>
			<th align="center" width="5%"><input name="allbox" type="checkbox" value="Check All" onClick="CheckAll();" /></th>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// subs_none
//===========================================================================
function subs_none() {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
			<td class="row2" align="center" colspan="6">{$ibforums->lang['subs_none']}</td>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// subs_row
//===========================================================================
function subs_row($data="",$type="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
			<td class="row2" align="center" width="5%">{$data['folder_img']}</td>
			<td class="row2">
				<a href="{$ibforums->base_url}act=ST&amp;f={$data['forum_id']}&amp;t={$data['tid']}">{$data['title']}</a>&nbsp;
				( <a href="{$ibforums->base_url}act=ST&amp;f={$data['forum_id']}&amp;t={$data['tid']}" target="_blank">{$ibforums->lang['new_window']}</a> )
  				<div class="desc">{$data['description']}{$ibforums->lang['subs_start']} {$data['track_started']}
  					<br />
  					{$ibforums->lang['subs_c_type']}: {$ibforums->lang[$type]}
  				</div>
  			</td>
  			<td class="row2" align="center">{$data['posts']}</td>
  			<td class="row2" align="center">{$data['views']}</td>
  			<td class="row2">{$data['last_post_date']}<br />{$ibforums->lang['subs_by']} {$data['last_poster']}</td>
  			<td class="row1" align="center"><input type="checkbox" name="id-{$data['trid']}" value="yes" /></td>
  		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// subs_show_choice_page
//===========================================================================
function subs_show_choice_page($forum="",$topic="",$method="",$key="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form action="{$ibforums->base_url}" method="post" name="REPLIER">
<input type="hidden" name="act" value="usercp" />
<input type="hidden" name="CODE" value="end_subs" />
<input type="hidden" name="method" value="$method" />
<input type="hidden" name="auth_key" value="$key" />
<input type="hidden" name="tid" value="{$topic['tid']}" />
<input type="hidden" name="fid" value="{$forum['id']}" />
<input type="hidden" name="st" value="{$ibforums->input['st']}" />
<div class="formsubtitle">{$ibforums->lang['subs_c_title']}</div>
<div style='padding:4px'>
EOF;
//startif
if ( $topic['tid'] != "" )
{
$IPBHTML .= <<<EOF
<b>{$ibforums->lang['subs_c_topic']} {$topic['title']}</b>
EOF;
}//endif
else
{
$IPBHTML .= <<<EOF
<b>{$ibforums->lang['subs_c_forum']} {$forum['name']}</b>
EOF;
}//endelse
$IPBHTML .= <<<EOF
	<div class="desc">{$ibforums->lang['subs_exp_text']}</div>
</div>
<table cellspacing="0">
	<tr>
		<td width="5%" align="center"><input type="radio" name="emailtype" value="none" /></td>
		<td><b>{$ibforums->lang['subs_none_title']}</b><div class="desc">{$ibforums->lang['subs_none_desc']}</div></td>
	</tr>
	<tr>
		<td width="5%" align="center"><input type="radio" name="emailtype" value="delayed" checked="checked" /></td>
		<td><b>{$ibforums->lang['subs_delayed']}</b><div class="desc">{$ibforums->lang['subs_delayed_desc']}</div></td>
	</tr>
	<tr>
		<td width="5%" align="center"><input type="radio" name="emailtype" value="immediate" /></td>
		<td><b>{$ibforums->lang['subs_immediate']}</b><div class="desc">{$ibforums->lang['subs_immediate_desc']}</div></td>
	</tr>
	<tr>
		<td width="5%" align="center"><input type="radio" name="emailtype" value="daily" /></td>
		<td><b>{$ibforums->lang['subs_daily']}</b><div class="desc">{$ibforums->lang['subs_daily_desc']}</div></td>
	</tr>
	<tr>
		<td width="5%" align="center"><input type="radio" name="emailtype" value="weekly" /></td>
		<td><b>{$ibforums->lang['subs_weekly']}</b><div class="desc">{$ibforums->lang['subs_weekly_desc']}</div></td>
	</tr>
	<tr>
		<td class="formbuttonrow" colspan="2"><input type="submit" value="{$ibforums->lang['subs_submit']}" class="button" /></td>
	</tr>
</table>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// ucp_announce_form
//===========================================================================
function ucp_announce_form($announce="",$button="",$forum_html="",$type="",$msg="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<form action="{$ibforums->base_url}" method="post" name="REPLIER">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="announce_save" />
<input type="hidden" name="type" value="$type" />
<input type="hidden" name="id"   value="{$announce['announce_id']}" />
<div class="formsubtitle">{$button}</div>
EOF;
//startif
if ( $msg != "" )
{
$IPBHTML .= <<<EOF
<div class="borderwrapm"><div class="tablepad">{$msg}</div></div>
EOF;
}//endif
$IPBHTML .= <<<EOF
<table cellspacing="0">
	<tr>
		<td class="pformleft"><b>{$ibforums->lang['announce_form_title']}</b></td>
		<td class="pformright" valign="top"><input type="text" size="30" name="announce_title" value="{$announce['announce_title']}" /></td>
	</tr>
	<tr>
		<td class="pformleft"><b>{$ibforums->lang['announce_form_start']}</b><div class="desc">{$ibforums->lang['announce_form_startdesc']}</div></td>
		<td class="pformright" valign="top"><input type="text" size="10" name="announce_start" value="{$announce['announce_start']}" /></td>
	</tr>
	<tr>
		<td class="pformleft"><b>{$ibforums->lang['announce_form_end']}</b><div class="desc">{$ibforums->lang['announce_form_enddesc']}</div></td>
		<td class="pformright" valign="top"><input type="text" size="10" name="announce_end" value="{$announce['announce_end']}" /></td>
	</tr>
	<tr>
		<td class="pformleft" valign="top"><b>{$ibforums->lang['announce_form_forums']}</b><div class="desc">{$ibforums->lang['announce_form_forums2']}</div></td>
		<td class="pformright" valign="top"><select class="dropdown" multiple="multiple" size="10" name="announce_forum[]">$forum_html</td>
	</tr>
	<tr>
		<td class="pformleft" valign="top"><b>{$ibforums->lang['announce_form_content']}</b></td>
		<td class="pformright" valign="top"><textarea cols="50" class="textarea" rows="15" name="announce_post" tabindex="3">{$announce['announce_post']}</textarea></td>
	</tr>
	<tr>
		<td class="pformleft" valign="top"><b>{$ibforums->lang['announce_form_options']}</b></td>
		<td class="pformright" valign="middle">
			<input type="checkbox" class="checkbox" name="announce_active" value="1" {$announce['announce_active_checked']} />&nbsp;{$ibforums->lang['announce_form_enable']}
			<br /><input type="checkbox" class="checkbox" name="announce_html_enabled" value="1" {$announce['announce_html_enabled']} />&nbsp;{$ibforums->lang['announce_use_html']}
		</td>
	</tr>
	<tr>
		<td class="formbuttonrow" colspan="2"><input type="submit" value="{$button}" class="button" /></td>
	</tr>
</table>
</form>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// ucp_announce_manage
//===========================================================================
function ucp_announce_manage($content="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<script type="text/javascript">
<!--
 var ipb_lang_js_del_1 = "{$ibforums->lang['announce_del1']}";
 var ipb_lang_js_del_2 = "{$ibforums->lang['announce_del2']}";
-->
</script>
<script type="text/javascript" src="jscripts/ipb_topic.js"></script>
<div class="formsubtitle">{$ibforums->lang['announce_current']}</div>
<form action="{$ibforums->base_url}" name="mutliact" method="post">
<input type="hidden" name="act" value="UserCP" />
<input type="hidden" name="CODE" value="announce_alter" />
<div class="borderwrapm">
	<table cellspacing="1">
		<tr>
			<th width="35%">{$ibforums->lang['announce_title']}</th>
			<th align="center" width="10%">{$ibforums->lang['announce_starts']}</th>
			<th align="center" width="10%">{$ibforums->lang['announce_end']}</th>
			<th width="25%">{$ibforums->lang['announce_forums']}</th>
			<th width="15%">&nbsp;</th>
		</tr>
EOF;
//startif
if ( $content )
{
$IPBHTML .= <<<EOF
$content
EOF;
}//endif
else
{
$IPBHTML .= <<<EOF
<tr>
			<td align="center" colspan="5">{$ibforums->lang['announce_none']}</td>
		</tr>
EOF;
}//endelse
$IPBHTML .= <<<EOF
	<tr>
		<td class="formbuttonrow" colspan="5"><a href="{$ibforums->base_url}act=usercp&amp;CODE=announce_add">{$ibforums->lang['announce_add']}</a></td>
	</tr>
	</table>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// ucp_announce_manage_row
//===========================================================================
function ucp_announce_manage_row($announce="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
			<td class="row1"><b><a href="{$ibforums->base_url}act=announce&amp;id={$announce['announce_id']}">{$announce['announce_title']}</a></b> {$announce['announce_inactive']}<div class="desc">{$ibforums->lang['announce_by']} {$announce['name']}</div></td>
			<td class="row1" align="center">{$announce['announce_starts_converted']}</td>
			<td class="row1" align="center">{$announce['announce_end_converted']}</td>
			<td class="row1"><div class="forumdesc">{$announce['announce_forum_show']}</div></td>
			<td class="row1" align="center">
				<a href="{$ibforums->base_url}act=usercp&amp;CODE=announce_edit&amp;id={$announce['announce_id']}">{$ibforums->lang['announce_edit']}</a>
				&middot; <a href="#" onclick="delete_post('{$ibforums->base_url}act=usercp&amp;CODE=announce_delete&amp;id={$announce['announce_id']}'); return false;">{$ibforums->lang['announce_delete']}</a>
			</td>
		</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// ucp_message
//===========================================================================
function ucp_message($title="",$msg="") {
global $ibforums;
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class="formsubtitle">{$title}</div>
	<p>$msg</p>
EOF;

//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>